### DISCUSSION TITLE
Cuda error bitsandbytes - Arch linux

### DISCUSSION THREAD

**Discussion by NulliferBones** [bmaltais/kohya_ss#2651] [Q&A]
Hello, i'm getting this error when trying to start training
I can't figure out what to do. I tried visiting the links and they all seem to 404.
Anyone able to help me fix this error?
```
CUDA SETUP: Loading binary /home/nullifer/Documents/AI/kohya_ss/venv/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda118_nocublaslt.so...
libcusparse.so.11: cannot open shared object file: No such file or directory
CUDA SETUP: Problem: The main issue seems to be that the main CUDA runtime library was not detected.
CUDA SETUP: Solution 1: To solve the issue the libcudart.so location needs to be added to the LD_LIBRARY_PATH variable
CUDA SETUP: Solution 1a): Find the cuda runtime library via: find / -name libcudart.so 2>/dev/null
CUDA SETUP: Solution 1b): Once the library is found add it to the LD_LIBRARY_PATH: export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:FOUND_PATH_FROM_1a
CUDA SETUP: Solution 1c): For a permanent solution add the export from 1b into your .bashrc file, located at ~/.bashrc
CUDA SETUP: Solution 2: If no library was found in step 1a) you need to install CUDA.
CUDA SETUP: Solution 2a): Download CUDA install script: wget https://raw.githubusercontent.com/TimDettmers/bitsandbytes/main/cuda_install.sh
CUDA SETUP: Solution 2b): Install desired CUDA version to desired location. The syntax is bash cuda_install.sh CUDA_VERSION PATH_TO_INSTALL_INTO.
CUDA SETUP: Solution 2b): For example, "bash cuda_install.sh 113 ~/local/" will download CUDA 11.3 and install into the folder ~/local
```

**Comment by b-fission** [comment]
The install script for solution 2 is here: https://github.com/bitsandbytes-foundation/bitsandbytes/blob/main/install_cuda.py

Try installing CUDA Toolkit 11.8 or higher.

**Comment by NulliferBones** [comment]
I do have cuda installed

**Reply by b-fission** [reply]
You installed a Cuda Toolkit, not just the Cuda runtime that come with nvidia's driver, right?
So, what output do you get if you run `nvcc --version` on a terminal?

**Reply by NulliferBones** [reply]
```
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2024 NVIDIA Corporation
Built on Thu_Jun__6_02:18:23_PDT_2024
Cuda compilation tools, release 12.5, V12.5.82
Build cuda_12.5.r12.5/compiler.34385749_0

```

**Reply by b-fission** [reply]
Cuda 12.5 is very recent, so you'll need to update to `bitsandbytes==0.43.3` for compatibility at this time.

Open your copy of [requirements_linux.txt](https://github.com/bmaltais/kohya_ss/blob/726ea78657fb5c09dffec22a3979d583b9e84cbf/requirements_linux.txt#L2) and set the version number there.
The update should begin the next time you start the gui.

**Reply by NulliferBones** [reply]
I get this error now when trying to use Adamw8bit
is it just because I have a GTX 1060? If i remember correctly it works fine on windows.

```
Traceback (most recent call last):
  File "/home/nullifer/Documents/AI/KohyaSS/kohya_ss/sd-scripts/train_network.py", line 1242, in <module>
    trainer.train(args)
  File "/home/nullifer/Documents/AI/KohyaSS/kohya_ss/sd-scripts/train_network.py", line 1012, in train
    optimizer.step()
  File "/home/nullifer/Documents/AI/KohyaSS/kohya_ss/venv/lib/python3.10/site-packages/accelerate/optimizer.py", line 132, in step
    self.scaler.step(self.optimizer, closure)
  File "/home/nullifer/Documents/AI/KohyaSS/kohya_ss/venv/lib/python3.10/site-packages/torch/cuda/amp/grad_scaler.py", line 416, in step
    retval = self._maybe_opt_step(optimizer, optimizer_state, *args, **kwargs)
  File "/home/nullifer/Documents/AI/KohyaSS/kohya_ss/venv/lib/python3.10/site-packages/torch/cuda/amp/grad_scaler.py", line 315, in _maybe_opt_step
    retval = optimizer.step(*args, **kwargs)
  File "/home/nullifer/Documents/AI/KohyaSS/kohya_ss/venv/lib/python3.10/site-packages/accelerate/optimizer.py", line 185, in patched_step
    return method(*args, **kwargs)
  File "/home/nullifer/Documents/AI/KohyaSS/kohya_ss/venv/lib/python3.10/site-packages/torch/optim/lr_scheduler.py", line 68, in wrapper
    return wrapped(*args, **kwargs)
  File "/home/nullifer/Documents/AI/KohyaSS/kohya_ss/venv/lib/python3.10/site-packages/torch/optim/optimizer.py", line 373, in wrapper
    out = func(*args, **kwargs)
  File "/home/nullifer/Documents/AI/KohyaSS/kohya_ss/venv/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/nullifer/Documents/AI/KohyaSS/kohya_ss/venv/lib/python3.10/site-packages/bitsandbytes/optim/optimizer.py", line 287, in step
    self.update_step(group, p, gindex, pindex)
  File "/home/nullifer/Documents/AI/KohyaSS/kohya_ss/venv/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/nullifer/Documents/AI/KohyaSS/kohya_ss/venv/lib/python3.10/site-packages/bitsandbytes/optim/optimizer.py", line 546, in update_step
    F.optimizer_update_8bit_blockwise(
  File "/home/nullifer/Documents/AI/KohyaSS/kohya_ss/venv/lib/python3.10/site-packages/bitsandbytes/functional.py", line 1777, in optimizer_update_8bit_blockwise
    optim_func = str2optimizer8bit_blockwise[optimizer_name][0]
NameError: name 'str2optimizer8bit_blockwise' is not defined
steps:   0%|                                                                        | 0/1254 [00:05<?, ?it/s, avr_loss=0.215]
Traceback (most recent call last):
  File "/home/nullifer/Documents/AI/KohyaSS/kohya_ss/venv/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/home/nullifer/Documents/AI/KohyaSS/kohya_ss/venv/lib/python3.10/site-packages/accelerate/commands/accelerate_cli.py", line 47, in main
    args.func(args)
  File "/home/nullifer/Documents/AI/KohyaSS/kohya_ss/venv/lib/python3.10/site-packages/accelerate/commands/launch.py", line 1017, in launch_command
    simple_launcher(args)
  File "/home/nullifer/Documents/AI/KohyaSS/kohya_ss/venv/lib/python3.10/site-packages/accelerate/commands/launch.py", line 637, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/home/nullifer/Documents/AI/KohyaSS/kohya_ss/venv/bin/python', '/home/nullifer/Documents/AI/KohyaSS/kohya_ss/sd-scripts/train_network.py', '--config_file', '/home/nullifer/Documents/2/model/config_lora-20240801-000103.toml']' returned non-zero exit status 1.
```

**Reply by b-fission** [reply]
If it can't find `str2optimizer8bit_blockwise` then it's probably because the path to the cuda toolkit's lib64 folder isn't specified in `LD_LIBRARY_PATH`.

**Reply by NulliferBones** [reply]
oh right, i forgot about that. I was trying to figure that out and couldn't understand how to specify that.
but the thing is, it says cuda toolkit found when i boot it up, which is odd

**Reply by b-fission** [reply]
You can do
`export LD_LIBRARY_PATH=/path/to/your/cuda-12.5/lib64`
and then run gui.sh on the same terminal session. I'm not 100% sure if the toolkit's lib64 is present at its install path, or a subfolder. You'll need to double-check in that.

**Reply by b-fission** [reply]
> it says cuda toolkit found when i boot it up, which is odd

That's only because pytorch includes a subset of the cuda libs, which get detected. 
bitsandbytes requires some additional cuda libs, which is why the toolkit is needed to successfully run.

**Reply by NulliferBones** [reply]
still got this error

```
Traceback (most recent call last):
  File "/home/nullifer/Documents/AI/KohyaSS/kohya_ss/sd-scripts/train_network.py", line 1242, in <module>
    trainer.train(args)
  File "/home/nullifer/Documents/AI/KohyaSS/kohya_ss/sd-scripts/train_network.py", line 1012, in train
    optimizer.step()
  File "/home/nullifer/Documents/AI/KohyaSS/kohya_ss/venv/lib/python3.10/site-packages/accelerate/optimizer.py", line 132, in step
    self.scaler.step(self.optimizer, closure)
  File "/home/nullifer/Documents/AI/KohyaSS/kohya_ss/venv/lib/python3.10/site-packages/torch/cuda/amp/grad_scaler.py", line 416, in step
    retval = self._maybe_opt_step(optimizer, optimizer_state, *args, **kwargs)
  File "/home/nullifer/Documents/AI/KohyaSS/kohya_ss/venv/lib/python3.10/site-packages/torch/cuda/amp/grad_scaler.py", line 315, in _maybe_opt_step
    retval = optimizer.step(*args, **kwargs)
  File "/home/nullifer/Documents/AI/KohyaSS/kohya_ss/venv/lib/python3.10/site-packages/accelerate/optimizer.py", line 185, in patched_step
    return method(*args, **kwargs)
  File "/home/nullifer/Documents/AI/KohyaSS/kohya_ss/venv/lib/python3.10/site-packages/torch/optim/lr_scheduler.py", line 68, in wrapper
    return wrapped(*args, **kwargs)
  File "/home/nullifer/Documents/AI/KohyaSS/kohya_ss/venv/lib/python3.10/site-packages/torch/optim/optimizer.py", line 373, in wrapper
    out = func(*args, **kwargs)
  File "/home/nullifer/Documents/AI/KohyaSS/kohya_ss/venv/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/nullifer/Documents/AI/KohyaSS/kohya_ss/venv/lib/python3.10/site-packages/bitsandbytes/optim/optimizer.py", line 287, in step
    self.update_step(group, p, gindex, pindex)
  File "/home/nullifer/Documents/AI/KohyaSS/kohya_ss/venv/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/nullifer/Documents/AI/KohyaSS/kohya_ss/venv/lib/python3.10/site-packages/bitsandbytes/optim/optimizer.py", line 546, in update_step
    F.optimizer_update_8bit_blockwise(
  File "/home/nullifer/Documents/AI/KohyaSS/kohya_ss/venv/lib/python3.10/site-packages/bitsandbytes/functional.py", line 1777, in optimizer_update_8bit_blockwise
    optim_func = str2optimizer8bit_blockwise[optimizer_name][0]
NameError: name 'str2optimizer8bit_blockwise' is not defined
steps:   0%|                                                                                        | 0/1600 [00:01<?, ?it/s]
Traceback (most recent call last):
  File "/home/nullifer/Documents/AI/KohyaSS/kohya_ss/venv/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/home/nullifer/Documents/AI/KohyaSS/kohya_ss/venv/lib/python3.10/site-packages/accelerate/commands/accelerate_cli.py", line 47, in main
    args.func(args)
  File "/home/nullifer/Documents/AI/KohyaSS/kohya_ss/venv/lib/python3.10/site-packages/accelerate/commands/launch.py", line 1017, in launch_command
    simple_launcher(args)
  File "/home/nullifer/Documents/AI/KohyaSS/kohya_ss/venv/lib/python3.10/site-packages/accelerate/commands/launch.py", line 637, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/home/nullifer/Documents/AI/KohyaSS/kohya_ss/venv/bin/python', '/home/nullifer/Documents/AI/KohyaSS/kohya_ss/sd-scripts/train_network.py', '--config_file', '/home/nullifer/Documents/AI/2/model/config_lora-20240801-010754.toml']' returned non-zero exit status 1.
```

**Reply by b-fission** [reply]
Maybe LD_LIBRARY_PATH isn't correct. Do you know the path to the cuda toolkit's `libcudart.so.12` file?

**Reply by NulliferBones** [reply]
yeah its in opt/cuda/lib64
that's what i exported

**Comment by b-fission** [comment]
Ok, so it wants libcusparse.so.11 which isn't part of the toolkit since you've installed version 12.

For your system, try this...
`export LD_LIBRARY_PATH=/home/nullifer/Documents/AI/KohyaSS/kohya_ss/venv/lib/python3.10/site-packages/nvidia/cusparse/lib`

If it works, then you won't need the cuda-12 toolkit.
kohya_ss currently expects toolkit 11.8, so you shouldn't try to mix and match v11 and v12.

**Reply by NulliferBones** [reply]
unfortunately it did not work, i notcied that i also have these messages when i boot up Kohya, not sure if it's related.

```
Warning: LD_LIBRARY_PATH environment variable is not set.
Certain functionalities may not work correctly.
Please ensure that the required libraries are properly configured.
 
If you use WSL2 you may want to: export LD_LIBRARY_PATH=/usr/lib/wsl/lib/
 
02:51:04-315513 INFO     Kohya_ss GUI version: v24.1.5                                                                       
02:51:04-363797 INFO     Submodule initialized and updated.                                                                  
02:51:04-365057 INFO     nVidia toolkit detected                                                                             
02:51:05-689987 INFO     Torch 2.1.2+cu118                                                                                   
02:51:05-705696 INFO     Torch backend: nVidia CUDA 11.8 cuDNN 8700                                                          
02:51:05-719453 INFO     Torch detected GPU: NVIDIA GeForce GTX 1060 6GB VRAM 6063 Arch (6, 1) Cores 10                      
02:51:05-723846 INFO     Python version is 3.10.14 (main, Jul 13 2024, 23:55:04) [GCC 14.1.1 20240522]                       
02:51:05-725229 INFO     Verifying modules installation status from                                                          
                         /home/nullifer/Documents/AI/KohyaSS/kohya_ss/requirements_linux.txt...                              
02:51:05-728933 INFO     Verifying modules installation status from requirements.txt...                                      
2024-08-01 02:51:08.589885: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-08-01 02:51:08.589927: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-08-01 02:51:08.591286: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-08-01 02:51:08.598324: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-08-01 02:51:09.440579: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
02:51:12-387672 INFO     headless: False                                                                                     
02:51:12-448108 INFO     Using shell=True when running external commands...                                                  
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.

```

**Reply by NulliferBones** [reply]
honestly i would have just installed cuda 11.8, but it seems nearly impossible to do so anymore on arch. tried everything.

**Reply by b-fission** [reply]
I'm confused. It shouldn't be saying `LD_LIBRARY_PATH environment variable is not set`  since you _did_ set it using `export`. Are you running `export` and then `gui.sh` on the same session? Not exiting or changing terminals, right?

> i notcied that i also have these messages when i boot up Kohya, not sure if it's related.

If you're referring to those TensorFlow messages, those can be ignored. The training code doesn't use TensorFlow.

**Reply by NulliferBones** [reply]
yes, I did as you instructed. export and then run gui in the same terminal session

**Reply by b-fission** [reply]
Let's try going back to bitsandbytes-0.43.0 first. 
Can you run `git restore requirements_linux.txt`

Then start the gui with this one-liner:
`LD_LIBRARY_PATH=venv/lib/python3.10/site-packages/nvidia/cusparse/lib ./gui.sh`

**Reply by NulliferBones** [reply]
just tried it and it says the exact same thing on launch

**Reply by b-fission** [reply]
Does the file `libcusparse.so.11` exist in the venv at `kohya_ss/venv/lib/python3.10/site-packages/nvidia/cusparse/lib/libcusparse.so.11`
The file size should be about 228 MB.

**Reply by NulliferBones** [reply]
there is no Nvidia folder inside of site-packages

**Reply by b-fission** [reply]
Try installing it with this command: `./venv/bin/pip install nvidia-cusparse-cu11`

**Reply by NulliferBones** [reply]
alright i did, the file is still not in that location

**Reply by b-fission** [reply]
You ran it from the kohya_ss directory, right? The exact command above, and the files didn't install?

**Reply by NulliferBones** [reply]
yes i did exactly as you requested
I tried doing it again to confirm and received this message
Requirement already satisfied: nvidia-cusparse-cu11 in ./venv/lib/python3.10/site-packages (11.7.5.86)

when i go to the location there is the folder called nvidia_cusparse_cu11-11.7.5.86.dist-info
inside there are only text files
Requested, installer, license.txt,  metadata, record, top-level.txt, wheel

i'm guessing i should run install from the folder?

**Reply by b-fission** [reply]
Try it again, but with the `-I` option. Run it from the kohya_ss directory like before.

`./venv/bin/pip install -I nvidia-cusparse-cu11`

If that works, it would be installed in `venv/lib/python3.10/site-packages/nvidia/cusparse/`

You might need to install two more packages.
`./venv/bin/pip install -I nvidia-cublas-cu11`
`./venv/bin/pip install -I nvidia-cuda_runtime-cu11`

**Reply by NulliferBones** [reply]
the file is in the location now, same warning on launch and now i get this message when using adamw8bit

```

/home/nullifer/Documents/AI/KohyaSS/kohya_ss/venv/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py:183: UserWarning: Welcome to bitsandbytes. For bug reports, please run

python -m bitsandbytes


  warn(msg)
================================================================================
The following directories listed in your path were found to be non-existent: {PosixPath('/home/nullifer/Documents/AI/KohyaSS/kohya_ss/venv/lib/python3.10/site-packages/cv2/../../lib64')}
/home/nullifer/Documents/AI/KohyaSS/kohya_ss/venv/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py:183: UserWarning: /home/nullifer/Documents/AI/KohyaSS/kohya_ss/venv/lib/python3.10/site-packages/cv2/../../lib64: did not contain ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0', 'libcudart.so.12.1', 'libcudart.so.12.2'] as expected! Searching further paths...
  warn(msg)
The following directories listed in your path were found to be non-existent: {PosixPath('local/archlinux'), PosixPath('@/tmp/.ICE-unix/948,unix/archlinux')}
The following directories listed in your path were found to be non-existent: {PosixPath('/org/freedesktop/DisplayManager/Session1')}
The following directories listed in your path were found to be non-existent: {PosixPath('/etc/gtk/gtkrc'), PosixPath('/home/nullifer/.gtkrc')}
The following directories listed in your path were found to be non-existent: {PosixPath('/etc/gtk-2.0/gtkrc')}
The following directories listed in your path were found to be non-existent: {PosixPath('/Sessions/1')}
The following directories listed in your path were found to be non-existent: {PosixPath('/org/freedesktop/DisplayManager/Seat0')}
The following directories listed in your path were found to be non-existent: {PosixPath('https'), PosixPath('//debuginfod.archlinux.org ')}
The following directories listed in your path were found to be non-existent: {PosixPath('/Windows/1')}
CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching in backup paths...
The following directories listed in your path were found to be non-existent: {PosixPath('/usr/local/cuda/lib64')}
DEBUG: Possible options found for libcudart.so: set()
CUDA SETUP: PyTorch settings found: CUDA_VERSION=118, Highest Compute Capability: 6.1.
CUDA SETUP: To manually override the PyTorch CUDA version please see:https://github.com/TimDettmers/bitsandbytes/blob/main/how_to_use_nonpytorch_cuda.md
/home/nullifer/Documents/AI/KohyaSS/kohya_ss/venv/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py:183: UserWarning: WARNING: Compute capability < 7.5 detected! Only slow 8-bit matmul is supported for your GPU!                     If you run into issues with 8-bit matmul, you can try 4-bit quantization: https://huggingface.co/blog/4bit-transformers-bitsandbytes
  warn(msg)
CUDA SETUP: Loading binary /home/nullifer/Documents/AI/KohyaSS/kohya_ss/venv/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda118_nocublaslt.so...
libcusparse.so.11: cannot open shared object file: No such file or directory
CUDA SETUP: Problem: The main issue seems to be that the main CUDA runtime library was not detected.
CUDA SETUP: Solution 1: To solve the issue the libcudart.so location needs to be added to the LD_LIBRARY_PATH variable
CUDA SETUP: Solution 1a): Find the cuda runtime library via: find / -name libcudart.so 2>/dev/null
CUDA SETUP: Solution 1b): Once the library is found add it to the LD_LIBRARY_PATH: export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:FOUND_PATH_FROM_1a
CUDA SETUP: Solution 1c): For a permanent solution add the export from 1b into your .bashrc file, located at ~/.bashrc
CUDA SETUP: Solution 2: If no library was found in step 1a) you need to install CUDA.
CUDA SETUP: Solution 2a): Download CUDA install script: wget https://raw.githubusercontent.com/TimDettmers/bitsandbytes/main/cuda_install.sh
CUDA SETUP: Solution 2b): Install desired CUDA version to desired location. The syntax is bash cuda_install.sh CUDA_VERSION PATH_TO_INSTALL_INTO.
CUDA SETUP: Solution 2b): For example, "bash cuda_install.sh 113 ~/local/" will download CUDA 11.3 and install into the folder ~/local
Traceback (most recent call last):
  File "/home/nullifer/Documents/AI/KohyaSS/kohya_ss/sd-scripts/train_network.py", line 1242, in <module>
    trainer.train(args)
  File "/home/nullifer/Documents/AI/KohyaSS/kohya_ss/sd-scripts/train_network.py", line 367, in train
    optimizer_name, optimizer_args, optimizer = train_util.get_optimizer(args, trainable_params)
  File "/home/nullifer/Documents/AI/KohyaSS/kohya_ss/sd-scripts/library/train_util.py", line 4322, in get_optimizer
    import bitsandbytes as bnb
  File "/home/nullifer/Documents/AI/KohyaSS/kohya_ss/venv/lib/python3.10/site-packages/bitsandbytes/__init__.py", line 6, in <module>
    from . import cuda_setup, research, utils
  File "/home/nullifer/Documents/AI/KohyaSS/kohya_ss/venv/lib/python3.10/site-packages/bitsandbytes/research/__init__.py", line 2, in <module>
    from .autograd._functions import (
  File "/home/nullifer/Documents/AI/KohyaSS/kohya_ss/venv/lib/python3.10/site-packages/bitsandbytes/research/autograd/_functions.py", line 8, in <module>
    from bitsandbytes.autograd._functions import GlobalOutlierPooler, MatmulLtState
  File "/home/nullifer/Documents/AI/KohyaSS/kohya_ss/venv/lib/python3.10/site-packages/bitsandbytes/autograd/__init__.py", line 1, in <module>
    from ._functions import get_inverse_transform_indices, undo_layout
  File "/home/nullifer/Documents/AI/KohyaSS/kohya_ss/venv/lib/python3.10/site-packages/bitsandbytes/autograd/_functions.py", line 10, in <module>
    import bitsandbytes.functional as F
  File "/home/nullifer/Documents/AI/KohyaSS/kohya_ss/venv/lib/python3.10/site-packages/bitsandbytes/functional.py", line 17, in <module>
    from .cextension import COMPILED_WITH_CUDA, lib
  File "/home/nullifer/Documents/AI/KohyaSS/kohya_ss/venv/lib/python3.10/site-packages/bitsandbytes/cextension.py", line 17, in <module>
    raise RuntimeError('''
RuntimeError: 
        CUDA Setup failed despite GPU being available. Please run the following command to get more information:

        python -m bitsandbytes

        Inspect the output of the command and see if you can locate CUDA libraries. You might need to add them
        to your LD_LIBRARY_PATH. If you suspect a bug, please take the information from python -m bitsandbytes
        and open an issue at: https://github.com/TimDettmers/bitsandbytes/issues
Traceback (most recent call last):
  File "/home/nullifer/Documents/AI/KohyaSS/kohya_ss/venv/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/home/nullifer/Documents/AI/KohyaSS/kohya_ss/venv/lib/python3.10/site-packages/accelerate/commands/accelerate_cli.py", line 47, in main
    args.func(args)
  File "/home/nullifer/Documents/AI/KohyaSS/kohya_ss/venv/lib/python3.10/site-packages/accelerate/commands/launch.py", line 1017, in launch_command
    simple_launcher(args)
  File "/home/nullifer/Documents/AI/KohyaSS/kohya_ss/venv/lib/python3.10/site-packages/accelerate/commands/launch.py", line 637, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/home/nullifer/Documents/AI/KohyaSS/kohya_ss/venv/bin/python', '/home/nullifer/Documents/AI/KohyaSS/kohya_ss/sd-scripts/train_network.py', '--config_file', '/home/nullifer/Documents/AI/2/model/config_lora-20240803-013528.toml']' returned non-zero exit status 1.
```

**Reply by b-fission** [reply]
Alright, that's progress. Now it also needs the paths for the other two dependencies in LD_LIBRARY_PATH. Use this command to start the gui...

`LD_LIBRARY_PATH=venv/lib/python3.10/site-packages/nvidia/cusparse/lib:venv/lib/python3.10/site-packages/nvidia/cublas/lib:venv/lib/python3.10/site-packages/nvidia/cuda_runtime/lib ./gui.sh`

**Reply by NulliferBones** [reply]
same message on startup and same message when using adamw8bit i think


```
===================================BUG REPORT===================================
/home/nullifer/Documents/AI/KohyaSS/kohya_ss/venv/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py:183: UserWarning: Welcome to bitsandbytes. For bug reports, please run

python -m bitsandbytes


  warn(msg)
================================================================================
The following directories listed in your path were found to be non-existent: {PosixPath('/home/nullifer/Documents/AI/KohyaSS/kohya_ss/venv/lib/python3.10/site-packages/cv2/../../lib64')}
/home/nullifer/Documents/AI/KohyaSS/kohya_ss/venv/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py:183: UserWarning: /home/nullifer/Documents/AI/KohyaSS/kohya_ss/venv/lib/python3.10/site-packages/cv2/../../lib64: did not contain ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0', 'libcudart.so.12.1', 'libcudart.so.12.2'] as expected! Searching further paths...
  warn(msg)
The following directories listed in your path were found to be non-existent: {PosixPath('local/archlinux'), PosixPath('@/tmp/.ICE-unix/948,unix/archlinux')}
The following directories listed in your path were found to be non-existent: {PosixPath('/org/freedesktop/DisplayManager/Session1')}
The following directories listed in your path were found to be non-existent: {PosixPath('/etc/gtk/gtkrc'), PosixPath('/home/nullifer/.gtkrc')}
The following directories listed in your path were found to be non-existent: {PosixPath('/etc/gtk-2.0/gtkrc')}
The following directories listed in your path were found to be non-existent: {PosixPath('/Sessions/1')}
The following directories listed in your path were found to be non-existent: {PosixPath('/org/freedesktop/DisplayManager/Seat0')}
The following directories listed in your path were found to be non-existent: {PosixPath('//debuginfod.archlinux.org '), PosixPath('https')}
The following directories listed in your path were found to be non-existent: {PosixPath('/Windows/1')}
CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching in backup paths...
The following directories listed in your path were found to be non-existent: {PosixPath('/usr/local/cuda/lib64')}
DEBUG: Possible options found for libcudart.so: set()
CUDA SETUP: PyTorch settings found: CUDA_VERSION=118, Highest Compute Capability: 6.1.
CUDA SETUP: To manually override the PyTorch CUDA version please see:https://github.com/TimDettmers/bitsandbytes/blob/main/how_to_use_nonpytorch_cuda.md
/home/nullifer/Documents/AI/KohyaSS/kohya_ss/venv/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py:183: UserWarning: WARNING: Compute capability < 7.5 detected! Only slow 8-bit matmul is supported for your GPU!                     If you run into issues with 8-bit matmul, you can try 4-bit quantization: https://huggingface.co/blog/4bit-transformers-bitsandbytes
  warn(msg)
CUDA SETUP: Loading binary /home/nullifer/Documents/AI/KohyaSS/kohya_ss/venv/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda118_nocublaslt.so...
libcusparse.so.11: cannot open shared object file: No such file or directory
CUDA SETUP: Problem: The main issue seems to be that the main CUDA runtime library was not detected.
CUDA SETUP: Solution 1: To solve the issue the libcudart.so location needs to be added to the LD_LIBRARY_PATH variable
CUDA SETUP: Solution 1a): Find the cuda runtime library via: find / -name libcudart.so 2>/dev/null
CUDA SETUP: Solution 1b): Once the library is found add it to the LD_LIBRARY_PATH: export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:FOUND_PATH_FROM_1a
CUDA SETUP: Solution 1c): For a permanent solution add the export from 1b into your .bashrc file, located at ~/.bashrc
CUDA SETUP: Solution 2: If no library was found in step 1a) you need to install CUDA.
CUDA SETUP: Solution 2a): Download CUDA install script: wget https://raw.githubusercontent.com/TimDettmers/bitsandbytes/main/cuda_install.sh
CUDA SETUP: Solution 2b): Install desired CUDA version to desired location. The syntax is bash cuda_install.sh CUDA_VERSION PATH_TO_INSTALL_INTO.
CUDA SETUP: Solution 2b): For example, "bash cuda_install.sh 113 ~/local/" will download CUDA 11.3 and install into the folder ~/local
Traceback (most recent call last):
  File "/home/nullifer/Documents/AI/KohyaSS/kohya_ss/sd-scripts/train_network.py", line 1242, in <module>
    trainer.train(args)
  File "/home/nullifer/Documents/AI/KohyaSS/kohya_ss/sd-scripts/train_network.py", line 367, in train
    optimizer_name, optimizer_args, optimizer = train_util.get_optimizer(args, trainable_params)
  File "/home/nullifer/Documents/AI/KohyaSS/kohya_ss/sd-scripts/library/train_util.py", line 4322, in get_optimizer
    import bitsandbytes as bnb
  File "/home/nullifer/Documents/AI/KohyaSS/kohya_ss/venv/lib/python3.10/site-packages/bitsandbytes/__init__.py", line 6, in <module>
    from . import cuda_setup, research, utils
  File "/home/nullifer/Documents/AI/KohyaSS/kohya_ss/venv/lib/python3.10/site-packages/bitsandbytes/research/__init__.py", line 2, in <module>
    from .autograd._functions import (
  File "/home/nullifer/Documents/AI/KohyaSS/kohya_ss/venv/lib/python3.10/site-packages/bitsandbytes/research/autograd/_functions.py", line 8, in <module>
    from bitsandbytes.autograd._functions import GlobalOutlierPooler, MatmulLtState
  File "/home/nullifer/Documents/AI/KohyaSS/kohya_ss/venv/lib/python3.10/site-packages/bitsandbytes/autograd/__init__.py", line 1, in <module>
    from ._functions import get_inverse_transform_indices, undo_layout
  File "/home/nullifer/Documents/AI/KohyaSS/kohya_ss/venv/lib/python3.10/site-packages/bitsandbytes/autograd/_functions.py", line 10, in <module>
    import bitsandbytes.functional as F
  File "/home/nullifer/Documents/AI/KohyaSS/kohya_ss/venv/lib/python3.10/site-packages/bitsandbytes/functional.py", line 17, in <module>
    from .cextension import COMPILED_WITH_CUDA, lib
  File "/home/nullifer/Documents/AI/KohyaSS/kohya_ss/venv/lib/python3.10/site-packages/bitsandbytes/cextension.py", line 17, in <module>
    raise RuntimeError('''
RuntimeError: 
        CUDA Setup failed despite GPU being available. Please run the following command to get more information:

        python -m bitsandbytes

        Inspect the output of the command and see if you can locate CUDA libraries. You might need to add them
        to your LD_LIBRARY_PATH. If you suspect a bug, please take the information from python -m bitsandbytes
        and open an issue at: https://github.com/TimDettmers/bitsandbytes/issues
Traceback (most recent call last):
  File "/home/nullifer/Documents/AI/KohyaSS/kohya_ss/venv/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/home/nullifer/Documents/AI/KohyaSS/kohya_ss/venv/lib/python3.10/site-packages/accelerate/commands/accelerate_cli.py", line 47, in main
    args.func(args)
  File "/home/nullifer/Documents/AI/KohyaSS/kohya_ss/venv/lib/python3.10/site-packages/accelerate/commands/launch.py", line 1017, in launch_command
    simple_launcher(args)
  File "/home/nullifer/Documents/AI/KohyaSS/kohya_ss/venv/lib/python3.10/site-packages/accelerate/commands/launch.py", line 637, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/home/nullifer/Documents/AI/KohyaSS/kohya_ss/venv/bin/python', '/home/nullifer/Documents/AI/KohyaSS/kohya_ss/sd-scripts/train_network.py', '--config_file', '/home/nullifer/Documents/AI/2/model/config_lora-20240803-015756.toml']' returned non-zero exit status 1.
```

**Reply by b-fission** [reply]
Despite that, both error logs still complain about a missing `libcusparse.so.11`

**Reply by NulliferBones** [reply]
that file is here so i dont know why it's still complaining
 /home/nullifer/Documents/AI/KohyaSS/kohya_ss/venv/lib/python3.10/site-packages/nvidia/cusparse/lib/libcusparse.so.11

**Reply by b-fission** [reply]
Another sanity check... can you run these commands from the kohya_ss directory?

```bash
export NVDIR=`pwd`/venv/lib/python3.10/site-packages/nvidia
export LD_LIBRARY_PATH=$NVDIR/cusparse/lib:$NVDIR/cublas/lib:$NVDIR/cuda_runtime/lib
ldd venv/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda118_nocublaslt.so
```

Do any lines say `=> not found` in the output?

**Reply by NulliferBones** [reply]
```
export NVDIR=`pwd`/venv/lib/python3.10/site-packages/nvidia
export LD_LIBRARY_PATH=$NVDIR/cusparse/lib:$NVDIR/cublas/lib:$NVDIR/cuda_runtime/lib
ldd venv/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda118_nocublaslt.so
ldd: warning: you do not have execution permission for `venv/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda118_nocublaslt.so'
        linux-vdso.so.1 (0x0000713e6fc88000)
        libcudart.so.11.0 => /home/nullifer/Documents/AI/KohyaSS/kohya_ss/venv/lib/python3.10/site-packages/nvidia/cuda_runtime/lib/libcudart.so.11.0 (0x0000713e6de00000)
        libcublas.so.11 => /home/nullifer/Documents/AI/KohyaSS/kohya_ss/venv/lib/python3.10/site-packages/nvidia/cublas/lib/libcublas.so.11 (0x0000713e67e00000)
        libcusparse.so.11 => /home/nullifer/Documents/AI/KohyaSS/kohya_ss/venv/lib/python3.10/site-packages/nvidia/cusparse/lib/libcusparse.so.11 (0x0000713e56e00000)
        libstdc++.so.6 => /usr/lib/libstdc++.so.6 (0x0000713e56a00000)
        libm.so.6 => /usr/lib/libm.so.6 (0x0000713e6fb6d000)
        libgcc_s.so.1 => /usr/lib/libgcc_s.so.1 (0x0000713e6fb3f000)
        libc.so.6 => /usr/lib/libc.so.6 (0x0000713e6e20f000)
        /usr/lib64/ld-linux-x86-64.so.2 (0x0000713e6fc8a000)
        libdl.so.2 => /usr/lib/libdl.so.2 (0x0000713e6fb3a000)
        libpthread.so.0 => /usr/lib/libpthread.so.0 (0x0000713e6fb35000)
        librt.so.1 => /usr/lib/librt.so.1 (0x0000713e6fb30000)
        libcublasLt.so.11 => /home/nullifer/Documents/AI/KohyaSS/kohya_ss/venv/lib/python3.10/site-packages/nvidia/cublas/lib/libcublasLt.so.11 (0x0000713e32200000)
```

**Reply by b-fission** [reply]
Looks perfectly fine.....
Can you run `./gui.sh` from that terminal? It should work.

**Reply by NulliferBones** [reply]
ok so everything was normal when i ran it from that same terminal. no errors, adamw8bit worked
But when i closed it and then ran GUI again by it self, it's the same situation again

**Reply by b-fission** [reply]
I think that can be solved by having a custom launch script. What if you paste this into a new file (in the same directory), save it as `run.sh` 

```bash
#!/usr/bin/bash
SCRIPT_DIR=$(cd -- "$(dirname -- "$0")" && pwd)
export NVDIR=$SCRIPT_DIR/venv/lib/python3.10/site-packages/nvidia
export LD_LIBRARY_PATH=$NVDIR/cusparse/lib:$NVDIR/cublas/lib:$NVDIR/cuda_runtime/lib
./gui.sh
```

Give it executable permission with `chmod +x run.sh`
Then you use that script to start the gui.

**Reply by NulliferBones** [reply]
Thank you very much, this does indeed work. I appreciate you help with this issue.
It would be nice to understand what is happening and be able to fix the issue. This behavior seems extremely odd.

**Reply by b-fission** [reply]
Ideally, installing CUDA Toolkit 11.8 and pointing LD_LIBRARY_PATH to it would've been the normal setup process.

What we did was avoid the toolkit, and used pip to install the individual nvidia libs used by bitsandbytes.
Relative paths in LD_LIBRARY_PATH caused issues, so absolute paths made sure it all worked.

**Reply by NulliferBones** [reply]
Yeah it's nice having arch for sort of being on the bleeding edge, but then at the same time you run into issues like this where it's almost impossible to install 11.8 now (more than anything GCC11).
Either way, thanks again for your help.

**Reply by NulliferBones** [reply]
not related to this, but recently for automatic1111 i started receiving this error. do not understand what caused it, no one is responding there maybe i can get some help here

```
Check TCMalloc: libtcmalloc_minimal.so.4
/home/nullifer/Documents/AI/WEBUI/webuirc/webui.sh: line 258: bc: command not found
/home/nullifer/Documents/AI/WEBUI/webuirc/webui.sh: line 258: [: -eq: unary operator expected
libtcmalloc_minimal.so.4 is linked with libc.so,execute LD_PRELOAD=/usr/lib/libtcmalloc_minimal.so.4

```

i tried that execute message but didn't seem to help

**Reply by b-fission** [reply]
The only error I see there is the [bc tool](https://archlinux.org/packages/extra/x86_64/bc/) isn't installed.
The parts about `libtcmalloc_minimal.so.4` is normal log output, nothing wrong there.

**Reply by NulliferBones** [reply]
alright i installed BC and that error is gone.
only message remaing apart from the future warning resume download
is 

```
Check TCMalloc: libtcmalloc_minimal.so.4
libtcmalloc_minimal.so.4 is linked with libc.so,execute LD_PRELOAD=/usr/lib/libtcmalloc_minimal.so.4
```

**Reply by b-fission** [reply]
Yeah, it looks fine.

**Reply by NulliferBones** [reply]
thanks again
