### DISCUSSION TITLE
accelerator device is cpu.

### DISCUSSION THREAD

**Discussion by pinkpray** [bmaltais/kohya_ss#3090] [Q&A]
I have 2 pc, and I’ve installed them with the same steps. But when I start a same Lora training run,  they always give different results. One gives one line that says accelerator device is cuda.and it ran smoothly.But the other says accelerator device is cpu. 
![7d361aee29afdcf1de4c949d60b2728c](https://github.com/user-attachments/assets/de6b7365-cdd2-43c2-b368-d6d36f90515e)
![0a364aeac72506497f6a584654930943](https://github.com/user-attachments/assets/4d0e4a39-15fe-4f6b-95cc-86002d233832)
![fc0f6e0c962d5e14161590ff178f1f7e](https://github.com/user-attachments/assets/5a39b5b5-338c-407f-9787-137a3e6cd410)
![38bdb6d16a6120249b6d2ca02d175db8](https://github.com/user-attachments/assets/adaaac4c-99fd-4f95-8f09-4ce2899785de)

**Comment by pinkpray** [comment]
I input the cmd to check the cuda, its answer is true.
![c069fd23c983408e84997d4f03405b48](https://github.com/user-attachments/assets/d90345a4-9b3c-41a7-9dd1-8dfa70fe65aa)

So what should I do to get the GPU accelerate device ？

**Comment by r33yl** [comment]
This is not exactly what you asked, but this is what helped me fix the same issue.
In my case, the problem was that **Accelerate was configured to use CPU on one machine**, even though CUDA was installed.

Go to this folder and run Accelerate config **from kohya’s own venv**:

```
kohya_ss\.venv\Scripts\accelerate.exe config
```

During setup, make sure you choose:

* `use_cpu: false`
* `gpu_ids: all`
* `mixed_precision: fp16`

The config will be saved here:

```
C:\Users\User\.cache\huggingface\accelerate\default_config.yaml
```

It should look like this:

```
compute_environment: LOCAL_MACHINE
debug: false
distributed_type: 'NO'
downcast_bf16: 'no'
enable_cpu_affinity: true
gpu_ids: all
machine_rank: 0
main_training_function: main
mixed_precision: fp16
num_machines: 1
num_processes: 1
rdzv_backend: static
same_network: true
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: false
```

After that, restart kohya and the log should say:

```
accelerator device: cuda
```

This fixed the issue for me where one PC used CUDA and the other always fell back to CPU.
