### ISSUE TITLE
RuntimeError: CUDA error: CUBLAS_STATUS_INTERNAL_ERROR 

### ISSUE THREAD

**Issue by josh3255** [bmaltais/kohya_ss#1001]
The following error will occur shortly after starting the training of dreambooth lora.

```
RuntimeError: CUDA error: CUBLAS_STATUS_INTERNAL_ERROR when calling `cublasGemmEx( handle, opa, opb, m, n, k, &falpha, a, CUDA_R_16F, lda, b, CUDA_R_16F, ldb, &fbeta, c, CUDA_R_16F, ldc, CUDA_R_32F, CUBLAS_GEMM_DFALT_TENSOR_OP)
```

The learning environment is as follows.
```
OS : Windows 11
Python : 3.10
GPU : RTX 3060Ti

Install Command :
git clone https://github.com/bmaltais/kohya_ss.git
cd kohya_ss
python -m venv --system-site-packages venv
.\venv\Scripts\activate
pip install torch==1.12.1+cu116 torchvision==0.13.1+cu116 --extra-index-url https://download.pytorch.org/whl/cu116
pip install --upgrade -r requirements.txt
pip install -U -I --no-deps https://github.com/C43H66N12O12S2/stable-diffusion-webui/releases/download/f/xformers-0.0.14.dev0-cp310-cp310-win_amd64.whl
cp .\bitsandbytes_windows\*.dll .\venv\Lib\site-packages\bitsandbytes\
cp .\bitsandbytes_windows\[cextension.py](http://cextension.py/) .\venv\Lib\site-packages\bitsandbytes\[cextension.py](http://cextension.py/)
cp .\bitsandbytes_windows\[main.py](http://main.py/) .\venv\Lib\site-packages\bitsandbytes\cuda_setup\[main.py](http://main.py/)
accelerate config
```

Please tell me how to solve this problem.

**Comment by bmaltais** [comment]
Try cloning the latest release and run setup.bat to set things up instead of doing the manual steps

**Comment by josh3255** [comment]
@bmaltais thank you for reply.

As mentioned in Installation (Windows), using setup.bat makes no difference.

do I have to match the locally installed cuda version to 11.6?

environment
```
GPU : RTX 3060Ti
local GPU Driver : 536.23
local cuda : None
```

this is the full output and settings
```
─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ C:\Users\josh3255\Desktop\projects\kohya_ss\train_network.py:864 in <module>                       │
│                                                                                                  │
│   861 │   args = parser.parse_args()                                                             │
│   862 │   args = train_util.read_config_from_file(args, parser)                                  │
│   863 │                                                                                          │
│ ❱ 864 │   train(args)                                                                            │
│   865                                                                                            │
│                                                                                                  │
│ C:\Users\josh3255\Desktop\projects\kohya_ss\train_network.py:653 in train                          │
│                                                                                                  │
│   650 │   │   │   │                                                                              │
│   651 │   │   │   │   # Predict the noise residual                                               │
│   652 │   │   │   │   with accelerator.autocast():                                               │
│ ❱ 653 │   │   │   │   │   noise_pred = unet(noisy_latents, timesteps, encoder_hidden_states).s   │
│   654 │   │   │   │                                                                              │
│   655 │   │   │   │   if args.v_parameterization:                                                │
│   656 │   │   │   │   │   # v-parameterization training                                          │
│                                                                                                  │
│ C:\Users\josh3255\Desktop\projects\kohya_ss\venv\lib\site-packages\torch\nn\modules\module.py:1130 │
│ in _call_impl                                                                                    │
│                                                                                                  │
│   1127 │   │   # this function, and just call forward.                                           │
│   1128 │   │   if not (self._backward_hooks or self._forward_hooks or self._forward_pre_hooks o  │
│   1129 │   │   │   │   or _global_forward_hooks or _global_forward_pre_hooks):                   │
│ ❱ 1130 │   │   │   return forward_call(*input, **kwargs)                                         │
│   1131 │   │   # Do not call functions when jit is used                                          │
│   1132 │   │   full_backward_hooks, non_full_backward_hooks = [], []                             │
│   1133 │   │   if self._backward_hooks or _global_backward_hooks:                                │
│                                                                                                  │
│ C:\Users\josh3255\Desktop\projects\kohya_ss\venv\lib\site-packages\accelerate\utils\operations.py: │
│ 490 in __call__                                                                                  │
│                                                                                                  │
│   487 │   │   update_wrapper(self, model_forward)                                                │
│   488 │                                                                                          │
│   489 │   def __call__(self, *args, **kwargs):                                                   │
│ ❱ 490 │   │   return convert_to_fp32(self.model_forward(*args, **kwargs))                        │
│   491 │                                                                                          │
│   492 │   def __getstate__(self):                                                                │
│   493 │   │   raise pickle.PicklingError(                                                        │
│                                                                                                  │
│ C:\Users\josh3255\Desktop\projects\kohya_ss\venv\lib\site-packages\torch\amp\autocast_mode.py:12   │
│ in decorate_autocast                                                                             │
│                                                                                                  │
│     9 │   @functools.wraps(func)                                                                 │
│    10 │   def decorate_autocast(*args, **kwargs):                                                │
│    11 │   │   with autocast_instance:                                                            │
│ ❱  12 │   │   │   return func(*args, **kwargs)                                                   │
│    13 │   decorate_autocast.__script_unsupported = '@autocast() decorator is not supported in    │
│    14 │   return decorate_autocast                                                               │
│    15                                                                                            │
│                                                                                                  │
│ C:\Users\josh3255\Desktop\projects\kohya_ss\venv\lib\site-packages\diffusers\models\unet_2d_condit │
│ on.py:381 in forward                                                                             │
│                                                                                                  │
│   378 │   │   down_block_res_samples = (sample,)                                                 │
│   379 │   │   for downsample_block in self.down_blocks:                                          │
│   380 │   │   │   if hasattr(downsample_block, "has_cross_attention") and downsample_block.has   │
│ ❱ 381 │   │   │   │   sample, res_samples = downsample_block(                                    │
│   382 │   │   │   │   │   hidden_states=sample,                                                  │
│   383 │   │   │   │   │   temb=emb,                                                              │
│   384 │   │   │   │   │   encoder_hidden_states=encoder_hidden_states,                           │
│                                                                                                  │
│ C:\Users\josh3255\Desktop\projects\kohya_ss\venv\lib\site-packages\torch\nn\modules\module.py:1130 │
│ in _call_impl                                                                                    │
│                                                                                                  │
│   1127 │   │   # this function, and just call forward.                                           │
│   1128 │   │   if not (self._backward_hooks or self._forward_hooks or self._forward_pre_hooks o  │
│   1129 │   │   │   │   or _global_forward_hooks or _global_forward_pre_hooks):                   │
│ ❱ 1130 │   │   │   return forward_call(*input, **kwargs)                                         │
│   1131 │   │   # Do not call functions when jit is used                                          │
│   1132 │   │   full_backward_hooks, non_full_backward_hooks = [], []                             │
│   1133 │   │   if self._backward_hooks or _global_backward_hooks:                                │
│                                                                                                  │
│ C:\Users\josh3255\Desktop\projects\kohya_ss\venv\lib\site-packages\diffusers\models\unet_2d_blocks │
│ .py:612 in forward                                                                               │
│                                                                                                  │
│    609 │   │   │   │   )[0]                                                                      │
│    610 │   │   │   else:                                                                         │
│    611 │   │   │   │   hidden_states = resnet(hidden_states, temb)                               │
│ ❱  612 │   │   │   │   hidden_states = attn(hidden_states, encoder_hidden_states=encoder_hidden  │
│    613 │   │   │                                                                                 │
│    614 │   │   │   output_states += (hidden_states,)                                             │
│    615                                                                                           │
│                                                                                                  │
│ C:\Users\josh3255\Desktop\projects\kohya_ss\venv\lib\site-packages\torch\nn\modules\module.py:1130 │
│ in _call_impl                                                                                    │
│                                                                                                  │
│   1127 │   │   # this function, and just call forward.                                           │
│   1128 │   │   if not (self._backward_hooks or self._forward_hooks or self._forward_pre_hooks o  │
│   1129 │   │   │   │   or _global_forward_hooks or _global_forward_pre_hooks):                   │
│ ❱ 1130 │   │   │   return forward_call(*input, **kwargs)                                         │
│   1131 │   │   # Do not call functions when jit is used                                          │
│   1132 │   │   full_backward_hooks, non_full_backward_hooks = [], []                             │
│   1133 │   │   if self._backward_hooks or _global_backward_hooks:                                │
│                                                                                                  │
│ C:\Users\josh3255\Desktop\projects\kohya_ss\venv\lib\site-packages\diffusers\models\attention.py:2 │
│ 16 in forward                                                                                    │
│                                                                                                  │
│   213 │   │                                                                                      │
│   214 │   │   # 2. Blocks                                                                        │
│   215 │   │   for block in self.transformer_blocks:                                              │
│ ❱ 216 │   │   │   hidden_states = block(hidden_states, context=encoder_hidden_states, timestep   │
│   217 │   │                                                                                      │
│   218 │   │   # 3. Output                                                                        │
│   219 │   │   if self.is_input_continuous:                                                       │
│                                                                                                  │
│ C:\Users\josh3255\Desktop\projects\kohya_ss\venv\lib\site-packages\torch\nn\modules\module.py:1130 │
│ in _call_impl                                                                                    │
│                                                                                                  │
│   1127 │   │   # this function, and just call forward.                                           │
│   1128 │   │   if not (self._backward_hooks or self._forward_hooks or self._forward_pre_hooks o  │
│   1129 │   │   │   │   or _global_forward_hooks or _global_forward_pre_hooks):                   │
│ ❱ 1130 │   │   │   return forward_call(*input, **kwargs)                                         │
│   1131 │   │   # Do not call functions when jit is used                                          │
│   1132 │   │   full_backward_hooks, non_full_backward_hooks = [], []                             │
│   1133 │   │   if self._backward_hooks or _global_backward_hooks:                                │
│                                                                                                  │
│ C:\Users\josh3255\Desktop\projects\kohya_ss\venv\lib\site-packages\diffusers\models\attention.py:4 │
│ 91 in forward                                                                                    │
│                                                                                                  │
│   488 │   │   │   norm_hidden_states = (                                                         │
│   489 │   │   │   │   self.norm2(hidden_states, timestep) if self.use_ada_layer_norm else self   │
│   490 │   │   │   )                                                                              │
│ ❱ 491 │   │   │   hidden_states = self.attn2(norm_hidden_states, context=context) + hidden_sta   │
│   492 │   │                                                                                      │
│   493 │   │   # 3. Feed-forward                                                                  │
│   494 │   │   hidden_states = self.ff(self.norm3(hidden_states)) + hidden_states                 │
│                                                                                                  │
│ C:\Users\josh3255\Desktop\projects\kohya_ss\venv\lib\site-packages\torch\nn\modules\module.py:1130 │
│ in _call_impl                                                                                    │
│                                                                                                  │
│   1127 │   │   # this function, and just call forward.                                           │
│   1128 │   │   if not (self._backward_hooks or self._forward_hooks or self._forward_pre_hooks o  │
│   1129 │   │   │   │   or _global_forward_hooks or _global_forward_pre_hooks):                   │
│ ❱ 1130 │   │   │   return forward_call(*input, **kwargs)                                         │
│   1131 │   │   # Do not call functions when jit is used                                          │
│   1132 │   │   full_backward_hooks, non_full_backward_hooks = [], []                             │
│   1133 │   │   if self._backward_hooks or _global_backward_hooks:                                │
│                                                                                                  │
│ C:\Users\josh3255\Desktop\projects\kohya_ss\library\train_util.py:1860 in forward_xformers         │
│                                                                                                  │
│   1857 │   │   │   context_k = context                                                           │
│   1858 │   │   │   context_v = context                                                           │
│   1859 │   │                                                                                     │
│ ❱ 1860 │   │   k_in = self.to_k(context_k)                                                       │
│   1861 │   │   v_in = self.to_v(context_v)                                                       │
│   1862 │   │                                                                                     │
│   1863 │   │   q, k, v = map(lambda t: rearrange(t, "b n (h d) -> b n h d", h=h), (q_in, k_in,   │
│                                                                                                  │
│ C:\Users\josh3255\Desktop\projects\kohya_ss\venv\lib\site-packages\torch\nn\modules\module.py:1130 │
│ in _call_impl                                                                                    │
│                                                                                                  │
│   1127 │   │   # this function, and just call forward.                                           │
│   1128 │   │   if not (self._backward_hooks or self._forward_hooks or self._forward_pre_hooks o  │
│   1129 │   │   │   │   or _global_forward_hooks or _global_forward_pre_hooks):                   │
│ ❱ 1130 │   │   │   return forward_call(*input, **kwargs)                                         │
│   1131 │   │   # Do not call functions when jit is used                                          │
│   1132 │   │   full_backward_hooks, non_full_backward_hooks = [], []                             │
│   1133 │   │   if self._backward_hooks or _global_backward_hooks:                                │
│                                                                                                  │
│ C:\Users\josh3255\Desktop\projects\kohya_ss\networks\lora.py:85 in forward                         │
│                                                                                                  │
│     82 │   │   del self.org_module                                                               │
│     83 │                                                                                         │
│     84 │   def forward(self, x):                                                                 │
│ ❱   85 │   │   org_forwarded = self.org_forward(x)                                               │
│     86 │   │                                                                                     │
│     87 │   │   # module dropout                                                                  │
│     88 │   │   if self.module_dropout is not None and self.training:                             │
│                                                                                                  │
│ C:\Users\josh3255\Desktop\projects\kohya_ss\venv\lib\site-packages\torch\nn\modules\linear.py:114  │
│ in forward                                                                                       │
│                                                                                                  │
│   111 │   │   │   init.uniform_(self.bias, -bound, bound)                                        │
│   112 │                                                                                          │
│   113 │   def forward(self, input: Tensor) -> Tensor:                                            │
│ ❱ 114 │   │   return F.linear(input, self.weight, self.bias)                                     │
│   115 │                                                                                          │
│   116 │   def extra_repr(self) -> str:                                                           │
│   117 │   │   return 'in_features={}, out_features={}, bias={}'.format(                          │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
RuntimeError: CUDA error: CUBLAS_STATUS_INTERNAL_ERROR when calling `cublasGemmEx( handle, opa, opb, m, n, k, &falpha,
a, CUDA_R_16F, lda, b, CUDA_R_16F, ldb, &fbeta, c, CUDA_R_16F, ldc, CUDA_R_32F, CUBLAS_GEMM_DFALT_TENSOR_OP)`
steps:   9%|█████▍                                                      | 506/5600 [02:16<22:51,  3.71it/s, loss=0.135]
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ C:\Users\josh3255\AppData\Local\Programs\Python\Python310\lib\runpy.py:196 in _run_module_as_main  │
│                                                                                                  │
│   193 │   main_globals = sys.modules["__main__"].__dict__                                        │
│   194 │   if alter_argv:                                                                         │
│   195 │   │   sys.argv[0] = mod_spec.origin                                                      │
│ ❱ 196 │   return _run_code(code, main_globals, None,                                             │
│   197 │   │   │   │   │    "__main__", mod_spec)                                                 │
│   198                                                                                            │
│   199 def run_module(mod_name, init_globals=None,                                                │
│                                                                                                  │
│ C:\Users\josh3255\AppData\Local\Programs\Python\Python310\lib\runpy.py:86 in _run_code             │
│                                                                                                  │
│    83 │   │   │   │   │      __loader__ = loader,                                                │
│    84 │   │   │   │   │      __package__ = pkg_name,                                             │
│    85 │   │   │   │   │      __spec__ = mod_spec)                                                │
│ ❱  86 │   exec(code, run_globals)                                                                │
│    87 │   return run_globals                                                                     │
│    88                                                                                            │
│    89 def _run_module_code(code, init_globals=None,                                              │
│                                                                                                  │
│ in <module>:7                                                                                    │
│                                                                                                  │
│   4 from accelerate.commands.accelerate_cli import main                                          │
│   5 if __name__ == '__main__':                                                                   │
│   6 │   sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])                         │
│ ❱ 7 │   sys.exit(main())                                                                         │
│   8                                                                                              │
│                                                                                                  │
│ C:\Users\josh3255\Desktop\projects\kohya_ss\venv\lib\site-packages\accelerate\commands\accelerate_ │
│ cli.py:45 in main                                                                                │
│                                                                                                  │
│   42 │   │   exit(1)                                                                             │
│   43 │                                                                                           │
│   44 │   # Run                                                                                   │
│ ❱ 45 │   args.func(args)                                                                         │
│   46                                                                                             │
│   47                                                                                             │
│   48 if __name__ == "__main__":                                                                  │
│                                                                                                  │
│ C:\Users\josh3255\Desktop\projects\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py:1 │
│ 104 in launch_command                                                                            │
│                                                                                                  │
│   1101 │   elif defaults is not None and defaults.compute_environment == ComputeEnvironment.AMA  │
│   1102 │   │   sagemaker_launcher(defaults, args)                                                │
│   1103 │   else:                                                                                 │
│ ❱ 1104 │   │   simple_launcher(args)                                                             │
│   1105                                                                                           │
│   1106                                                                                           │
│   1107 def main():                                                                               │
│                                                                                                  │
│ C:\Users\josh3255\Desktop\projects\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py:5 │
│ 67 in simple_launcher                                                                            │
│                                                                                                  │
│    564 │   process = subprocess.Popen(cmd, env=current_env)                                      │
│    565 │   process.wait()                                                                        │
│    566 │   if process.returncode != 0:                                                           │
│ ❱  567 │   │   raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)       │
│    568                                                                                           │
│    569                                                                                           │
│    570 def multi_gpu_launcher(args):                                                             │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
CalledProcessError: Command '['C:\\Users\\josh3255\\Desktop\\projects\\kohya_ss\\venv\\Scripts\\python.exe',
'train_network.py', '--enable_bucket',
'--pretrained_model_name_or_path=C:/Users/josh3255/Downloads/v1-5-pruned-emaonly.safetensors',
'--train_data_dir=C:/Users/josh3255/Desktop/images/train', '--reg_data_dir=C:/Users/josh3255/Desktop/images/regularisation',
'--resolution=512,512', '--output_dir=C:/Users/josh3255/Desktop/weights', '--network_alpha=1',
'--save_model_as=safetensors', '--network_module=networks.lora', '--text_encoder_lr=5e-05', '--unet_lr=0.0001',
'--network_dim=1', '--output_name=qdm', '--lr_scheduler_num_cycles=2', '--learning_rate=0.0001',
'--lr_scheduler=cosine', '--lr_warmup_steps=560', '--train_batch_size=1', '--max_train_steps=5600',
'--save_every_n_epochs=1', '--mixed_precision=fp16', '--save_precision=fp16', '--cache_latents',
'--optimizer_type=AdamW8bit', '--max_data_loader_n_workers=0', '--bucket_reso_steps=64', '--full_fp16', '--xformers',
'--bucket_no_upscale']' returned non-zero exit status 1.
```

**Comment by bmaltais** [comment]
It is ok not to have captions. The folder name part after the _ will be used in that case.

Regarding the other error I really have no idea. You could try to install the latest cudann drivers for your card and see if it help.

**Comment by wogam** [comment]
Did you manage to fix the error? I'm getting the same error. Cuda 11.8, but also tried with 12.1. RTX 3090, torch 2.0.1+cu118.

**Comment by wogam** [comment]
Here's what worked for me:

1. Download CUDA 11.8 from here: https://developer.nvidia.com/cuda-11-8-0-download-archive
2. Delete the Kohya_ss folder.
3. Uninstall NVIDIA drivers (536.x especially causes issues)
4. Install the NVDIA graphics driver from the CUDA installer (should be 526.x) (you only need to reinstall CUDA if you don't have 11.8 installed, otherwise just the driver is fine)
5. Download the latest cuDNN from here: https://developer.nvidia.com/cudnn (make sure it's for 11.8 not 12.1)
6. Unpack the archive and rename the bin folder 'cudnn_windows'
7. Git checkout this repo and the place the 'cudnn_windows' folder inside it
8. Install Kohya through the automatic set up as listed on the main page of this repo
9. Install cuDNN through the same set-up script
