### ISSUE TITLE
Docker:Error response from daemon: could not select device driver "nvidia" with capabilities

### ISSUE THREAD

**Issue by weiwei83** [bmaltais/kohya_ss#1108]
<img width="978" alt="image" src="https://github.com/bmaltais/kohya_ss/assets/10830200/3b06d8e7-cff6-4d7f-9ebc-56301ba02d24">
Install the docker container according to the tutorial, and report an error when executing the command, as shown in the figure, the figure below is my GPU information
<img width="710" alt="image" src="https://github.com/bmaltais/kohya_ss/assets/10830200/b7966784-735b-48c2-9e3e-e16a5daa457e">

(lora) PS D:\kohya_ss> docker compose build
time="2023-07-02T01:47:50+08:00" level=warning msg="The \"DISPLAY\" variable is not set. Defaulting to a blank string."
[+] Building 4.2s (20/20) FINISHED
 => [kohya-ss-gui internal] load build definition from Dockerfile                                                                              0.0s
 => => transferring dockerfile: 2.17kB                                                                                                         0.0s
 => [kohya-ss-gui internal] load .dockerignore                                                                                                 0.0s
 => => transferring context: 153B                                                                                                              0.0s
 => [kohya-ss-gui internal] load metadata for nvcr.io/nvidia/pytorch:23.04-py3                                                                 2.3s
 => [kohya-ss-gui  1/15] FROM nvcr.io/nvidia/pytorch:23.04-py3@sha256:5dd0caf52947719ba4fc170e779cfb20a5ecac7c91ca530f2884ed35fb97005f         0.0s
 => [kohya-ss-gui internal] load build context                                                                                                 0.1s
 => => transferring context: 8.85MB                                                                                                            0.1s
 => CACHED [kohya-ss-gui  2/15] RUN apt update && apt-get install -y software-properties-common                                                0.0s
 => CACHED [kohya-ss-gui  3/15] RUN add-apt-repository ppa:deadsnakes/ppa &&     apt update &&     apt-get install -y git curl libgl1 libglib  0.0s
 => CACHED [kohya-ss-gui  4/15] RUN update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.10 3 &&     update-alternatives -  0.0s
 => CACHED [kohya-ss-gui  5/15] RUN curl -sS https://bootstrap.pypa.io/get-pip.py | python3                                                    0.0s
 => CACHED [kohya-ss-gui  6/15] WORKDIR /app                                                                                                   0.0s
 => CACHED [kohya-ss-gui  7/15] RUN python3 -m pip install wheel                                                                               0.0s
 => CACHED [kohya-ss-gui  8/15] COPY ./requirements.txt ./requirements_linux_docker.txt ./                                                     0.0s
 => CACHED [kohya-ss-gui  9/15] COPY ./setup/docker_setup.py ./setup.py                                                                        0.0s
 => CACHED [kohya-ss-gui 10/15] RUN python3 -m pip install -r ./requirements_linux_docker.txt                                                  0.0s
 => CACHED [kohya-ss-gui 11/15] RUN python3 -m pip install -r ./requirements.txt                                                               0.0s
 => CACHED [kohya-ss-gui 12/15] RUN python3 -m pip uninstall -y pillow &&     CC="cc -mavx2" python3 -m pip install -U --force-reinstall pill  0.0s
 => CACHED [kohya-ss-gui 13/15] RUN ln -s /usr/lib/x86_64-linux-gnu/libnvinfer.so /usr/lib/x86_64-linux-gnu/libnvinfer.so.7 &&     ln -s /usr  0.0s
 => CACHED [kohya-ss-gui 14/15] RUN useradd -m -s /bin/bash appuser &&     chown -R appuser: /app                                              0.0s
 => [kohya-ss-gui 15/15] COPY --chown=appuser . .                                                                                              0.7s
 => [kohya-ss-gui] exporting to image                                                                                                          0.9s
 => => exporting layers                                                                                                                        0.9s
 => => writing image sha256:1860d7a12dd4efea488d2e1e8269ccb361f5910870f4eac3207af24ad0ca2e33                                                   0.0s
 => => naming to docker.io/library/kohya-ss-gui:latest                                                                                         0.0s
(lora) PS D:\kohya_ss> docker compose run --service-ports kohya-ss-gui
time="2023-07-02T01:49:29+08:00" level=warning msg="The \"DISPLAY\" variable is not set. Defaulting to a blank string."
[+] Creating 1/1
 ✔ Network kohya_ss_default  Created                                                                                                           0.6s
Error response from daemon: could not select device driver "nvidia" with capabilities: [[]]

**Comment by potatoker** [comment]
same error here, I used to install kohya-ss in the same machine and environment successfully, can it be some changes  in the repo recently caused this error?

**Comment by potatoker** [comment]
I managed to run docker successfully again by checkout to eec7d05. although there are some other problems on this commit

**Comment by weiwei83** [comment]
> 
I added in docker configuration file（docker-compose.yaml）--capabilities: [gpu]
it worked！
Can go to the web page fine, able to configure, able to click to start training, but after starting training I get more errors so I give up
```
deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['all']
              capabilities: [gpu]
```

**Comment by ac2522** [comment]
> > 
> 
> I added in docker configuration file（docker-compose.yaml）--capabilities: [gpu] it worked！ Can go to the web page fine, able to configure, able to click to start training, but after starting training I get more errors so I give up
> 
> ```
> deploy:
>       resources:
>         reservations:
>           devices:
>             - driver: nvidia
>               device_ids: ['all']
>               capabilities: [gpu]
> ```

Didn't work for me.
Initial error:
`ERRO[0000] error waiting for container:                 
Error response from daemon: could not select device driver "nvidia" with capabilities: [gpu]`
Error after adding "capabilities: [gpu]":
`ERRO[0000] error waiting for container:                 
Error response from daemon: could not select device driver "nvidia" with capabilities: [[gpu]]`

**Comment by esa1975** [comment]
> > > 
> > 
> > 
> > I added in docker configuration file（docker-compose.yaml）--capabilities: [gpu] it worked！ Can go to the web page fine, able to configure, able to click to start training, but after starting training I get more errors so I give up
> > ```
> > deploy:
> >       resources:
> >         reservations:
> >           devices:
> >             - driver: nvidia
> >               device_ids: ['all']
> >               capabilities: [gpu]
> > ```
> 
> Didn't work for me. Initial error: `ERRO[0000] error waiting for container: Error response from daemon: could not select device driver "nvidia" with capabilities: [gpu]`
> 
> Error after adding "capabilities: [gpu]": `ERRO[0000] error waiting for container: Error response from daemon: could not select device driver "nvidia" with capabilities: [[gpu]]`

This may not be relevant to you but, simply adding the capabilities line to the yaml file did work on Ubuntu but not Arch. For Arch, I needed to follow the wiki and install Nvidia Container Toolkit. Hopefully this helps someone.

https://wiki.archlinux.org/title/Docker#Run_GPU_accelerated_Docker_containers_with_NVIDIA_GPUs

**Comment by pythonlearner1025** [comment]
@kabrio thank you, worked for me. for future people, make sure you follow steps on "Configuring Docker" in the nvidia docs as well
