### ISSUE TITLE
CUDA Setup Failed (Ubuntu 22.04) Bitsandbytes CLI vs train_network.py execution

### ISSUE THREAD

**Issue by markojak** [bmaltais/kohya_ss#1213]
I'm really hoping someone can help me here because for the life of me I can't get Khoya training working on Ubuntu 22.04

The error i'm getting is **Exception: CUDA SETUP: Setup Failed!** - See full exception Below
This appears to be thrown from the bitsandbytes package which cannot detect CUDA

However when I run `python -m bitsandbytes` it executes with no problem ...."SUCCESS!"
(See CLI Output below)

Can anyone please help?

The following has been done 
- Installed the standard setup with Khoya and using the standard python-venv
- CUDA Toolkit and v12 installed, TensoRT, CuDNN, Driver and Kernel updates (nvidia-smi and nvcc working fine)
- Recompiled Bitsandbytes from source 

Exception thrown (from bitsandbytes package)
```
CUDA SETUP: CUDA runtime path found: /usr/local/cuda/lib64/libcudart.so
CUDA exception! Error code: no CUDA-capable device is detected
CUDA exception! Error code: initialization error
CUDA SETUP: Highest compute capability among GPUs detected: None
CUDA exception! Error code: no CUDA-capable device is detected
CUDA SETUP: CUDA version lower than 11 are currenlty not supported for LLM.int8(). You will be only to use 8-bit optimizers and quantization routines!!
CUDA SETUP: Detected CUDA version 00
CUDA SETUP: TODO: compile library for specific version: libbitsandbytes_cuda00_nocublaslt.so
CUDA SETUP: Defaulting to libbitsandbytes.so...
CUDA SETUP: CUDA detection failed. Either CUDA driver not installed, CUDA not installed, or you have multiple conflicting CUDA libraries!
CUDA SETUP: If you compiled from source, try again with `make CUDA_VERSION=DETECTED_CUDA_VERSION` for example, `make CUDA_VERSION=113`.
Traceback (most recent call last):
```

**CLI Output ` python -m bitsandbytes` in CLI** 
```
venv) markoj@ml-titan-c:~/workspace/khoya$ python -m bitsandbytes

===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please submit your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
For effortless bug reporting copy-paste your error into this form: https://docs.google.com/forms/d/e/1FAIpQLScPB8emS3Thkp66nvqwmjTEgxp8Y9ufuWTzFyr9kJ5AoI47dQ/viewform?usp=sf_link
================================================================================
/home/markoj/workspace/khoya/venv/lib/python3.10/site-packages/bitsandbytes/cuda_setup/paths.py:93: UserWarning: /home/markoj/miniconda3 did not contain libcudart.so as expected! Searching further paths...
  warn(
/home/markoj/workspace/khoya/venv/lib/python3.10/site-packages/bitsandbytes/cuda_setup/paths.py:27: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {PosixPath('/usr/local/cuda/extras/CUPTI/lib64')}
  warn(
CUDA SETUP: CUDA runtime path found: /usr/local/cuda/lib64/libcudart.so
CUDA SETUP: Highest compute capability among GPUs detected: 8.0
CUDA SETUP: Detected CUDA version 118
CUDA SETUP: Loading binary /home/markoj/workspace/khoya/venv/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda118.so...
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
++++++++++++++++++++ DEBUG INFORMATION +++++++++++++++++++++
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

++++++++++ POTENTIALLY LIBRARY-PATH-LIKE ENV VARS ++++++++++
'NVM_INC': '/home/markoj/.nvm/versions/node/v18.16.0/include/node'
'CONDA_EXE': '/home/markoj/miniconda3/bin/conda'
'_P9K_TTY': '/dev/pts/2'
'CONDA_PREFIX': '/home/markoj/miniconda3'
'VIRTUAL_ENV': '/home/markoj/workspace/khoya/venv'
'NVM_DIR': '/home/markoj/.nvm'
'ZSH': '/home/markoj/.oh-my-zsh'
'LIBRARY_PATH': '/usr/local/cuda/lib64:'
'_P9K_SSH_TTY': '/dev/pts/2'
'CONDA_PYTHON_EXE': '/home/markoj/miniconda3/bin/python'
'LD_LIBRARY_PATH': '/usr/local/cuda/lib64:/usr/local/cuda/extras/CUPTI/lib64:'
'CUDA_HOME': '/usr/local/cuda'
'NVM_BIN': '/home/markoj/.nvm/versions/node/v18.16.0/bin'
'CPATH': '/usr/local/cuda/include:'
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

WARNING: Please be sure to sanitize sensible info from any such env vars!

++++++++++++++++++++++++++ OTHER +++++++++++++++++++++++++++
COMPILED_WITH_CUDA = True
COMPUTE_CAPABILITIES_PER_GPU = ['8.0']
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
++++++++++++++++++++++ DEBUG INFO END ++++++++++++++++++++++
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

Running a quick check that:
    + library is importable
    + CUDA function is callable

SUCCESS!
Installation was successful!
```

**pip show bitsandbytes**
```
Name: bitsandbytes
Version: 0.35.0
Summary: 8-bit optimizers and matrix multiplication routines.
...
```

**Comment by markojak** [comment]
OK turns out the requirements_linux.txt file is incorrect for SDXL Training

```
torch==2.0.1+cu118 
torchvision==0.15.2+cu118 --extra-index-url https://download.pytorch.org/whl/cu118 # no_verify leave this to specify not checking this a verification stage
xformers==0.0.20 
bitsandbytes==0.40.2
accelerate==0.21.0
tensorboard==2.12.1 
tensorflow==2.12.0
```

My requirements file that is workiong @bmaltais 
Should I open a PR?

**Comment by tostangs** [comment]
Hey @markojak would you be willing to provide your exact steps for installation? I'm trying to install kohya onto an ubuntu 22.04 server as well but am running into many of your same issues unfortunately
