### ISSUE TITLE
LORA Training -> RuntimeError: CUDA error: CUBLAS_STATUS_EXECUTION_FAILED

### ISSUE THREAD

**Issue by VampiricDusk** [bmaltais/kohya_ss#1380]
Hello,

Getting this error while training lora:

RuntimeError: CUDA error: CUBLAS_STATUS_EXECUTION_FAILED when calling `cublasGemmEx( handle, opa, opb, m, n, k, &falpha,a, CUDA_R_16BF, lda, b, CUDA_R_16BF, ldb, &fbeta, c, CUDA_R_16BF, ldc, CUDA_R_32F, CUBLAS_GEMM_DFALT_TENSOR_OP)`

(Any ideas how to solve?)

----------------------------------------------

Modules installed outside the virtual environment were found.
This can cause issues. Please review the installed modules.

You can uninstall all local modules with:

deactivate
pip freeze > uninstall.txt
pip uninstall -y -r uninstall.txt

14:14:12-652232 INFO     Version: v21.8.7

14:14:12-658233 INFO     nVidia toolkit detected
14:14:14-145143 INFO     Torch 2.0.1+cu118
14:14:14-162148 INFO     Torch backend: nVidia CUDA 11.8 cuDNN 8700
14:14:14-163148 INFO     Torch detected GPU: NVIDIA GeForce RTX 4060 Ti VRAM 8187 Arch (8, 9) Cores 34
14:14:14-165153 INFO     Verifying modules instalation status from requirements_windows_torch2.txt...
14:14:14-167654 INFO     Verifying modules instalation status from requirements.txt...
14:14:16-759851 INFO     headless: False
14:14:16-763351 INFO     Load CSS...
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.

RAM 64GB sticks

----------------------------------------------------------------------------------------------------------------------
FULL COPY/PASTE below
----------------------------------------------------------------------------------------------------------------------

steps:   0%|                                                          | 3/7200 [01:17<51:37:14, 25.82s/it, loss=0.0585]╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ Y:\Program Files\SDXL etc\kohya_ss\sdxl_train_network.py:174 in <module>                         │
│                                                                                                  │
│   171 │   args = train_util.read_config_from_file(args, parser)                                  │
│   172 │                                                                                          │
│   173 │   trainer = SdxlNetworkTrainer()                                                         │
│ ❱ 174 │   trainer.train(args)                                                                    │
│   175                                                                                            │
│                                                                                                  │
│ Y:\Program Files\SDXL etc\kohya_ss\train_network.py:798 in train                                 │
│                                                                                                  │
│   795 │   │   │   │   │                                                                          │
│   796 │   │   │   │   │   loss = loss.mean()  # 平均なのでbatch_sizeで割る必要なし               │
│   797 │   │   │   │   │                                                                          │
│ ❱ 798 │   │   │   │   │   accelerator.backward(loss)                                             │
│   799 │   │   │   │   │   if accelerator.sync_gradients and args.max_grad_norm != 0.0:           │
│   800 │   │   │   │   │   │   params_to_clip = network.get_trainable_params()                    │
│   801 │   │   │   │   │   │   accelerator.clip_grad_norm_(params_to_clip, args.max_grad_norm)    │
│                                                                                                  │
│ Y:\Program Files\SDXL etc\kohya_ss\venv\lib\site-packages\accelerate\accelerator.py:1745 in      │
│ backward                                                                                         │
│                                                                                                  │
│   1742 │   │   elif self.scaler is not None:                                                     │
│   1743 │   │   │   self.scaler.scale(loss).backward(**kwargs)                                    │
│   1744 │   │   else:                                                                             │
│ ❱ 1745 │   │   │   loss.backward(**kwargs)                                                       │
│   1746 │                                                                                         │
│   1747 │   def unscale_gradients(self, optimizer=None):                                          │
│   1748 │   │   """                                                                               │
│                                                                                                  │
│ Y:\Program Files\SDXL etc\kohya_ss\venv\lib\site-packages\torch\_tensor.py:487 in backward       │
│                                                                                                  │
│    484 │   │   │   │   create_graph=create_graph,                                                │
│    485 │   │   │   │   inputs=inputs,                                                            │
│    486 │   │   │   )                                                                             │
│ ❱  487 │   │   torch.autograd.backward(                                                          │
│    488 │   │   │   self, gradient, retain_graph, create_graph, inputs=inputs                     │
│    489 │   │   )                                                                                 │
│    490                                                                                           │
│                                                                                                  │
│ Y:\Program Files\SDXL etc\kohya_ss\venv\lib\site-packages\torch\autograd\__init__.py:200 in      │
│ backward                                                                                         │
│                                                                                                  │
│   197 │   # The reason we repeat same the comment below is that                                  │
│   198 │   # some Python versions print out the first line of a multi-line function               │
│   199 │   # calls in the traceback and some print out the last line                              │
│ ❱ 200 │   Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the bac   │
│   201 │   │   tensors, grad_tensors_, retain_graph, create_graph, inputs,                        │
│   202 │   │   allow_unreachable=True, accumulate_grad=True)  # Calls into the C++ engine to ru   │
│   203                                                                                            │
│                                                                                                  │
│ Y:\Program Files\SDXL etc\kohya_ss\venv\lib\site-packages\torch\autograd\function.py:274 in      │
│ apply                                                                                            │
│                                                                                                  │
│   271 │   │   │   │   │   │   │      "Function is not allowed. You should only implement one "   │
│   272 │   │   │   │   │   │   │      "of them.")                                                 │
│   273 │   │   user_fn = vjp_fn if vjp_fn is not Function.vjp else backward_fn                    │
│ ❱ 274 │   │   return user_fn(self, *args)                                                        │
│   275 │                                                                                          │
│   276 │   def apply_jvp(self, *args):                                                            │
│   277 │   │   # _forward_cls is defined by derived class                                         │
│                                                                                                  │
│ Y:\Program Files\SDXL etc\kohya_ss\venv\lib\site-packages\torch\utils\checkpoint.py:157 in       │
│ backward                                                                                         │
│                                                                                                  │
│   154 │   │   │   raise RuntimeError(                                                            │
│   155 │   │   │   │   "none of output has requires_grad=True,"                                   │
│   156 │   │   │   │   " this checkpoint() is not necessary")                                     │
│ ❱ 157 │   │   torch.autograd.backward(outputs_with_grad, args_with_grad)                         │
│   158 │   │   grads = tuple(inp.grad if isinstance(inp, torch.Tensor) else None                  │
│   159 │   │   │   │   │     for inp in detached_inputs)                                          │
│   160                                                                                            │
│                                                                                                  │
│ Y:\Program Files\SDXL etc\kohya_ss\venv\lib\site-packages\torch\autograd\__init__.py:200 in      │
│ backward                                                                                         │
│                                                                                                  │
│   197 │   # The reason we repeat same the comment below is that                                  │
│   198 │   # some Python versions print out the first line of a multi-line function               │
│   199 │   # calls in the traceback and some print out the last line                              │
│ ❱ 200 │   Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the bac   │
│   201 │   │   tensors, grad_tensors_, retain_graph, create_graph, inputs,                        │
│   202 │   │   allow_unreachable=True, accumulate_grad=True)  # Calls into the C++ engine to ru   │
│   203                                                                                            │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
RuntimeError: CUDA error: CUBLAS_STATUS_EXECUTION_FAILED when calling `cublasGemmEx( handle, opa, opb, m, n, k, &falpha,a, CUDA_R_16BF, lda, b, CUDA_R_16BF, ldb, &fbeta, c, CUDA_R_16BF, ldc, CUDA_R_32F, CUBLAS_GEMM_DFALT_TENSOR_OP)`
steps:   0%|                                                          | 3/7200 [01:51<74:03:44, 37.05s/it, loss=0.0585]
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ Y:\Python3106\lib\runpy.py:196 in _run_module_as_main                                            │
│                                                                                                  │
│   193 │   main_globals = sys.modules["__main__"].__dict__                                        │
│   194 │   if alter_argv:                                                                         │
│   195 │   │   sys.argv[0] = mod_spec.origin                                                      │
│ ❱ 196 │   return _run_code(code, main_globals, None,                                             │
│   197 │   │   │   │   │    "__main__", mod_spec)                                                 │
│   198                                                                                            │
│   199 def run_module(mod_name, init_globals=None,                                                │
│                                                                                                  │
│ Y:\Python3106\lib\runpy.py:86 in _run_code                                                       │
│                                                                                                  │
│    83 │   │   │   │   │      __loader__ = loader,                                                │
│    84 │   │   │   │   │      __package__ = pkg_name,                                             │
│    85 │   │   │   │   │      __spec__ = mod_spec)                                                │
│ ❱  86 │   exec(code, run_globals)                                                                │
│    87 │   return run_globals                                                                     │
│    88                                                                                            │
│    89 def _run_module_code(code, init_globals=None,                                              │
│                                                                                                  │
│ in <module>:7                                                                                    │
│                                                                                                  │
│   4 from accelerate.commands.accelerate_cli import main                                          │
│   5 if __name__ == '__main__':                                                                   │
│   6 │   sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])                         │
│ ❱ 7 │   sys.exit(main())                                                                         │
│   8                                                                                              │
│                                                                                                  │
│ Y:\Program Files\SDXL                                                                            │
│ etc\kohya_ss\venv\lib\site-packages\accelerate\commands\accelerate_cli.py:45 in main             │
│                                                                                                  │
│   42 │   │   exit(1)                                                                             │
│   43 │                                                                                           │
│   44 │   # Run                                                                                   │
│ ❱ 45 │   args.func(args)                                                                         │
│   46                                                                                             │
│   47                                                                                             │
│   48 if __name__ == "__main__":                                                                  │
│                                                                                                  │
│ Y:\Program Files\SDXL etc\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py:918 in   │
│ launch_command                                                                                   │
│                                                                                                  │
│   915 │   elif defaults is not None and defaults.compute_environment == ComputeEnvironment.AMA   │
│   916 │   │   sagemaker_launcher(defaults, args)                                                 │
│   917 │   else:                                                                                  │
│ ❱ 918 │   │   simple_launcher(args)                                                              │
│   919                                                                                            │
│   920                                                                                            │
│   921 def main():                                                                                │
│                                                                                                  │
│ Y:\Program Files\SDXL etc\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py:580 in   │
│ simple_launcher                                                                                  │
│                                                                                                  │
│   577 │   process.wait()                                                                         │
│   578 │   if process.returncode != 0:                                                            │
│   579 │   │   if not args.quiet:                                                                 │
│ ❱ 580 │   │   │   raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)    │
│   581 │   │   else:                                                                              │
│   582 │   │   │   sys.exit(1)                                                                    │
│   583                                                                                            │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
CalledProcessError: Command '['Y:\\Program Files\\SDXL etc\\kohya_ss\\venv\\Scripts\\python.exe',
'./sdxl_train_network.py', '--enable_bucket', '--min_bucket_reso=256', '--max_bucket_reso=2048',
'--pretrained_model_name_or_path=Y:/Program Files/SDXL
etc/stable-diffusion-webui/models/Stable-diffusion/sd_xl_base_1.0_0.9vae.safetensors', '--train_data_dir=Y:\\Program
Files\\SDXL etc\\--Training--\\Kohya Trained\\img', '--reg_data_dir=Y:\\Program Files\\SDXL etc\\--Training--\\Kohya
Trained\\reg', '--resolution=1024,1024', '--output_dir=Y:\\Program Files\\SDXL etc\\--Training--\\Kohya Trained\\model','--logging_dir=Y:\\Program Files\\SDXL etc\\--Training--\\Kohya Trained\\log', '--network_alpha=1',
'--save_model_as=safetensors', '--network_module=networks.lora', '--text_encoder_lr=0.0004', '--unet_lr=0.0004',
'--network_dim=250', '--output_name=last', '--lr_scheduler_num_cycles=4', '--no_half_vae', '--learning_rate=0.0004',
'--lr_scheduler=cosine', '--train_batch_size=1', '--max_train_steps=7200', '--save_every_n_epochs=1',
'--mixed_precision=bf16', '--save_precision=bf16', '--cache_latents', '--cache_latents_to_disk',
'--optimizer_type=Adafactor', '--optimizer_args', 'scale_parameter=False', 'relative_step=False', 'warmup_init=False',
'--max_data_loader_n_workers=0', '--bucket_reso_steps=64', '--gradient_checkpointing', '--xformers',
'--bucket_no_upscale', '--noise_offset=0.0']

**Comment by VampiricDusk** [comment]
Here is what CHATGPT has to say about the error (and I am still clueless on what to do):

Anyone know what to do? I have yet to be able to train a LORA
-----------------------------------------------------------------------
The provided text appears to be a portion of a traceback from a Python script that encountered an error during its execution. The error seems to be related to a CUDA operation (cublasGemmEx) and has resulted in a RuntimeError. The traceback provides information about the sequence of function calls and files that led to the error. However, without access to the complete context, it's difficult to pinpoint the exact location where the code execution stopped.

The traceback indicates that the error occurred within a script named sdxl_train_network.py, specifically within a function call to trainer.train(args). Within the train function, there is a call to accelerator.backward(loss), which is followed by a series of nested function calls within the torch and accelerate libraries.

To determine the exact location where the code execution stopped, you would need to look for the last function call in the traceback before the RuntimeError occurred. This function call corresponds to where the code execution was when the error was raised. It's possible that the error is related to the usage of CUDA, GPU operations, or deep learning frameworks.

If you have access to the full traceback and code, you can analyze it in more detail to identify the specific line of code or operation that triggered the error. If you're having trouble resolving the issue, consider reaching out to the community forums or support channels of the relevant libraries or frameworks for assistance.

**Comment by VampiricDusk** [comment]
Issue solved.

Not sure how but I can tell that what might have fixed it for me was a reinstall of my NVIDIA driver as Kohya started training the next time I started it up right after that.

**Comment by AyoKeito** [comment]
A little bit of necromancy, but for me the solution was clearing latent cache. 
Simply remove all *.NPZ files from the image directory.
