### ISSUE TITLE
Version 22.1.0 CUDA not available

### ISSUE THREAD

**Issue by G-Grifflu** [bmaltais/kohya_ss#1608]
After updating to v22.1.0 CUDA is no longer available. Or so it says when launching Kohya.

> INFO     Version: v22.1.0
>
>INFO     nVidia toolkit detected
>INFO     Torch 2.0.1+cpu
>WARNING  Torch reports CUDA not available

**Comment by abozahran** [comment]
I have similar or same issue
ValueError: torch.cuda.is_available() should be True but is False. xformers' memory efficient attention is only available for GPU

**Comment by abozahran** [comment]
I fixed the problem.
I found out it's the gpu setting.
I ran 'accelerate config', at 'what gpu to use' part type in 'all'. ('ALL' in lower-case)
