### ISSUE TITLE
ValueError: torch.cuda.is_available() should be True but is False. xformers' memory efficient attention is only available for GPU

### ISSUE THREAD

**Issue by Pokilokui** [bmaltais/kohya_ss#1638]
tried to set all in lower case to gpu select but does not work

Traceback (most recent call last):
  File "D:\AI\Kohya\kohya_ss\train_network.py", line 1009, in <module>
    trainer.train(args)
  File "D:\AI\Kohya\kohya_ss\train_network.py", line 232, in train
    vae.set_use_memory_efficient_attention_xformers(args.xformers)
  File "D:\AI\Kohya\kohya_ss\venv\lib\site-packages\diffusers\models\modeling_utils.py", line 251, in set_use_memory_efficient_attention_xformers
    fn_recursive_set_mem_eff(module)
  File "D:\AI\Kohya\kohya_ss\venv\lib\site-packages\diffusers\models\modeling_utils.py", line 247, in fn_recursive_set_mem_eff
    fn_recursive_set_mem_eff(child)
  File "D:\AI\Kohya\kohya_ss\venv\lib\site-packages\diffusers\models\modeling_utils.py", line 247, in fn_recursive_set_mem_eff
    fn_recursive_set_mem_eff(child)
  File "D:\AI\Kohya\kohya_ss\venv\lib\site-packages\diffusers\models\modeling_utils.py", line 247, in fn_recursive_set_mem_eff
    fn_recursive_set_mem_eff(child)
  File "D:\AI\Kohya\kohya_ss\venv\lib\site-packages\diffusers\models\modeling_utils.py", line 244, in fn_recursive_set_mem_eff
    module.set_use_memory_efficient_attention_xformers(valid, attention_op)
  File "D:\AI\Kohya\kohya_ss\venv\lib\site-packages\diffusers\models\attention_processor.py", line 203, in set_use_memory_efficient_attention_xformers
    raise ValueError(
ValueError: torch.cuda.is_available() should be True but is False. xformers' memory efficient attention is only available for GPU
Traceback (most recent call last):
  File "C:\Users\Elouan\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Elouan\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "D:\AI\Kohya\kohya_ss\venv\Scripts\accelerate.exe\__main__.py", line 7, in <module>
  File "D:\AI\Kohya\kohya_ss\venv\lib\site-packages\accelerate\commands\accelerate_cli.py", line 47, in main
    args.func(args)
  File "D:\AI\Kohya\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 986, in launch_command
    simple_launcher(args)
  File "D:\AI\Kohya\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 628, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['D:\\AI\\Kohya\\kohya_ss\\venv\\Scripts\\python.exe', './train_network.py', '--enable_bucket', '--min_bucket_reso=256', '--max_bucket_reso=2048', '--pretrained_model_name_or_path=runwayml/stable-diffusion-v1-5', '--train_data_dir=D:/AI/Kohya/kunaboto/kunaboto style/image', '--resolution=512,512', '--output_dir=D:/AI/Kohya/kunaboto/kunaboto style/model', '--logging_dir=D:/AI/Kohya/kunaboto/kunaboto style/log', '--network_alpha=128', '--save_model_as=safetensors', '--network_module=networks.lora', '--text_encoder_lr=5e-05', '--unet_lr=0.0001', '--network_dim=128', '--output_name=Kunaboto style', '--lr_scheduler_num_cycles=1', '--no_half_vae', '--learning_rate=0.0001', '--lr_scheduler=constant', '--train_batch_size=2', '--max_train_steps=1300', '--save_every_n_epochs=1', '--mixed_precision=bf16', '--save_precision=bf16', '--seed=1234', '--caption_extension=.txt', '--cache_latents', '--optimizer_type=AdamW8bit', '--max_data_loader_n_workers=1', '--clip_skip=2', '--bucket_reso_steps=64', '--xformers', '--bucket_no_upscale', '--noise_offset=0.0']' returned non-zero exit status 1.

**Comment by sammcj** [comment]
Came here to log this as well, it occurs with the docker image which used to work fine but now doesn't, it looks like transformers was installed with a version that wasn't built with CUDA support.

```
WARNING[XFORMERS]: xFormers can't load C++/CUDA extensions. xFormers was built for:
    PyTorch 2.0.1+cu118 with CUDA 1108 (you have 2.1.0+cu121)
    Python  3.10.11 (you have 3.10.13)
...
NotImplementedError: No operator found for `memory_efficient_attention_forward` with inputs:
     query       : shape=(1, 2, 1, 40) (torch.float32)
     key         : shape=(1, 2, 1, 40) (torch.float32)
     value       : shape=(1, 2, 1, 40) (torch.float32)
     attn_bias   : <class 'NoneType'>
     p           : 0.0
`flshattF` is not supported because:
    xFormers wasn't build with CUDA support
    dtype=torch.float32 (supported: {torch.float16, torch.bfloat16})
    Operator wasn't built - see `python -m xformers.info` for more info
`tritonflashattF` is not supported because:
    xFormers wasn't build with CUDA support
    dtype=torch.float32 (supported: {torch.float16, torch.bfloat16})
    requires A100 GPU
    Only work on pre-MLIR triton for now
`cutlassF` is not supported because:
    xFormers wasn't build with CUDA support
    Operator wasn't built - see `python -m xformers.info` for more info
`smallkF` is not supported because:
    xFormers wasn't build with CUDA support
    max(query.shape[-1] != value.shape[-1]) > 32
    Operator wasn't built - see `python -m xformers.info` for more info
    unsupported embed per head: 40
```

**Comment by sammcj** [comment]
It also looks like tensorflow was built for CPU only and without any AVX acceleration!

```
This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.

To enable the following instructions: AVX2 AVX512F AVX512_VNNI AVX512_BF16 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
```

**Comment by h3clikejava** [comment]
I encountered the same problem, suddenly appeared. How to solve?

**Comment by sarojkumarss** [comment]
To create a public link, set `share=True` in `launch()`.
19:35:16-739216 INFO     Start training LoRA Standard ...
19:35:16-740721 INFO     Checking for duplicate image filenames in training data directory...
19:35:16-743723 INFO     Valid image folder names found in: D:/Lora Training/Lora Training/img
19:35:16-744724 INFO     Valid image folder names found in: D:/Lora Training/Lora Training/reg
19:35:16-746724 INFO     Folder 100_Sw3tha woman: 26 images found
19:35:16-747724 INFO     Folder 100_Sw3tha woman: 2600 steps
19:35:16-748724 WARNING  Regularisation images are used... Will double the number of steps required...
19:35:16-750228 INFO     Total steps: 2600
19:35:16-751250 INFO     Train batch size: 2
19:35:16-752355 INFO     Gradient accumulation steps: 1
19:35:16-754355 INFO     Epoch: 4
19:35:16-755355 INFO     Regulatization factor: 2
19:35:16-756355 INFO     max_train_steps (2600 / 2 / 1 * 4 * 2) = 10400
19:35:16-757355 INFO     stop_text_encoder_training = 0
19:35:16-758356 INFO     lr_warmup_steps = 0
19:35:16-759356 INFO     Saving training config to D:/Lora Training/Lora
                         Training/model\Sw3tha_T_1_20231104-193516.json...
19:35:16-761937 INFO     accelerate launch --num_cpu_threads_per_process=2 "./train_network.py" --enable_bucket
                         --min_bucket_reso=256 --max_bucket_reso=2048 --pretrained_model_name_or_path="D:/Lora
                         Training/realisticVisionV51_v20Novae.safetensors" --train_data_dir="D:/Lora Training/Lora
                         Training/img" --reg_data_dir="D:/Lora Training/Lora Training/reg" --resolution="512,512"
                         --output_dir="D:/Lora Training/Lora Training/model" --logging_dir="D:/Lora Training/Lora
                         Training/log" --network_alpha="1" --save_model_as=safetensors --network_module=networks.lora
                         --text_encoder_lr=5e-05 --unet_lr=0.0001 --network_dim=8 --output_name="Sw3tha_T_1"
                         --lr_scheduler_num_cycles="4" --no_half_vae --learning_rate="0.0001" --lr_scheduler="constant"
                         --train_batch_size="2" --max_train_steps="10400" --save_every_n_epochs="1"
                         --mixed_precision="fp16" --save_precision="fp16" --cache_latents --optimizer_type="AdamW"
                         --max_data_loader_n_workers="0" --bucket_reso_steps=64 --xformers --bucket_no_upscale
                         --noise_offset=0.0
prepare tokenizer
Using DreamBooth method.
prepare images.
found directory D:\Lora Training\Lora Training\img\100_Sw3tha woman contains 26 image files
No caption file found for 26 images. Training will continue without captions for these images. If class token exists, it will be used. / 26枚の画像にキャプションファイルが見つかりませんでした。これらの画像についてはキャプションなしで学習を 続行します。class tokenが存在する場合はそれを使います。
D:\Lora Training\Lora Training\img\100_Sw3tha woman\Swetha (1).jpg
D:\Lora Training\Lora Training\img\100_Sw3tha woman\Swetha (10).jpg
D:\Lora Training\Lora Training\img\100_Sw3tha woman\Swetha (11).jpg
D:\Lora Training\Lora Training\img\100_Sw3tha woman\Swetha (12).jpg
D:\Lora Training\Lora Training\img\100_Sw3tha woman\Swetha (13).jpg
D:\Lora Training\Lora Training\img\100_Sw3tha woman\Swetha (14).jpg... and 21 more
found directory D:\Lora Training\Lora Training\reg\1_woman contains 3094 image files
No caption file found for 3094 images. Training will continue without captions for these images. If class token exists, it will be used. / 3094枚の画像にキャプションファイルが見つかりませんでした。これらの画像についてはキャプションなしで学 習を続行します。class tokenが存在する場合はそれを使います。
D:\Lora Training\Lora Training\reg\1_woman\000ec56dfb20adadc286bfcfbaff808d9baa3be1.png
D:\Lora Training\Lora Training\reg\1_woman\00c54c34a72c0aa645fa0f0600ffcd20993415ae.png
D:\Lora Training\Lora Training\reg\1_woman\01141f93a90475633b67a52e962db6c1ded4c2c1.png
D:\Lora Training\Lora Training\reg\1_woman\014f68f49bbe86ae069ed2983fe6b0bb190a02b3.png
D:\Lora Training\Lora Training\reg\1_woman\0172b1968fa4dbf02e580d2f8543e3046cd9a04e.png
D:\Lora Training\Lora Training\reg\1_woman\01c75252dc92c4783ff229eb769f45fedf77c47b.png... and 3089 more
2600 train images with repeating.
3094 reg images.
some of reg images are not used / 正則化画像の数が多いので、一部使用されない正則化画像があります
[Dataset 0]
  batch_size: 2
  resolution: (512, 512)
  enable_bucket: True
  min_bucket_reso: 256
  max_bucket_reso: 2048
  bucket_reso_steps: 64
  bucket_no_upscale: True

  [Subset 0 of Dataset 0]
    image_dir: "D:\Lora Training\Lora Training\img\100_Sw3tha woman"
    image_count: 26
    num_repeats: 100
    shuffle_caption: False
    keep_tokens: 0
    caption_dropout_rate: 0.0
    caption_dropout_every_n_epoches: 0
    caption_tag_dropout_rate: 0.0
    caption_prefix: None
    caption_suffix: None
    color_aug: False
    flip_aug: False
    face_crop_aug_range: None
    random_crop: False
    token_warmup_min: 1,
    token_warmup_step: 0,
    is_reg: False
    class_tokens: Sw3tha woman
    caption_extension: .caption

  [Subset 1 of Dataset 0]
    image_dir: "D:\Lora Training\Lora Training\reg\1_woman"
    image_count: 3094
    num_repeats: 1
    shuffle_caption: False
    keep_tokens: 0
    caption_dropout_rate: 0.0
    caption_dropout_every_n_epoches: 0
    caption_tag_dropout_rate: 0.0
    caption_prefix: None
    caption_suffix: None
    color_aug: False
    flip_aug: False
    face_crop_aug_range: None
    random_crop: False
    token_warmup_min: 1,
    token_warmup_step: 0,
    is_reg: True
    class_tokens: woman
    caption_extension: .caption


[Dataset 0]
loading image sizes.
100%|█████████████████████████████████████████████████████████████████████████████| 2626/2626 [00:13<00:00, 188.47it/s]
make buckets
min_bucket_reso and max_bucket_reso are ignored if bucket_no_upscale is set, because bucket reso is defined by image size automatically / bucket_no_upscaleが指定された場合は、bucketの解像度は画像サイズから自動計算されるため、min_bucket_resoとmax_bucket_resoは無視されます
number of images (including repeats) / 各bucketの画像枚数（繰り返し回数を含む）
bucket 0: resolution (320, 640), count: 100
bucket 1: resolution (384, 512), count: 400
bucket 2: resolution (384, 576), count: 1000
bucket 3: resolution (384, 640), count: 200
bucket 4: resolution (448, 576), count: 100
bucket 5: resolution (512, 384), count: 200
bucket 6: resolution (512, 448), count: 100
bucket 7: resolution (512, 512), count: 2600
bucket 8: resolution (576, 384), count: 400
bucket 9: resolution (576, 448), count: 100
mean ar error (without repeats): 0.00021692813305737463
preparing accelerator
loading model for process 0/1
load StableDiffusion checkpoint: D:/Lora Training/realisticVisionV51_v20Novae.safetensors
UNet2DConditionModel: 64, 8, 768, False, False
loading u-net: <All keys matched successfully>
loading vae: <All keys matched successfully>
loading text encoder: <All keys matched successfully>
Enable xformers for U-Net
Traceback (most recent call last):
  File "D:\Kohya\kohya_ss\train_network.py", line 1009, in <module>
    trainer.train(args)
  File "D:\Kohya\kohya_ss\train_network.py", line 232, in train
    vae.set_use_memory_efficient_attention_xformers(args.xformers)
  File "D:\Kohya\kohya_ss\venv\lib\site-packages\diffusers\models\modeling_utils.py", line 251, in set_use_memory_efficient_attention_xformers
    fn_recursive_set_mem_eff(module)
  File "D:\Kohya\kohya_ss\venv\lib\site-packages\diffusers\models\modeling_utils.py", line 247, in fn_recursive_set_mem_eff
    fn_recursive_set_mem_eff(child)
  File "D:\Kohya\kohya_ss\venv\lib\site-packages\diffusers\models\modeling_utils.py", line 247, in fn_recursive_set_mem_eff
    fn_recursive_set_mem_eff(child)
  File "D:\Kohya\kohya_ss\venv\lib\site-packages\diffusers\models\modeling_utils.py", line 247, in fn_recursive_set_mem_eff
    fn_recursive_set_mem_eff(child)
  File "D:\Kohya\kohya_ss\venv\lib\site-packages\diffusers\models\modeling_utils.py", line 244, in fn_recursive_set_mem_eff
    module.set_use_memory_efficient_attention_xformers(valid, attention_op)
  File "D:\Kohya\kohya_ss\venv\lib\site-packages\diffusers\models\attention_processor.py", line 203, in set_use_memory_efficient_attention_xformers
    raise ValueError(
ValueError: torch.cuda.is_available() should be True but is False. xformers' memory efficient attention is only available for GPU
Traceback (most recent call last):
  File "C:\Users\saroj\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\saroj\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "D:\Kohya\kohya_ss\venv\Scripts\accelerate.exe\__main__.py", line 7, in <module>
  File "D:\Kohya\kohya_ss\venv\lib\site-packages\accelerate\commands\accelerate_cli.py", line 47, in main
    args.func(args)
  File "D:\Kohya\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 986, in launch_command
    simple_launcher(args)
  File "D:\Kohya\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 628, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['D:\\Kohya\\kohya_ss\\venv\\Scripts\\python.exe', './train_network.py', '--enable_bucket', '--min_bucket_reso=256', '--max_bucket_reso=2048', '--pretrained_model_name_or_path=D:/Lora Training/realisticVisionV51_v20Novae.safetensors', '--train_data_dir=D:/Lora Training/Lora Training/img', '--reg_data_dir=D:/Lora Training/Lora Training/reg', '--resolution=512,512', '--output_dir=D:/Lora Training/Lora Training/model', '--logging_dir=D:/Lora Training/Lora Training/log', '--network_alpha=1', '--save_model_as=safetensors', '--network_module=networks.lora', '--text_encoder_lr=5e-05', '--unet_lr=0.0001', '--network_dim=8', '--output_name=Sw3tha_T_1', '--lr_scheduler_num_cycles=4', '--no_half_vae', '--learning_rate=0.0001', '--lr_scheduler=constant', '--train_batch_size=2', '--max_train_steps=10400', '--save_every_n_epochs=1', '--mixed_precision=fp16', '--save_precision=fp16', '--cache_latents', '--optimizer_type=AdamW', '--max_data_loader_n_workers=0', '--bucket_reso_steps=64', '--xformers', '--bucket_no_upscale', '--noise_offset=0.0']' returned non-zero exit status 1.


I have the same issue. 
ValueError: torch.cuda.is_available() should be True but is False. xformers' memory efficient attention is only available for GPU

Can anyone help us on this issue??

**Comment by sarojkumarss** [comment]
Got the solution from another post.
run 'accelerate config' in powershell
When asking 'what gpu to use' part type in 'all'. ('ALL' in lower-case)

**Comment by heartlocket** [comment]
Seems broken. Anyone else know a decent lora alternative with a well-maintained repo?

**Comment by segalinc** [comment]
made it work adding `--gpu_ids=0` at line 724 of `lora_gui.py`

**Comment by ZhangEnsure** [comment]
> made it work adding `--gpu_ids=0` at line 724 of `lora_gui.py`

Hello,Could you show your code?thank you thankyou!!!

**Comment by spikers** [comment]
The error apparently is saying that the specific "xformers" feature's memory efficient attention is only available for Nvidia GPUs. I use an AMD GPU, so I just disabled it. I did that by: Under "Advanced", you'll see "CrossAttention" and it's "xformers" by default. I set that to "none".

For me, it also complained about fp16 or something. Up on top, under "Accelerate Launch" under "Mixed precision", use "no", I think that forces it to use full 32-bit precision. I was able to CPU train a model last night and it gave me a .safetensors file, but it took forever (6h) and the results were awful, so take that with a grain of salt.

**Comment by emosGambler** [comment]
> finally conquered the problem. xFormers needs to be installed first and very explicitly. otherwise it will install cpu package only. long story short `python -m pip uninstall xformers torch torchvision -y` uninstalling torchvision and torch because they likely are non-cuda versions too, as xformers is installing them. just clean everything. `python -m pip install xformers torchvision --index-url https://download.pytorch.org/whl/cu121` if you have cuda 12, or 118, 116 depending on your version. `python -m pip` is more reliable than just `pip` because sometimes (dont ask how i know) pip might be calling different version python pip than what is being called when training

Worked like a charm, good Sir!
