### ISSUE TITLE
LoRA Low Vram Training Errors on GTX 1000 Series GPUs

### ISSUE THREAD

**Issue by kartiksharmakk** [bmaltais/kohya_ss#164]
GPU Used : Gtx 1060 6gb
OS : Windows 10 pro
Ram : 16gb
Error no kernel image is available or execution on the device at line 167 in file D:\ai\tool\bitsandbytes\csrc\ops.cu
![kernel_error](https://user-images.githubusercontent.com/77577353/218534199-d19254b4-3e59-49a2-87b4-12722f9b6365.png)

**Comment by ashmodai6** [comment]
Got the same error while trying to use a Tesla P4 (which has 8GB of ram)

**Comment by Tempaccnt** [comment]
disable 8bit adam and make sure to choose pf16 instead of bf16 for the precision options

**Comment by kartiksharmakk** [comment]
that solved it , thanks
