### ISSUE TITLE
bitsandbytes error.

### ISSUE THREAD

**Issue by 444butter** [bmaltais/kohya_ss#1800]
i have tried everything i can think of to solve this but i couldnt. i reinstalled mini conda, i installed nvidia webkit, i reinstalled the webui program many times, i reinstalled bitsandbytes many times, asked chat gpt, but nothing i did fixed it.

Traceback (most recent call last):
  File "C:\Users\user\Videos\ai\image\image_gen\dreambooth\kohya_ss-master\kohya_ss-master\library\train_util.py", line 3444, in get_optimizer
    import bitsandbytes as bnb
  File "C:\Users\user\Videos\ai\image\image_gen\dreambooth\kohya_ss-master\kohya_ss-master\venv\lib\site-packages\bitsandbytes\__init__.py", line 6, in <module>
    from . import cuda_setup, utils, research
  File "C:\Users\user\Videos\ai\image\image_gen\dreambooth\kohya_ss-master\kohya_ss-master\venv\lib\site-packages\bitsandbytes\research\__init__.py", line 1, in <module>
    from . import nn
  File "C:\Users\user\Videos\ai\image\image_gen\dreambooth\kohya_ss-master\kohya_ss-master\venv\lib\site-packages\bitsandbytes\research\nn\__init__.py", line 1, in <module>
    from .modules import LinearFP8Mixed, LinearFP8Global
  File "C:\Users\user\Videos\ai\image\image_gen\dreambooth\kohya_ss-master\kohya_ss-master\venv\lib\site-packages\bitsandbytes\research\nn\modules.py", line 8, in <module>
    from bitsandbytes.optim import GlobalOptimManager
  File "C:\Users\user\Videos\ai\image\image_gen\dreambooth\kohya_ss-master\kohya_ss-master\venv\lib\site-packages\bitsandbytes\optim\__init__.py", line 6, in <module>
    from bitsandbytes.cextension import COMPILED_WITH_CUDA
  File "C:\Users\user\Videos\ai\image\image_gen\dreambooth\kohya_ss-master\kohya_ss-master\venv\lib\site-packages\bitsandbytes\cextension.py", line 5, in <module>
    from .cuda_setup.main import evaluate_cuda_setup
  File "C:\Users\user\Videos\ai\image\image_gen\dreambooth\kohya_ss-master\kohya_ss-master\venv\lib\site-packages\bitsandbytes\cuda_setup\main.py", line 21, in <module>
    from .paths import determine_cuda_runtime_lib_path
ModuleNotFoundError: No module named 'bitsandbytes.cuda_setup.paths'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\user\Videos\ai\image\image_gen\dreambooth\kohya_ss-master\kohya_ss-master\train_network.py", line 1012, in <module>
    trainer.train(args)
  File "C:\Users\user\Videos\ai\image\image_gen\dreambooth\kohya_ss-master\kohya_ss-master\train_network.py", line 342, in train
    optimizer_name, optimizer_args, optimizer = train_util.get_optimizer(args, trainable_params)
  File "C:\Users\user\Videos\ai\image\image_gen\dreambooth\kohya_ss-master\kohya_ss-master\library\train_util.py", line 3446, in get_optimizer
    raise ImportError("No bitsandbytes / bitsandbytesがインストールされていないようです")
ImportError: No bitsandbytes / bitsandbytesがインストールされていないようです
Traceback (most recent call last):
  File "C:\Users\user\miniconda3\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\user\miniconda3\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\user\Videos\ai\image\image_gen\dreambooth\kohya_ss-master\kohya_ss-master\venv\Scripts\accelerate.exe\__main__.py", line 7, in <module>
  File "C:\Users\user\Videos\ai\image\image_gen\dreambooth\kohya_ss-master\kohya_ss-master\venv\lib\site-packages\accelerate\commands\accelerate_cli.py", line 47, in main
    args.func(args)
  File "C:\Users\user\Videos\ai\image\image_gen\dreambooth\kohya_ss-master\kohya_ss-master\venv\lib\site-packages\accelerate\commands\launch.py", line 986, in launch_command
    simple_launcher(args)
  File "C:\Users\user\Videos\ai\image\image_gen\dreambooth\kohya_ss-master\kohya_ss-master\venv\lib\site-packages\accelerate\commands\launch.py", line 628, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['C:\\Users\\user\\Videos\\ai\\image\\image_gen\\dreambooth\\kohya_ss-master\\kohya_ss-master\\venv\\Scripts\\python.exe', './train_network.py', '--enable_bucket', '--min_bucket_reso=256', '--max_bucket_reso=2048', '--pretrained_model_name_or_path=C:/Users/user/Videos/ai/image/image_gen/dreambooth/kohya_ss-master/kohya_ss-master/model.ckpt', '--train_data_dir=C:\\Users\\user\\Videos\\ai\\image\\image_gen\\dreambooth\\datasets\\bruh\\img', '--resolution=768,768', '--output_dir=C:\\Users\\user\\Videos\\ai\\image\\image_gen\\dreambooth\\datasets\\bruh\\model', '--logging_dir=C:\\Users\\user\\Videos\\ai\\image\\image_gen\\dreambooth\\datasets\\bruh\\log', '--network_alpha=128', '--save_model_as=safetensors', '--network_module=networks.lora', '--text_encoder_lr=5e-05', '--unet_lr=0.0001', '--network_dim=128', '--gradient_accumulation_steps=3', '--output_name=Greatm8', '--lr_scheduler_num_cycles=1', '--no_half_vae', '--learning_rate=0.0001', '--lr_scheduler=constant', '--train_batch_size=8', '--max_train_steps=69', '--save_every_n_epochs=1', '--mixed_precision=bf16', '--save_precision=bf16', '--seed=1234', '--caption_extension=.txt', '--cache_latents', '--cache_latents_to_disk', '--optimizer_type=AdamW8bit', '--max_grad_norm=1', '--max_data_loader_n_workers=0', '--clip_skip=2', '--bucket_reso_steps=64', '--xformers', '--bucket_no_upscale', '--noise_offset=0.0']' returned non-zero exit status 1.

--num_cpu_threads_per_process=2 "./train_network.py" --enable_bucket --min_bucket_reso=256 --max_bucket_reso=2048
                         --pretrained_model_name_or_path="C:/Users/user/Videos/ai/image/image_gen/dreambooth/kohya_ss-master/kohya_ss-master/model.ckpt"
                         --train_data_dir="C:\Users\user\Videos\ai\image\image_gen\dreambooth\datasets\bruh\img" --resolution="768,768" --output_dir="C:\Users\user\Videos\ai\image\image_gen\dreambooth\datasets\bruh\model"
                         --logging_dir="C:\Users\user\Videos\ai\image\image_gen\dreambooth\datasets\bruh\log" --network_alpha="128" --save_model_as=safetensors --network_module=networks.lora --text_encoder_lr=5e-05 --unet_lr=0.0001
                         --network_dim=128 --gradient_accumulation_steps=3 --output_name="Greatm8" --lr_scheduler_num_cycles="1" --no_half_vae --learning_rate="0.0001" --lr_scheduler="constant" --train_batch_size="8"
                         --max_train_steps="69" --save_every_n_epochs="1" --mixed_precision="bf16" --save_precision="bf16" --seed="1234" --caption_extension=".txt" --cache_latents --cache_latents_to_disk --optimizer_type="AdamW8bit"
                         --max_grad_norm="1" --max_data_loader_n_workers="0" --clip_skip=2 --bucket_reso_steps=64 --xformers --bucket_no_upscale --noise_offset=0.0

python -m bitsandbytes

  warn(msg)
================================================================================
CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching in backup paths...
The following directories listed in your path were found to be non-existent: {WindowsPath('/usr/local/cuda/lib64')}
DEBUG: Possible options found for libcudart.so: set()
CUDA SETUP: PyTorch settings found: CUDA_VERSION=118, Highest Compute Capability: 8.6.
CUDA SETUP: To manually override the PyTorch CUDA version please see:https://github.com/TimDettmers/bitsandbytes/blob/main/how_to_use_nonpytorch_cuda.md
CUDA SETUP: Loading binary C:\Users\user\Videos\ai\image\image_gen\dreambooth\kohya_ss-master\kohya_ss-master\venv\lib\site-packages\bitsandbytes\libbitsandbytes_cuda118.so...
argument of type 'WindowsPath' is not iterable
CUDA SETUP: Problem: The main issue seems to be that the main CUDA runtime library was not detected.
CUDA SETUP: Solution 1: To solve the issue the libcudart.so location needs to be added to the LD_LIBRARY_PATH variable
CUDA SETUP: Solution 1a): Find the cuda runtime library via: find / -name libcudart.so 2>/dev/null
CUDA SETUP: Solution 1b): Once the library is found add it to the LD_LIBRARY_PATH: export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:FOUND_PATH_FROM_1a
CUDA SETUP: Solution 1c): For a permanent solution add the export from 1b into your .bashrc file, located at ~/.bashrc
CUDA SETUP: Solution 2: If no library was found in step 1a) you need to install CUDA.
CUDA SETUP: Solution 2a): Download CUDA install script: wget https://github.com/TimDettmers/bitsandbytes/blob/main/cuda_install.sh
CUDA SETUP: Solution 2b): Install desired CUDA version to desired location. The syntax is bash cuda_install.sh CUDA_VERSION PATH_TO_INSTALL_INTO.
CUDA SETUP: Solution 2b): For example, "bash cuda_install.sh 113 ~/local/" will download CUDA 11.3 and install into the folder ~/local
Traceback (most recent call last):
  File "C:\Users\user\miniconda3\lib\runpy.py", line 187, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "C:\Users\user\miniconda3\lib\runpy.py", line 146, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "C:\Users\user\miniconda3\lib\runpy.py", line 110, in _get_module_details
    __import__(pkg_name)
  File "C:\Users\user\Videos\ai\image\image_gen\dreambooth\kohya_ss-master\kohya_ss-master\venv\lib\site-packages\bitsandbytes\__init__.py", line 6, in <module>
    from . import cuda_setup, utils, research
  File "C:\Users\user\Videos\ai\image\image_gen\dreambooth\kohya_ss-master\kohya_ss-master\venv\lib\site-packages\bitsandbytes\research\__init__.py", line 1, in <module>
    from . import nn
  File "C:\Users\user\Videos\ai\image\image_gen\dreambooth\kohya_ss-master\kohya_ss-master\venv\lib\site-packages\bitsandbytes\research\nn\__init__.py", line 1, in <module>
    from .modules import LinearFP8Mixed, LinearFP8Global
  File "C:\Users\user\Videos\ai\image\image_gen\dreambooth\kohya_ss-master\kohya_ss-master\venv\lib\site-packages\bitsandbytes\research\nn\modules.py", line 8, in <module>
    from bitsandbytes.optim import GlobalOptimManager
  File "C:\Users\user\Videos\ai\image\image_gen\dreambooth\kohya_ss-master\kohya_ss-master\venv\lib\site-packages\bitsandbytes\optim\__init__.py", line 6, in <module>
    from bitsandbytes.cextension import COMPILED_WITH_CUDA
  File "C:\Users\user\Videos\ai\image\image_gen\dreambooth\kohya_ss-master\kohya_ss-master\venv\lib\site-packages\bitsandbytes\cextension.py", line 20, in <module>
    raise RuntimeError('''
RuntimeError:
        CUDA Setup failed despite GPU being available. Please run the following command to get more information:

        python -m bitsandbytes

        Inspect the output of the command and see if you can locate CUDA libraries. You might need to add them
        to your LD_LIBRARY_PATH. If you suspect a bug, please take the information from python -m bitsandbytes
        and open an issue at: https://github.com/TimDettmers/bitsandbytes/issues

**Comment by Pychnight** [comment]
yeah the newer versions are broken, i had to roll back to 22.0.1 to get it working again.

i also got this error along with a error trying to train sd 1.5 models, but SDXL models kinda work.

**Comment by 444butter** [comment]
thanks will try

**Comment by karachay-b** [comment]
I've had the same issue on win10 and the following worked for me:

`./venv/Scripts/activate.ps1` with powershell

`pip uninstall bitsandbytes`

`pip uninstall bitsandbytes-windows`

Then I downloaded this wheel:
[bitsandbytes-0.41.2.post2-py3-none-win_amd64.whl](https://github.com/jllllll/bitsandbytes-windows-webui/releases/download/wheels/bitsandbytes-0.41.2.post2-py3-none-win_amd64.whl)

Placed it in `./venv/Scripts/`

Finally run:
`./venv/Scripts/activate.ps1` with powershell
and
`pip install bitsandbytes-0.41.2.post2-py3-none-win_amd64.whl`
