### ISSUE TITLE
Not installing all dependencies on Linux and another issues

### ISSUE THREAD

**Issue by WizardlyBump17** [bmaltais/kohya_ss#1855]
Hi, I am trying to train a Lora on a Linux computer. I have ran the `setup.sh` and `accelerate config`.
When I try to train a Lora with fp16, it gives me a bitsandbytes error telling me to run `python -m bitsandbytes`. When I run this command the Python says that no module was found, so I manually installed it. When running the `python -m bitsandbytes` again, it says it could find torch. Basically, all dependencies in the requirements_linux.txt are not being installed.

When everything is installed, I try to build the Lora with fp16 and again the same bitsandbytes error. `python -m bitsandbytes` says that it is rightly installed so I think this may be a different issue.

When switching to bfp16 it gives a PyTorch error.

`./gui.sh` log: (bf16 error first, then the fp16)
```
(kohya_ss) davi@davi:~/AI/kohya_ss$ ./gui.sh                                                                                                                  
21:38:12-111654 INFO     Version: v22.4.1                                                                                                                     
                                                                                                                                                              
21:38:12-122456 INFO     nVidia toolkit detected                                                                                                              
21:38:13-370537 INFO     Torch 2.0.1+cu118                                                                                                                    
21:38:13-654866 INFO     Torch backend: nVidia CUDA 11.8 cuDNN 8700                                                                                           
21:38:13-706565 INFO     Torch detected GPU: NVIDIA GeForce GTX 1650 VRAM 3716 Arch (7, 5) Cores 14                                                           
21:38:13-708363 INFO     Verifying modules installation status from /home/davi/AI/kohya_ss/requirements_linux.txt...                                          
21:38:13-711241 INFO     Verifying modules installation status from requirements.txt...                                                                       
21:38:16-185363 INFO     headless: False                                                                                                                      
21:38:16-190288 INFO     Load CSS...                                                                                                                          
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
21:38:36-092441 INFO     Loading config...                                                                                                                    
21:38:36-233317 INFO     runwayml/stable-diffusion-v1-5 model selected.                                                                                       
21:45:03-016069 INFO     Start training LoRA Standard ...                                                                                                     
21:45:03-017468 INFO     Checking for duplicate image filenames in training data directory...                                                                 
21:45:03-019142 INFO     Valid image folder names found in: /home/davi/Downloads/test/images                                                                  
21:45:03-020511 INFO     Folder 30_dindjarin: 10 images found                                                                                                 
21:45:03-021735 INFO     Folder 30_dindjarin: 300 steps                                                                                                       
21:45:03-022933 INFO     Total steps: 300                                                                                                                     
21:45:03-024017 INFO     Train batch size: 1                                                                                                                  
21:45:03-025090 INFO     Gradient accumulation steps: 1                                                                                                       
21:45:03-026384 INFO     Epoch: 1                                                                                                                             
21:45:03-027553 INFO     Regulatization factor: 1                                                                                                             
21:45:03-028685 INFO     max_train_steps (300 / 1 / 1 * 1 * 1) = 300                                                                                          
21:45:03-030434 INFO     stop_text_encoder_training = 0                                                                                                       
21:45:03-031533 INFO     lr_warmup_steps = 0                                                                                                                  
21:45:03-032967 INFO     Saving training config to /home/davi/Downloads/test/model/Addams_20240108-214503.json...                                             
21:45:03-034707 INFO     accelerate launch --num_cpu_threads_per_process=2 "./train_network.py" --v2 --v_parameterization                                     
                         --pretrained_model_name_or_path="/home/davi/AI/ComfyUI/models/checkpoints/v2-1_512-ema-pruned.safetensors"                           
                         --train_data_dir="/home/davi/Downloads/test/images" --resolution="512,512" --output_dir="/home/davi/Downloads/test/model"            
                         --logging_dir="/home/davi/Downloads/test/log" --network_alpha="128" --save_model_as=safetensors --network_module=networks.lora       
                         --text_encoder_lr=5e-05 --unet_lr=0.0001 --network_dim=128 --output_name="Addams" --lr_scheduler_num_cycles="1" --no_half_vae        
                         --learning_rate="0.0001" --lr_scheduler="constant" --train_batch_size="1" --max_train_steps="300" --save_every_n_epochs="1"          
                         --mixed_precision="bf16" --save_precision="bf16" --seed="1234" --caption_extension=".txt" --cache_latents                            
                         --optimizer_type="AdamW8bit" --max_grad_norm="1" --max_data_loader_n_workers="1" --clip_skip=2 --bucket_reso_steps=64 --mem_eff_attn 
                         --gradient_checkpointing --xformers --bucket_no_upscale --noise_offset=0.0                                                           
2024-01-08 21:45:07.829906: E tensorflow/compiler/xla/stream_executor/cuda/cuda_dnn.cc:9342] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-01-08 21:45:07.829941: E tensorflow/compiler/xla/stream_executor/cuda/cuda_fft.cc:609] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-01-08 21:45:07.829961: E tensorflow/compiler/xla/stream_executor/cuda/cuda_blas.cc:1518] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-01-08 21:45:07.836006: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-01-08 21:45:08.982530: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
v2 with clip_skip will be unexpected / v2でclip_skipを使用することは想定されていません
prepare tokenizer
Using DreamBooth method.
prepare images.
found directory /home/davi/Downloads/test/images/30_dindjarin contains 10 image files
300 train images with repeating.
0 reg images.
no regularization images / 正則化画像が見つかりませんでした
[Dataset 0]
  batch_size: 1
  resolution: (512, 512)
  enable_bucket: False

  [Subset 0 of Dataset 0]
    image_dir: "/home/davi/Downloads/test/images/30_dindjarin"
    image_count: 10
    num_repeats: 30
    shuffle_caption: False
    keep_tokens: 0
    keep_tokens_separator: 
    caption_dropout_rate: 0.0
    caption_dropout_every_n_epoches: 0
    caption_tag_dropout_rate: 0.0
    caption_prefix: None
    caption_suffix: None
    color_aug: False
    flip_aug: False
    face_crop_aug_range: None
    random_crop: False
    token_warmup_min: 1,
    token_warmup_step: 0,
    is_reg: False
    class_tokens: dindjarin
    caption_extension: .txt


[Dataset 0]
loading image sizes.
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 10/10 [00:00<00:00, 1948.94it/s]
prepare dataset
preparing accelerator
Traceback (most recent call last):
  File "/home/davi/AI/kohya_ss/./train_network.py", line 996, in <module>
    trainer.train(args)
  File "/home/davi/AI/kohya_ss/./train_network.py", line 226, in train
    accelerator = train_util.prepare_accelerator(args)
  File "/home/davi/AI/kohya_ss/library/train_util.py", line 3880, in prepare_accelerator
    accelerator = Accelerator(
  File "/home/davi/AI/kohya_ss/venv/lib/python3.10/site-packages/accelerate/accelerator.py", line 448, in __init__
    raise ValueError(err.format(mode="bf16", requirement="PyTorch >= 1.10 and a supported device."))
ValueError: bf16 mixed precision requires PyTorch >= 1.10 and a supported device.
Traceback (most recent call last):
  File "/home/davi/AI/kohya_ss/venv/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/home/davi/AI/kohya_ss/venv/lib/python3.10/site-packages/accelerate/commands/accelerate_cli.py", line 47, in main
    args.func(args)
  File "/home/davi/AI/kohya_ss/venv/lib/python3.10/site-packages/accelerate/commands/launch.py", line 986, in launch_command
    simple_launcher(args)
  File "/home/davi/AI/kohya_ss/venv/lib/python3.10/site-packages/accelerate/commands/launch.py", line 628, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/home/davi/AI/kohya_ss/venv/bin/python', './train_network.py', '--v2', '--v_parameterization', '--pretrained_model_name_or_path=/home/davi/AI/ComfyUI/models/checkpoints/v2-1_512-ema-pruned.safetensors', '--train_data_dir=/home/davi/Downloads/test/images', '--resolution=512,512', '--output_dir=/home/davi/Downloads/test/model', '--logging_dir=/home/davi/Downloads/test/log', '--network_alpha=128', '--save_model_as=safetensors', '--network_module=networks.lora', '--text_encoder_lr=5e-05', '--unet_lr=0.0001', '--network_dim=128', '--output_name=Addams', '--lr_scheduler_num_cycles=1', '--no_half_vae', '--learning_rate=0.0001', '--lr_scheduler=constant', '--train_batch_size=1', '--max_train_steps=300', '--save_every_n_epochs=1', '--mixed_precision=bf16', '--save_precision=bf16', '--seed=1234', '--caption_extension=.txt', '--cache_latents', '--optimizer_type=AdamW8bit', '--max_grad_norm=1', '--max_data_loader_n_workers=1', '--clip_skip=2', '--bucket_reso_steps=64', '--mem_eff_attn', '--gradient_checkpointing', '--xformers', '--bucket_no_upscale', '--noise_offset=0.0']' returned non-zero exit status 1.
21:46:43-686778 INFO     Start training LoRA Standard ...                                                                                                     
21:46:43-689000 INFO     Checking for duplicate image filenames in training data directory...                                                                 
21:46:43-691933 INFO     Valid image folder names found in: /home/davi/Downloads/test/images                                                                  
21:46:43-694337 INFO     Folder 30_dindjarin: 10 images found                                                                                                 
21:46:43-695401 INFO     Folder 30_dindjarin: 300 steps                                                                                                       
21:46:43-696357 INFO     Total steps: 300                                                                                                                     
21:46:43-697344 INFO     Train batch size: 1                                                                                                                  
21:46:43-698332 INFO     Gradient accumulation steps: 1                                                                                                       
21:46:43-699274 INFO     Epoch: 1                                                                                                                             
21:46:43-700173 INFO     Regulatization factor: 1                                                                                                             
21:46:43-701170 INFO     max_train_steps (300 / 1 / 1 * 1 * 1) = 300                                                                                          
21:46:43-702319 INFO     stop_text_encoder_training = 0                                                                                                       
21:46:43-703448 INFO     lr_warmup_steps = 0                                                                                                                  
21:46:43-704477 INFO     Saving training config to /home/davi/Downloads/test/model/Addams_20240108-214643.json...                                             
21:46:43-705975 INFO     accelerate launch --num_cpu_threads_per_process=2 "./train_network.py" --v2 --v_parameterization                                     
                         --pretrained_model_name_or_path="/home/davi/AI/ComfyUI/models/checkpoints/v2-1_512-ema-pruned.safetensors"                           
                         --train_data_dir="/home/davi/Downloads/test/images" --resolution="512,512" --output_dir="/home/davi/Downloads/test/model"            
                         --logging_dir="/home/davi/Downloads/test/log" --network_alpha="128" --save_model_as=safetensors --network_module=networks.lora       
                         --text_encoder_lr=5e-05 --unet_lr=0.0001 --network_dim=128 --output_name="Addams" --lr_scheduler_num_cycles="1" --no_half_vae        
                         --learning_rate="0.0001" --lr_scheduler="constant" --train_batch_size="1" --max_train_steps="300" --save_every_n_epochs="1"          
                         --mixed_precision="fp16" --save_precision="fp16" --seed="1234" --caption_extension=".txt" --cache_latents                            
                         --optimizer_type="AdamW8bit" --max_grad_norm="1" --max_data_loader_n_workers="1" --clip_skip=2 --bucket_reso_steps=64 --mem_eff_attn 
                         --gradient_checkpointing --xformers --bucket_no_upscale --noise_offset=0.0                                                           
2024-01-08 21:46:48.283696: E tensorflow/compiler/xla/stream_executor/cuda/cuda_dnn.cc:9342] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-01-08 21:46:48.283731: E tensorflow/compiler/xla/stream_executor/cuda/cuda_fft.cc:609] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-01-08 21:46:48.283751: E tensorflow/compiler/xla/stream_executor/cuda/cuda_blas.cc:1518] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-01-08 21:46:48.289898: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-01-08 21:46:49.118080: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
v2 with clip_skip will be unexpected / v2でclip_skipを使用することは想定されていません
prepare tokenizer
Using DreamBooth method.
prepare images.
found directory /home/davi/Downloads/test/images/30_dindjarin contains 10 image files
300 train images with repeating.
0 reg images.
no regularization images / 正則化画像が見つかりませんでした
[Dataset 0]
  batch_size: 1
  resolution: (512, 512)
  enable_bucket: False

  [Subset 0 of Dataset 0]
    image_dir: "/home/davi/Downloads/test/images/30_dindjarin"
    image_count: 10
    num_repeats: 30
    shuffle_caption: False
    keep_tokens: 0
    keep_tokens_separator: 
    caption_dropout_rate: 0.0
    caption_dropout_every_n_epoches: 0
    caption_tag_dropout_rate: 0.0
    caption_prefix: None
    caption_suffix: None
    color_aug: False
    flip_aug: False
    face_crop_aug_range: None
    random_crop: False
    token_warmup_min: 1,
    token_warmup_step: 0,
    is_reg: False
    class_tokens: dindjarin
    caption_extension: .txt


[Dataset 0]
loading image sizes.
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 10/10 [00:00<00:00, 2596.45it/s]
prepare dataset
preparing accelerator
loading model for process 0/1
load StableDiffusion checkpoint: /home/davi/AI/ComfyUI/models/checkpoints/v2-1_512-ema-pruned.safetensors
UNet2DConditionModel: 64, [5, 10, 20, 20], 1024, False, False
loading u-net: <All keys matched successfully>
loading vae: <All keys matched successfully>
loading text encoder: <All keys matched successfully>
Enable memory efficient attention for U-Net
import network module: networks.lora
[Dataset 0]
caching latents.
checking cache validity...
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 10/10 [00:00<00:00, 301748.49it/s]
caching latents...
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 10/10 [00:03<00:00,  2.54it/s]
create LoRA network. base dim (rank): 128, alpha: 128.0
neuron dropout: p=None, rank dropout: p=None, module dropout: p=None
create LoRA for Text Encoder:
create LoRA for Text Encoder: 138 modules.
create LoRA for U-Net: 192 modules.
enable LoRA for text encoder
enable LoRA for U-Net
CrossAttnDownBlock2D False -> True
CrossAttnDownBlock2D False -> True
CrossAttnDownBlock2D False -> True
DownBlock2D False -> True
UNetMidBlock2DCrossAttn False -> True
UpBlock2D False -> True
CrossAttnUpBlock2D False -> True
CrossAttnUpBlock2D False -> True
CrossAttnUpBlock2D False -> True
prepare optimizer, data loader etc.
False

===================================BUG REPORT===================================
/home/davi/AI/kohya_ss/venv/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py:166: UserWarning: Welcome to bitsandbytes. For bug reports, please run

python -m bitsandbytes


  warn(msg)
================================================================================
/home/davi/AI/kohya_ss/venv/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py:166: UserWarning: /home/davi/anaconda3/envs/kohya_ss did not contain ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] as expected! Searching further paths...
  warn(msg)
The following directories listed in your path were found to be non-existent: {PosixPath('/home/davi/AI/kohya_ss/venv/lib/python3.10/site-packages/cv2/../../lib64')}
/home/davi/AI/kohya_ss/venv/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py:166: UserWarning: /home/davi/AI/kohya_ss/venv/lib/python3.10/site-packages/cv2/../../lib64:/usr/local/cuda/lib64 did not contain ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] as expected! Searching further paths...
  warn(msg)
The following directories listed in your path were found to be non-existent: {PosixPath('/usr/share/gconf/zorin.mandatory.path')}
The following directories listed in your path were found to be non-existent: {PosixPath('https'), PosixPath('//api.sdkman.io/2')}
The following directories listed in your path were found to be non-existent: {PosixPath('/usr/share/gconf/zorin.default.path')}
The following directories listed in your path were found to be non-existent: {PosixPath('@/tmp/.ICE-unix/1459,unix/davi'), PosixPath('local/davi')}
The following directories listed in your path were found to be non-existent: {PosixPath('/org/gnome/Terminal/screen/bdebe05e_a666_4609_af42_e8275353294c')}
The following directories listed in your path were found to be non-existent: {PosixPath('0'), PosixPath('1')}
The following directories listed in your path were found to be non-existent: {PosixPath('/etc/xdg/xdg-zorin')}
CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching in backup paths...
DEBUG: Possible options found for libcudart.so: {PosixPath('/usr/local/cuda/lib64/libcudart.so')}
CUDA SETUP: PyTorch settings found: CUDA_VERSION=118, Highest Compute Capability: 7.5.
CUDA SETUP: To manually override the PyTorch CUDA version please see:https://github.com/TimDettmers/bitsandbytes/blob/main/how_to_use_nonpytorch_cuda.md
CUDA SETUP: Loading binary /home/davi/AI/kohya_ss/venv/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda118.so...
libcusparse.so.11: cannot open shared object file: No such file or directory
CUDA SETUP: Something unexpected happened. Please compile from source:
git clone https://github.com/TimDettmers/bitsandbytes.git
cd bitsandbytes
CUDA_VERSION=118 make cuda11x
python setup.py install
Traceback (most recent call last):
  File "/home/davi/AI/kohya_ss/./train_network.py", line 996, in <module>
    trainer.train(args)
  File "/home/davi/AI/kohya_ss/./train_network.py", line 348, in train
    optimizer_name, optimizer_args, optimizer = train_util.get_optimizer(args, trainable_params)
  File "/home/davi/AI/kohya_ss/library/train_util.py", line 3480, in get_optimizer
    import bitsandbytes as bnb
  File "/home/davi/AI/kohya_ss/venv/lib/python3.10/site-packages/bitsandbytes/__init__.py", line 6, in <module>
    from . import cuda_setup, utils, research
  File "/home/davi/AI/kohya_ss/venv/lib/python3.10/site-packages/bitsandbytes/research/__init__.py", line 1, in <module>
    from . import nn
  File "/home/davi/AI/kohya_ss/venv/lib/python3.10/site-packages/bitsandbytes/research/nn/__init__.py", line 1, in <module>
    from .modules import LinearFP8Mixed, LinearFP8Global
  File "/home/davi/AI/kohya_ss/venv/lib/python3.10/site-packages/bitsandbytes/research/nn/modules.py", line 8, in <module>
    from bitsandbytes.optim import GlobalOptimManager
  File "/home/davi/AI/kohya_ss/venv/lib/python3.10/site-packages/bitsandbytes/optim/__init__.py", line 6, in <module>
    from bitsandbytes.cextension import COMPILED_WITH_CUDA
  File "/home/davi/AI/kohya_ss/venv/lib/python3.10/site-packages/bitsandbytes/cextension.py", line 20, in <module>
    raise RuntimeError('''
RuntimeError: 
        CUDA Setup failed despite GPU being available. Please run the following command to get more information:

        python -m bitsandbytes

        Inspect the output of the command and see if you can locate CUDA libraries. You might need to add them
        to your LD_LIBRARY_PATH. If you suspect a bug, please take the information from python -m bitsandbytes
        and open an issue at: https://github.com/TimDettmers/bitsandbytes/issues
Traceback (most recent call last):
  File "/home/davi/AI/kohya_ss/venv/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/home/davi/AI/kohya_ss/venv/lib/python3.10/site-packages/accelerate/commands/accelerate_cli.py", line 47, in main
    args.func(args)
  File "/home/davi/AI/kohya_ss/venv/lib/python3.10/site-packages/accelerate/commands/launch.py", line 986, in launch_command
    simple_launcher(args)
  File "/home/davi/AI/kohya_ss/venv/lib/python3.10/site-packages/accelerate/commands/launch.py", line 628, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/home/davi/AI/kohya_ss/venv/bin/python', './train_network.py', '--v2', '--v_parameterization', '--pretrained_model_name_or_path=/home/davi/AI/ComfyUI/models/checkpoints/v2-1_512-ema-pruned.safetensors', '--train_data_dir=/home/davi/Downloads/test/images', '--resolution=512,512', '--output_dir=/home/davi/Downloads/test/model', '--logging_dir=/home/davi/Downloads/test/log', '--network_alpha=128', '--save_model_as=safetensors', '--network_module=networks.lora', '--text_encoder_lr=5e-05', '--unet_lr=0.0001', '--network_dim=128', '--output_name=Addams', '--lr_scheduler_num_cycles=1', '--no_half_vae', '--learning_rate=0.0001', '--lr_scheduler=constant', '--train_batch_size=1', '--max_train_steps=300', '--save_every_n_epochs=1', '--mixed_precision=fp16', '--save_precision=fp16', '--seed=1234', '--caption_extension=.txt', '--cache_latents', '--optimizer_type=AdamW8bit', '--max_grad_norm=1', '--max_data_loader_n_workers=1', '--clip_skip=2', '--bucket_reso_steps=64', '--mem_eff_attn', '--gradient_checkpointing', '--xformers', '--bucket_no_upscale', '--noise_offset=0.0']' returned non-zero exit status 1.
```

OS:
![image](https://github.com/bmaltais/kohya_ss/assets/38295327/c7d9d21a-b1de-4ae9-8e55-a9f94ed81250)

Conda: 23.11.0
Python: 3.10.6
pip: 23.3.1
Settings: [LoraLowVRAMSettings.json](https://github.com/bmaltais/kohya_ss/files/13867616/LoraLowVRAMSettings.json)
CUDA: 12.3 (the beginning is saying 11.8, but it looks like that the Pytorch from requirements_linux.txt is doing that)

If you need more details, just let me know

**Comment by WizardlyBump17** [comment]
Closing issue because it may be my mistake

**Comment by phucbienvan** [comment]
I also encountered a similar error. How did you fix it?

**Comment by WizardlyBump17** [comment]
> I also encountered a similar error. How did you fix it?

It has been some time since I faced that error. If I remember correctly, I simply installed the dependencies manually

**Comment by phucbienvan** [comment]
Yes, I downgraded the CUDA version from 12.6 to 11.8 and reset the CUDA environment variables, and now it works.
