### ISSUE TITLE
GPU no longer available after update [Intel IPEX]

### ISSUE THREAD

**Issue by bvhari** [bmaltais/kohya_ss#2261]
I get this warning when I run ./gui.sh --use-ipex:
`WARNING  Torch reports GPU not available`

I already tried running ./setup.sh --use-ipex

If I manually activate the venv, open python, and import intel_extension_for_pytorch, it loads without any issue and my GPU is visible in torch.xpu.get_device_properties(0)

Everything was working fine before the recent update which installed a different version of intel_extension_for_pytorch.

If I ignore the warning and run a lora training anyway, I get this error:
```
Traceback (most recent call last):
  File "kohya_ss/venv/bin/accelerate", line 5, in <module>
    from accelerate.commands.accelerate_cli import main
  File "kohya_ss/venv/lib/python3.10/site-packages/accelerate/commands/accelerate_cli.py", line 23, in <module>
    from accelerate.commands.test import test_command_parser
  File "kohya_ss/venv/lib/python3.10/site-packages/accelerate/commands/test.py", line 20, in <module>
    from accelerate.test_utils import execute_subprocess_async
  File "kohya_ss/venv/lib/python3.10/site-packages/accelerate/test_utils/__init__.py", line 23, in <module>
    from .scripts import test_script, test_sync, test_ops  # isort: skip
  File "kohya_ss/venv/lib/python3.10/site-packages/accelerate/test_utils/scripts/test_script.py", line 45, in <module>
    if is_xpu_available():
  File "kohya_ss/venv/lib/python3.10/site-packages/accelerate/utils/imports.py", line 290, in is_xpu_available
    import intel_extension_for_pytorch  # noqa: F401
  File "kohya_ss/venv/lib/python3.10/site-packages/intel_extension_for_pytorch/__init__.py", line 94, in <module>
    from .utils._proxy_module import *
  File "kohya_ss/venv/lib/python3.10/site-packages/intel_extension_for_pytorch/utils/_proxy_module.py", line 2, in <module>
    import intel_extension_for_pytorch._C
ImportError: kohya_ss/venv/lib/libmkl_sycl_data_fitting.so.4: undefined symbol: _ZN4sycl3_V17handler19getMaxWorkGroups_v2Ev
```

Specs: Intel ARC 770 LE, Windows 10, WSL2, Ubuntu 22.04.3, Python 3.10.12

**Comment by bmaltais** [comment]
I can't test and fix this as I don't have this GPU. Someone with such a system will need to figure out the solution...

**Comment by Disty0** [comment]
Remove the venv folder. This was noted in the PP notes: https://github.com/bmaltais/kohya_ss/pull/2181

**Comment by bvhari** [comment]
@Disty0 Tried on a fresh WSL2 setup and it is working now
Thanks!
