### ISSUE TITLE
error on runpod

### ISSUE THREAD

**Issue by lawliet198t** [bmaltais/kohya_ss#2378]
07:57:37-223336 INFO     Kohya_ss GUI version: v24.0.6                                                                                                                                 
07:57:37-285769 INFO     Submodule initialized and updated.                                                                                                                            
07:57:37-287723 INFO     nVidia toolkit detected                                                                                                                                       
07:57:38-846794 INFO     Torch 2.1.2+cu118                                                                                                                                             
/workspace/all_data/kohya_ss/venv/lib/python3.10/site-packages/torch/cuda/__init__.py:138: UserWarning: CUDA initialization: CUDA driver initialization failed, you might not have a CUDA gpu. (Triggered internally at ../c10/cuda/CUDAFunctions.cpp:108.)
  return torch._C._cuda_getDeviceCount() > 0
07:57:38-916240 WARNING  Torch reports GPU not available                                                                                                                               
07:57:38-921048 INFO     Python version is 3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0]                                                                                          
07:57:38-922333 INFO     Verifying modules installation status from /workspace/all_data/kohya_ss/requirements_runpod.txt...                                                            
07:57:38-925551 INFO     Verifying modules installation status from requirements.txt...                                                                                                
Traceback (most recent call last):
  File "/workspace/all_data/kohya_ss/kohya_gui.py", line 4, in <module>
    from kohya_gui.class_gui_config import KohyaSSGUIConfig
  File "/workspace/all_data/kohya_ss/kohya_gui/class_gui_config.py", line 2, in <module>
    from .common_gui import scriptdir
  File "/workspace/all_data/kohya_ss/kohya_gui/common_gui.py", line 1, in <module>
    from tkinter import filedialog, Tk
ModuleNotFoundError: No module named 'tkinter'
root@bab134a9fd42:/workspace/all_data/kohya_ss#

**Comment by bmaltais** [comment]
Are you running it in headless mode with: `./gui.sh --headless`

**Comment by lawliet198t** [comment]
yup

**Comment by bmaltais** [comment]
I pushed a possible fix to the dev branch... give it a try.

**Comment by lawliet198t** [comment]
k wait

**Comment by lawliet198t** [comment]
the gpu problem is solved but tkinter one still there is there any possible fixes

**Comment by bmaltais** [comment]
What is the error after I pushed this update to dev. I has to be adifferent one now. Can'y out install tkinter in runpod?

**Comment by lawliet198t** [comment]
yup i tried to install python again but every time it showed the same error tried almost everything but didnt work thats problem i even tried to install tkinter but didnt work

**Comment by lawliet198t** [comment]
so is there anything i can do ?

**Comment by bmaltais** [comment]
Have you tried to reach out to @ashleykleynhans from https://github.com/bmaltais/kohya_ss/issues/2308

He as a running solution on runpod...

**Comment by lawliet198t** [comment]
k

**Comment by mattatattattat** [comment]
How did you solve WARNING: Torch reports GPU not available? I have the same issue on Mac M3

**Comment by ashleykleynhans** [comment]
> How did you solve WARNING: Torch reports GPU not available? I have the same issue on Mac M3

Are you using RunPod?  if not then log a new issue, its not related to this issue, this issue is specifically for RunPod.
