### ISSUE TITLE
Khoya for 5090

### ISSUE THREAD

**Issue by McLaniel** [bmaltais/kohya_ss#3159]
Hello! I've juste experience this error on khoya VOC:

e:\kohya_ss\venv\lib\site-packages\torch\cuda\__init__.py:235: UserWarning: 
NVIDIA GeForce RTX 5090 with CUDA capability sm_120 is not compatible with the current PyTorch installation.
The current PyTorch install supports CUDA capabilities sm_50 sm_60 sm_61 sm_70 sm_75 sm_80 sm_86 sm_90.
If you want to use the NVIDIA GeForce RTX 5090 GPU with PyTorch, please check the instructions at https://pytorch.org/get-started/locally/

I have a new 5090, and was wondering when do you think khoya would be available for it?

Thanks in advance :)

**Comment by TheInfinites** [comment]
There is a fix. Refer to this [comment](https://github.com/bmaltais/kohya_ss/issues/3096#issuecomment-2730229439)

You will find that the link for sd3-flux doesn't exist. I think they simply merged it or something. 
I ended up downloading the [Master](https://github.com/[bmaltais/kohya_ss](https://github.com/bmaltais/kohya_ss)) Branch. Also this version of the [sd-scripts](https://github.com/kohya-ss/sd-scripts/tree/8ebe858f896340d698f03fc33d99ca010131320a). 
Then I followed along with the rest of the steps.  
It worked for me.

**Comment by Specthram** [comment]
I don't understand fully how it works but I guess you are on windows looking at your "e:/".
There is a file named "requirements_pytorch_windows.txt" at the project root.
in v25.0.3 it's 
torch==2.5.0+cu124
torchvision==0.20.0+cu124
xformers==0.0.28.post2

but as far i know, to support new rtx 50, at least cuda 12.8 is needed.
it's take the form "+cu128" of what I seen.
torch 2.6.0+cu128 is needed
xformers 0.0.29.post3 is need

i don't know for torchvision.

in the release notes, v25.0.0 is supposed to be on cuda 12, but maybe it's on <12.8
maybe the dependancies are not ready ? I don't know

**Comment by lixida123** [comment]
> I don't understand fully how it works but I guess you are on windows looking at your "e:/". There is a file named "requirements_pytorch_windows.txt" at the project root. in v25.0.3 it's torch==2.5.0+cu124 torchvision==0.20.0+cu124 xformers==0.0.28.post2
> 
> but as far i know, to support new rtx 50, at least cuda 12.8 is needed. it's take the form "+cu128" of what I seen. torch 2.6.0+cu128 at least is needed
> 
> i don't know for torchvision and xformers.
> 
> in the release notes, v25.0.0 is supposed to be on cuda 12, but maybe it's on <12.8 (12.4 looking at the dependancies) maybe the 12.8 dependancies are not ready ? I don't know



Yes, this might require you to comment out torch==2.5.0+cu124
Torchvision = = 0.20.0 + cu124
xformers==0.0.28.post2 uses the dedicated Torch version of the 50 series instead of relying on the old version of Torch in the file
