### ISSUE TITLE
CUDA error: no kernel image is available for execution on the device (Blackwell GPU)

### ISSUE THREAD

**Issue by Beunhaaz** [bmaltais/kohya_ss#3238]
Hello,

I should start by stating that I'm new to the scene and wanted to experiment with some LoRas.
I've tried installing Koyha with pinokio, intalling manually, and via [this](https://github.com/bmaltais/kohya_ss/discussions/3218) guide, and they all result in the same error:
```
10:04:53-864045 INFO     Start training Dreambooth...
10:04:53-866045 INFO     Validating lr scheduler arguments...
10:04:53-866045 INFO     Validating optimizer arguments...
10:04:53-867045 INFO     Validating C:/Users/royro/Documents/Koyha/datasets/hier\log existence and writability...
                         SUCCESS
10:04:53-868135 INFO     Validating C:/Users/royro/Documents/Koyha/datasets/hier\model existence and writability...
                         SUCCESS
10:04:53-868135 INFO     Validating stabilityai/stable-diffusion-xl-base-1.0 existence... SUCCESS
10:04:53-869134 INFO     Validating C:/Users/royro/Documents/Koyha/datasets/hier\img existence... SUCCESS
10:04:53-870071 INFO     Folder 5_test123 testing123: 5 repeats found
10:04:53-871076 INFO     Folder 5_test123 testing123: 47 images found
10:04:53-871076 INFO     Folder 5_test123 testing123: 47 * 5 = 235 steps
10:04:53-872076 INFO     Regularization factor: 1
10:04:53-872076 INFO     Total steps: 235
10:04:53-873075 INFO     Train batch size: 1
10:04:53-873075 INFO     Gradient accumulation steps: 1
10:04:53-874074 INFO     Epoch: 10
10:04:53-874074 INFO     Max train steps: 1600
10:04:53-874074 INFO     lr_warmup_steps = 0.1
10:04:53-876076 INFO     Saving training config to
                         C:/Users/royro/Documents/Koyha/datasets/hier\model\test123_20250518-100453.json...
10:04:53-877078 INFO     Executing command: C:\Users\royro\Documents\Koyha\kohya_ss\.venv\Scripts\accelerate.EXE launch
                         --dynamo_backend no --dynamo_mode default --mixed_precision fp16 --num_processes 1
                         --num_machines 1 --num_cpu_threads_per_process 2
                         C:/Users/royro/Documents/Koyha/kohya_ss/sd-scripts/sdxl_train.py --config_file
                         C:/Users/royro/Documents/Koyha/datasets/hier\model/config_dreambooth-20250518-100453.toml
C:\Users\royro\Documents\Koyha\kohya_ss\.venv\lib\site-packages\torch\cuda\__init__.py:235: UserWarning:
NVIDIA GeForce RTX 5070 Ti with CUDA capability sm_120 is not compatible with the current PyTorch installation.
The current PyTorch install supports CUDA capabilities sm_50 sm_60 sm_61 sm_70 sm_75 sm_80 sm_86 sm_90.
If you want to use the NVIDIA GeForce RTX 5070 Ti GPU with PyTorch, please check the instructions at https://pytorch.org/get-started/locally/

  warnings.warn(
C:\Users\royro\Documents\Koyha\kohya_ss\.venv\lib\site-packages\torch\cuda\__init__.py:235: UserWarning:
NVIDIA GeForce RTX 5070 Ti with CUDA capability sm_120 is not compatible with the current PyTorch installation.
The current PyTorch install supports CUDA capabilities sm_50 sm_60 sm_61 sm_70 sm_75 sm_80 sm_86 sm_90.
If you want to use the NVIDIA GeForce RTX 5070 Ti GPU with PyTorch, please check the instructions at https://pytorch.org/get-started/locally/

  warnings.warn(
2025-05-18 10:04:58 INFO     Loading settings from                                                    train_util.py:4648
                             C:/Users/royro/Documents/Koyha/datasets/hier\model/config_dreambooth-202
                             50518-100453.toml...
                    WARNING  clip_skip will be unexpected / SDXL学習ではclip_skipは動作しません   sdxl_train_util.py:349
C:\Users\royro\Documents\Koyha\kohya_ss\.venv\lib\site-packages\transformers\tokenization_utils_base.py:1601: FutureWarning: `clean_up_tokenization_spaces` was not set. It will be set to `True` by default. This behavior will be depracted in transformers v4.45, and will be then set to `False` by default. For more details check this issue: https://github.com/huggingface/transformers/issues/31884
  warnings.warn(
2025-05-18 10:04:59 INFO     Using DreamBooth method.                                                  sdxl_train.py:153
                    INFO     prepare images.                                                          train_util.py:2069
                    INFO     get image size from name of cache files                                  train_util.py:1962
100%|██████████████████████████████████████████████████████████████████████████████████████████| 47/47 [00:00<?, ?it/s]
                    INFO     set image size from cache files: 0/47                                    train_util.py:1992
                    INFO     found directory                                                          train_util.py:2016
                             C:\Users\royro\Documents\Koyha\datasets\hier\img\5_test123 testing123
                             contains 47 image files
read caption: 100%|█████████████████████████████████████████████████████████████████| 47/47 [00:00<00:00, 23507.31it/s]
                    INFO     235 train images with repeats.                                           train_util.py:2113
                    INFO     0 reg images with repeats.                                               train_util.py:2117
                    WARNING  no regularization images / 正則化画像が見つかりませんでした              train_util.py:2122
                    INFO     [Dataset 0]                                                              config_util.py:580
                               batch_size: 1
                               resolution: (1024, 1024)
                               resize_interpolation: None
                               enable_bucket: True
                               min_bucket_reso: 256
                               max_bucket_reso: 2048
                               bucket_reso_steps: 64
                               bucket_no_upscale: True

                               [Subset 0 of Dataset 0]
                                 image_dir:
                             "C:\Users\royro\Documents\Koyha\datasets\hier\img\5_test123 testing123"
                                 image_count: 47
                                 num_repeats: 5
                                 shuffle_caption: False
                                 keep_tokens: 0
                                 caption_dropout_rate: 0
                                 caption_dropout_every_n_epochs: 0
                                 caption_tag_dropout_rate: 0.0
                                 caption_prefix: None
                                 caption_suffix: None
                                 color_aug: False
                                 flip_aug: False
                                 face_crop_aug_range: None
                                 random_crop: False
                                 token_warmup_min: 1,
                                 token_warmup_step: 0,
                                 alpha_mask: False
                                 resize_interpolation: None
                                 custom_attributes: {}
                                 is_reg: False
                                 class_tokens: test123 testing123
                                 caption_extension: .txt


                    INFO     [Prepare dataset 0]                                                      config_util.py:592
                    INFO     loading image sizes.                                                      train_util.py:987
100%|███████████████████████████████████████████████████████████████████████████████| 47/47 [00:00<00:00, 47025.83it/s]
                    INFO     make buckets                                                             train_util.py:1010
                    WARNING  min_bucket_reso and max_bucket_reso are ignored if bucket_no_upscale is  train_util.py:1027
                             set, because bucket reso is defined by image size automatically /
                             bucket_no_upscaleが指定された場合は、bucketの解像度は画像サイズから自動
                             計算されるため、min_bucket_resoとmax_bucket_resoは無視されます
                    INFO     number of images (including repeats) /                                   train_util.py:1056
                             各bucketの画像枚数（繰り返し回数を含む）
                    INFO     bucket 0: resolution (640, 1024), count: 5                               train_util.py:1061
                    INFO     bucket 1: resolution (704, 896), count: 5                                train_util.py:1061
                    INFO     bucket 2: resolution (768, 1088), count: 5                               train_util.py:1061
                    INFO     bucket 3: resolution (832, 1088), count: 20                              train_util.py:1061
                    INFO     bucket 4: resolution (832, 1216), count: 15                              train_util.py:1061
                    INFO     bucket 5: resolution (896, 896), count: 10                               train_util.py:1061
                    INFO     bucket 6: resolution (960, 960), count: 5                                train_util.py:1061
                    INFO     bucket 7: resolution (1024, 896), count: 5                               train_util.py:1061
                    INFO     bucket 8: resolution (1024, 1024), count: 15                             train_util.py:1061
                    INFO     bucket 9: resolution (1088, 832), count: 5                               train_util.py:1061
                    INFO     bucket 10: resolution (1088, 896), count: 5                              train_util.py:1061
                    INFO     bucket 11: resolution (1152, 576), count: 5                              train_util.py:1061
                    INFO     bucket 12: resolution (1152, 640), count: 15                             train_util.py:1061
                    INFO     bucket 13: resolution (1152, 768), count: 10                             train_util.py:1061
                    INFO     bucket 14: resolution (1216, 704), count: 10                             train_util.py:1061
                    INFO     bucket 15: resolution (1216, 832), count: 30                             train_util.py:1061
                    INFO     bucket 16: resolution (1280, 704), count: 30                             train_util.py:1061
                    INFO     bucket 17: resolution (1280, 768), count: 15                             train_util.py:1061
                    INFO     bucket 18: resolution (1344, 704), count: 5                              train_util.py:1061
                    INFO     bucket 19: resolution (1344, 768), count: 15                             train_util.py:1061
                    INFO     bucket 20: resolution (1408, 640), count: 5                              train_util.py:1061
                    INFO     mean ar error (without repeats): 0.025941414257308535                    train_util.py:1066
                    INFO     prepare accelerator                                                       sdxl_train.py:211
C:\Users\royro\Documents\Koyha\kohya_ss\.venv\lib\site-packages\accelerate\accelerator.py:488: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = torch.cuda.amp.GradScaler(**kwargs)
accelerator device: cuda
                    INFO     loading model for process 0/1                                         sdxl_train_util.py:32
                    INFO     load Diffusers pretrained models:                                     sdxl_train_util.py:87
                             stabilityai/stable-diffusion-xl-base-1.0, variant=fp16
Loading pipeline components...: 100%|████████████████████████████████████████████████████| 6/6 [00:02<00:00,  2.38it/s]
2025-05-18 10:05:02 INFO     U-Net converted to original U-Net                                    sdxl_train_util.py:123
Disable Diffusers' xformers
                    INFO     Enable xformers for U-Net                                                train_util.py:3346
Traceback (most recent call last):
  File "C:\Users\royro\Documents\Koyha\kohya_ss\sd-scripts\sdxl_train.py", line 951, in <module>
    train(args)
  File "C:\Users\royro\Documents\Koyha\kohya_ss\sd-scripts\sdxl_train.py", line 268, in train
    vae.set_use_memory_efficient_attention_xformers(args.xformers)
  File "C:\Users\royro\Documents\Koyha\kohya_ss\.venv\lib\site-packages\diffusers\models\modeling_utils.py", line 273, in set_use_memory_efficient_attention_xformers
    fn_recursive_set_mem_eff(module)
  File "C:\Users\royro\Documents\Koyha\kohya_ss\.venv\lib\site-packages\diffusers\models\modeling_utils.py", line 269, in fn_recursive_set_mem_eff
    fn_recursive_set_mem_eff(child)
  File "C:\Users\royro\Documents\Koyha\kohya_ss\.venv\lib\site-packages\diffusers\models\modeling_utils.py", line 269, in fn_recursive_set_mem_eff
    fn_recursive_set_mem_eff(child)
  File "C:\Users\royro\Documents\Koyha\kohya_ss\.venv\lib\site-packages\diffusers\models\modeling_utils.py", line 269, in fn_recursive_set_mem_eff
    fn_recursive_set_mem_eff(child)
  File "C:\Users\royro\Documents\Koyha\kohya_ss\.venv\lib\site-packages\diffusers\models\modeling_utils.py", line 266, in fn_recursive_set_mem_eff
    module.set_use_memory_efficient_attention_xformers(valid, attention_op)
  File "C:\Users\royro\Documents\Koyha\kohya_ss\.venv\lib\site-packages\diffusers\models\attention_processor.py", line 408, in set_use_memory_efficient_attention_xformers
    raise e
  File "C:\Users\royro\Documents\Koyha\kohya_ss\.venv\lib\site-packages\diffusers\models\attention_processor.py", line 403, in set_use_memory_efficient_attention_xformers
    torch.randn((1, 2, 40), device="cuda"),
RuntimeError: CUDA error: no kernel image is available for execution on the device
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

Traceback (most recent call last):
  File "C:\Users\royro\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\royro\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\royro\Documents\Koyha\kohya_ss\.venv\Scripts\accelerate.EXE\__main__.py", line 10, in <module>
    sys.exit(main())
  File "C:\Users\royro\Documents\Koyha\kohya_ss\.venv\lib\site-packages\accelerate\commands\accelerate_cli.py", line 48, in main
    args.func(args)
  File "C:\Users\royro\Documents\Koyha\kohya_ss\.venv\lib\site-packages\accelerate\commands\launch.py", line 1106, in launch_command
    simple_launcher(args)
  File "C:\Users\royro\Documents\Koyha\kohya_ss\.venv\lib\site-packages\accelerate\commands\launch.py", line 704, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['C:\\Users\\royro\\Documents\\Koyha\\kohya_ss\\.venv\\Scripts\\python.exe', 'C:/Users/royro/Documents/Koyha/kohya_ss/sd-scripts/sdxl_train.py', '--config_file', 'C:/Users/royro/Documents/Koyha/datasets/hier\\model/config_dreambooth-20250518-100453.toml']' returned non-zero exit status 1.
10:05:04-140140 INFO     Training has ended.
````

Here's some info on what I'm running atm:
```
C:\Users\royro>nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2025 NVIDIA Corporation
Built on Wed_Jan_15_19:38:46_Pacific_Standard_Time_2025
Cuda compilation tools, release 12.8, V12.8.61
Build cuda_12.8.r12.8/compiler.35404655_0

>>> print(torch.__version__)
2.8.0.dev20250516+cu128
>>> print(torch.cuda.is_available())
True
>>> print(torch.version.cuda)
12.8

C:\Users\royro>nvidia-smi
Sun May 18 14:02:09 2025
| NVIDIA-SMI 576.40                 Driver Version: 576.40         CUDA Version: 12.9     |
|   0  NVIDIA GeForce RTX 5070 Ti   WDDM  |   00000000:01:00.0 Off |             N/A |
|  0%   47C    P8             21W /  300W |    7010MiB /  16303MiB |      0%      Default |
```

It seems to be a mismatch between CUDA and Pytorch somewhere, but I can't seem to figure out how to fix this.
Any help would be greatly appreciated.

**Comment by Beunhaaz** [comment]
After trying almost every possible way of installing koyha, [this](https://github.com/bmaltais/kohya_ss/issues/3096#issuecomment-2886401109) is the one that works for me.
