### ISSUE TITLE
Multi GPU training is not working, GPU mapping is incorrect

### ISSUE THREAD

**Issue by NeoLoger** [bmaltais/kohya_ss#3260]
I have 2 GPUs RTX 3060 Ti and RTX 3080
If I'm running the training on a single GPU on the same host its working fine.
But when I enable the multi GPU, and this is the only thing that I change all the rest of the configuration stays the same I'm getting an error.
```
using GPU 1 as device used by this process is currently unknown. This can potentially cause a hang if this rank to GPU mapping is incorrect. You can pecify device_id in init_process_group() to force use of a particular device.


using GPU 0 as device used by this process is currently unknown. This can potentially cause a hang if this rank to GPU mapping is incorrect. You can pecify device_id in init_process_group() to force use of a particular device.
```

I have tried a fresh install, I tried to run it run kohya_ss from docker and from wsl, I keep getting the same issue.

This is my `accelerate env` output
```
Copy-and-paste the text below in your GitHub issue

- `Accelerate` version: 1.7.0
- Platform: Linux-6.6.87.1-microsoft-standard-WSL2-x86_64-with-glibc2.35
- `accelerate` bash location: /mnt/c/tools/AI/kohya_ss/venv/bin/accelerate
- Python version: 3.10.12
- Numpy version: 1.26.4
- PyTorch version: 2.7.0+cu128
- PyTorch accelerator: CUDA
- System RAM: 15.59 GB
- GPU type: NVIDIA GeForce RTX 3080
- `Accelerate` default config:
        - compute_environment: LOCAL_MACHINE
        - distributed_type: MULTI_GPU
        - mixed_precision: fp16
        - use_cpu: False
        - debug: False
        - num_processes: 2
        - machine_rank: 0
        - num_machines: 1
        - gpu_ids: all
        - rdzv_backend: static
        - same_network: True
        - main_training_function: main
        - enable_cpu_affinity: True
        - downcast_bf16: no
        - tpu_use_cluster: False
        - tpu_use_sudo: False
        - tpu_env: []
```

nvidia-smi output
```
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 575.57.04              Driver Version: 576.52         CUDA Version: 12.9     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 3080        On  |   00000000:01:00.0 Off |                  N/A |
|  0%   33C    P8              9W /  340W |       0MiB /  10240MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+
|   1  NVIDIA GeForce RTX 3060 Ti     On  |   00000000:03:00.0 Off |                  N/A |
|  0%   44C    P8             15W /  200W |     708MiB /   8192MiB |      2%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+

+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI              PID   Type   Process name                        GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|    0   N/A  N/A              28      G   /Xwayland                             N/A      |
|    1   N/A  N/A              28      G   /Xwayland                             N/A      |
+-----------------------------------------------------------------------------------------+
```

This is the command:
```
Executing command: /mnt/c/tools/AI/kohya_ss/venv/bin/accelerate launch --dynamo_backend no --dynamo_mode default --mixed_precision fp16
                         --multi_gpu --num_processes 2 --num_machines 1 --num_cpu_threads_per_process 2 /mnt/c/tools/AI/kohya_ss/sd-scripts/sdxl_train_network.py
                         --config_file /mnt/v/ImagesForSDTrining/Lora training/Test/model/config_lora-20250529-161705.toml
```

This is the error:
```
2025-05-29 16:18:26 INFO     make buckets                                                                                                           train_util.py:1010
                    WARNING  min_bucket_reso and max_bucket_reso are ignored if bucket_no_upscale is set, because bucket reso is defined by image   train_util.py:1027
                             size automatically /
                             bucket_no_upscaleが指定された場合は、bucketの解像度は画像サイズから自動計算されるため、min_bucket_resoとmax_bucket_res
                             oは無視されます
                    INFO     number of images (including repeats) / 各bucketの画像枚数（繰り返し回数を含む）                                        train_util.py:1056
                    INFO     bucket 0: resolution (512, 512), count: 1438                                                                           train_util.py:1061
                    INFO     mean ar error (without repeats): 0.0                                                                                   train_util.py:1069
                    WARNING  clip_skip will be unexpected / SDXL学習ではclip_skipは動作しません                                                 sdxl_train_util.py:349
                    INFO     preparing accelerator                                                                                                train_network.py:580
accelerator device: cuda:1
[rank1]:[W529 16:18:26.604637915 ProcessGroupNCCL.cpp:4715] [PG ID 0 PG GUID 0 Rank 1]  using GPU 1 as device used by this process is currently unknown. This can potentially cause a hang if this rank to GPU mapping is incorrect. You can pecify device_id in init_process_group() to force use of a particular device.
                    INFO     building U-Net                                                                                                     sdxl_model_util.py:198
2025-05-29 16:18:27 INFO     loading U-Net from checkpoint                                                                                      sdxl_model_util.py:202
                    INFO     U-Net: <All keys matched successfully>                                                                             sdxl_model_util.py:208
                    INFO     building text encoders                                                                                             sdxl_model_util.py:211
                    INFO     loading text encoders from checkpoint                                                                              sdxl_model_util.py:264
2025-05-29 16:18:28 INFO     text encoder 1: <All keys matched successfully>                                                                    sdxl_model_util.py:278
2025-05-29 16:18:33 INFO     text encoder 2: <All keys matched successfully>                                                                    sdxl_model_util.py:282
                    INFO     building VAE                                                                                                       sdxl_model_util.py:285
                    INFO     loading VAE from checkpoint                                                                                        sdxl_model_util.py:290
                    INFO     VAE: <All keys matched successfully>                                                                               sdxl_model_util.py:293
[rank0]:[W529 16:18:33.962232571 ProcessGroupNCCL.cpp:4715] [PG ID 0 PG GUID 0 Rank 0]  using GPU 0 as device used by this process is currently unknown. This can potentially cause a hang if this rank to GPU mapping is incorrect. You can pecify device_id in init_process_group() to force use of a particular device.
[rank1]: Traceback (most recent call last):
[rank1]:   File "/mnt/c/tools/AI/kohya_ss/sd-scripts/sdxl_train_network.py", line 229, in <module>
[rank1]:     trainer.train(args)
[rank1]:   File "/mnt/c/tools/AI/kohya_ss/sd-scripts/train_network.py", line 589, in train
[rank1]:     model_version, text_encoder, vae, unet = self.load_target_model(args, weight_dtype, accelerator)
[rank1]:   File "/mnt/c/tools/AI/kohya_ss/sd-scripts/sdxl_train_network.py", line 51, in load_target_model
[rank1]:     ) = sdxl_train_util.load_target_model(args, accelerator, sdxl_model_util.MODEL_VERSION_SDXL_BASE_V1_0, weight_dtype)
[rank1]:   File "/mnt/c/tools/AI/kohya_ss/sd-scripts/library/sdxl_train_util.py", line 60, in load_target_model
[rank1]:     accelerator.wait_for_everyone()
[rank1]:   File "/mnt/c/tools/AI/kohya_ss/venv/lib/python3.10/site-packages/accelerate/accelerator.py", line 2890, in wait_for_everyone
[rank1]:     wait_for_everyone()
[rank1]:   File "/mnt/c/tools/AI/kohya_ss/venv/lib/python3.10/site-packages/accelerate/utils/other.py", line 241, in wait_for_everyone
[rank1]:     PartialState().wait_for_everyone()
[rank1]:   File "/mnt/c/tools/AI/kohya_ss/venv/lib/python3.10/site-packages/accelerate/state.py", line 401, in wait_for_everyone
[rank1]:     torch.distributed.barrier()
[rank1]:   File "/mnt/c/tools/AI/kohya_ss/venv/lib/python3.10/site-packages/torch/distributed/c10d_logger.py", line 81, in wrapper
[rank1]:     return func(*args, **kwargs)
[rank1]:   File "/mnt/c/tools/AI/kohya_ss/venv/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 4622, in barrier
[rank1]:     work = group.barrier(opts=opts)
[rank1]: torch.distributed.DistBackendError: NCCL error in: /pytorch/torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:3353, unhandled cuda error (run with NCCL_DEBUG=INFO for details), NCCL version 2.26.2
[rank1]: ncclUnhandledCudaError: Call to CUDA function failed.
[rank1]: Last error:
[rank1]: Cuda failure 2 'out of memory'
W0529 16:18:35.603000 46081 venv/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/api.py:900] Sending process 46257 closing signal SIGTERM
E0529 16:18:36.278000 46081 venv/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/api.py:874] failed (exitcode: 1) local_rank: 1 (pid: 46258) of binary: /mnt/c/tools/AI/kohya_ss/venv/bin/python3.10
Traceback (most recent call last):
  File "/mnt/c/tools/AI/kohya_ss/venv/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/mnt/c/tools/AI/kohya_ss/venv/lib/python3.10/site-packages/accelerate/commands/accelerate_cli.py", line 50, in main
    args.func(args)
  File "/mnt/c/tools/AI/kohya_ss/venv/lib/python3.10/site-packages/accelerate/commands/launch.py", line 1189, in launch_command
    multi_gpu_launcher(args)
  File "/mnt/c/tools/AI/kohya_ss/venv/lib/python3.10/site-packages/accelerate/commands/launch.py", line 815, in multi_gpu_launcher
    distrib_run.run(args)
  File "/mnt/c/tools/AI/kohya_ss/venv/lib/python3.10/site-packages/torch/distributed/run.py", line 883, in run
    elastic_launch(
  File "/mnt/c/tools/AI/kohya_ss/venv/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 139, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/mnt/c/tools/AI/kohya_ss/venv/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 270, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:
============================================================
/mnt/c/tools/AI/kohya_ss/sd-scripts/sdxl_train_network.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2025-05-29_16:18:35
  host      : HarbingerMark4.localdomain
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 46258)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
16:18:37-136560 INFO     Training has ended.
```

I didn't find anything to help me in the documentation or similar complains in the issues.

Anyone can help me with that?

**Comment by NeoLoger** [comment]
I played with the configuration, I manage to resolve on problem just to get stuck on a different one.
I added port and IP this seem to progress but to a different failure point.

![Image](https://github.com/user-attachments/assets/4361a205-c308-4f3a-8de6-5a7b4bfff45b)

Still cant get the multi GPU training working. 

```
23:29:18-853708 INFO     Executing command: /mnt/c/tools/AI/kohya_ss/.venv/bin/accelerate launch --dynamo_backend no --dynamo_mode default --main_process_ip
                         172.18.219.97 --gpu_ids 1,0 --main_process_port 12355 --mixed_precision fp16 --multi_gpu --num_processes 2 --num_machines 1
                         --num_cpu_threads_per_process 2 /mnt/c/tools/AI/kohya_ss/sd-scripts/sdxl_train_network.py --config_file /mnt/v/ImagesForSDTrining/Lora
                         training/Test/config_lora-20250529-232918.toml
2025-05-29 23:30:27.859929: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:467] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2025-05-29 23:30:27.859964: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:467] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1748550627.879363    1028 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1748550627.879457    1029 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1748550627.888140    1028 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
E0000 00:00:1748550627.888280    1029 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1748550627.904353    1028 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1748550627.904429    1028 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1748550627.904435    1028 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1748550627.904438    1028 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1748550627.904534    1029 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1748550627.904595    1029 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1748550627.904601    1029 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1748550627.904603    1029 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
2025-05-29 23:30:27.908835: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2025-05-29 23:30:27.908835: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2025-05-29 23:30:40 INFO     Loading settings from /mnt/v/ImagesForSDTrining/Lora training/Test                                          train_util.py:4651
                             /model/config_lora-20250529-232918.toml...
2025-05-29 23:30:40 INFO     Loading settings from /mnt/v/ImagesForSDTrining/Lora training/Test                                          train_util.py:4651
                             /model/config_lora-20250529-232918.toml...
/mnt/c/tools/AI/kohya_ss/.venv/lib/python3.11/site-packages/transformers/tokenization_utils_base.py:1601: FutureWarning: `clean_up_tokenization_spaces` was not set. It will be set to `True` by default. This behavior will be depracted in transformers v4.45, and will be then set to `False` by default. For more details check this issue: https://github.com/huggingface/transformers/issues/31884
  warnings.warn(
2025-05-29 23:30:41 INFO     Using DreamBooth method.                                                                                             train_network.py:517
                    INFO     prepare images.                                                                                                        train_util.py:2072
/mnt/c/tools/AI/kohya_ss/.venv/lib/python3.11/site-packages/transformers/tokenization_utils_base.py:1601: FutureWarning: `clean_up_tokenization_spaces` was not set. It will be set to `True` by default. This behavior will be depracted in transformers v4.45, and will be then set to `False` by default. For more details check this issue: https://github.com/huggingface/transformers/issues/31884
  warnings.warn(
                    INFO     get image size from name of cache files                                                                                train_util.py:1965
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 48/48 [00:00<00:00, 505845.71it/s]
                    INFO     set image size from cache files: 0/48                                                                                  train_util.py:1995
                    INFO     found directory /mnt/v/ImagesForSDTrining/Lora training/Test/2_Test contains 48 image     train_util.py:2019
                             files
read caption: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 48/48 [00:00<00:00, 169.81it/s]
                    WARNING  No caption file found for 1 images. Training will continue without captions for these images. If class token exists,   train_util.py:2050
                             it will be used. /
                             1枚の画像にキャプションファイルが見つかりませんでした。これらの画像についてはキャプションなしで学習を続行します。class
                             tokenが存在する場合はそれを使います。
                    WARNING  /mnt/v/ImagesForSDTrining/Lora training/Test/00012-0-Rouge_IXbYJ6.png              train_util.py:2057
                    INFO     96 train images with repeats.                                                                                          train_util.py:2116
                    INFO     0 reg images with repeats.                                                                                             train_util.py:2120
                    WARNING  no regularization images / 正則化画像が見つかりませんでした                                                            train_util.py:2125
                    INFO     [Dataset 0]                                                                                                            config_util.py:580
                               batch_size: 1
                               resolution: (768, 768)
                               resize_interpolation: None
                               enable_bucket: True
                               min_bucket_reso: 256
                               max_bucket_reso: 1024
                               bucket_reso_steps: 64
                               bucket_no_upscale: True

                               [Subset 0 of Dataset 0]
                                 image_dir: "/mnt/v/ImagesForSDTrining/Lora training/Test/2_Test"
                                 image_count: 48
                                 num_repeats: 2
                                 shuffle_caption: True
                                 keep_tokens: 0
                                 caption_dropout_rate: 0.0
                                 caption_dropout_every_n_epochs: 0
                                 caption_tag_dropout_rate: 0.0
                                 caption_prefix: None
                                 caption_suffix: None
                                 color_aug: False
                                 flip_aug: True
                                 face_crop_aug_range: None
                                 random_crop: False
                                 token_warmup_min: 1,
                                 token_warmup_step: 0,
                                 alpha_mask: False
                                 resize_interpolation: None
                                 custom_attributes: {}
                                 is_reg: False
                                 class_tokens: Test
                                 caption_extension: .txt


                    INFO     [Prepare dataset 0]                                                                                                    config_util.py:592
                    INFO     loading image sizes.                                                                                                    train_util.py:987
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 48/48 [00:00<00:00, 317.37it/s]
2025-05-29 23:30:42 INFO     make buckets                                                                                                           train_util.py:1010
                    WARNING  min_bucket_reso and max_bucket_reso are ignored if bucket_no_upscale is set, because bucket reso is defined by image   train_util.py:1027
                             size automatically /
                             bucket_no_upscaleが指定された場合は、bucketの解像度は画像サイズから自動計算されるため、min_bucket_resoとmax_bucket_res
                             oは無視されます
                    INFO     number of images (including repeats) / 各bucketの画像枚数（繰り返し回数を含む）                                        train_util.py:1056
                    INFO     bucket 0: resolution (512, 512), count: 96                                                                             train_util.py:1061
                    INFO     mean ar error (without repeats): 0.0                                                                                   train_util.py:1069
                    WARNING  clip_skip will be unexpected / SDXL学習ではclip_skipは動作しません                                                 sdxl_train_util.py:349
                    INFO     preparing accelerator                                                                                                train_network.py:580
2025-05-29 23:30:42 INFO     Using DreamBooth method.                                                                                             train_network.py:517
                    INFO     prepare images.                                                                                                        train_util.py:2072
accelerator device: cuda:0
                    INFO     loading model for process 0/2                                                                                       sdxl_train_util.py:32
                    INFO     load StableDiffusion checkpoint: /mnt/v/Stable                                                                      sdxl_train_util.py:73
                             Diffusion/stable-diffusion-webui/models/Stable-diffusion/SDXL/ponyDiffusionV6XL_v6StartWithThisOne.safetensors
                    INFO     get image size from name of cache files                                                                                train_util.py:1965
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 48/48 [00:00<00:00, 300039.63it/s]
                    INFO     set image size from cache files: 0/48                                                                                  train_util.py:1995
                    INFO     found directory /mnt/v/ImagesForSDTrining/Lora training/Test/2_Test contains 48 image     train_util.py:2019
                             files
read caption: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 48/48 [00:00<00:00, 123.81it/s]
                    WARNING  No caption file found for 1 images. Training will continue without captions for these images. If class token exists,   train_util.py:2050
                             it will be used. /
                             1枚の画像にキャプションファイルが見つかりませんでした。これらの画像についてはキャプションなしで学習を続行します。class
                             tokenが存在する場合はそれを使います。
                    WARNING  /mnt/v/ImagesForSDTrining/Lora training/Test/00012-0-Rouge_IXbYJ6.png              train_util.py:2057
                    INFO     96 train images with repeats.                                                                                          train_util.py:2116
                    INFO     0 reg images with repeats.                                                                                             train_util.py:2120
                    WARNING  no regularization images / 正則化画像が見つかりませんでした                                                            train_util.py:2125
                    INFO     [Dataset 0]                                                                                                            config_util.py:580
                               batch_size: 1
                               resolution: (768, 768)
                               resize_interpolation: None
                               enable_bucket: True
                               min_bucket_reso: 256
                               max_bucket_reso: 1024
                               bucket_reso_steps: 64
                               bucket_no_upscale: True

                               [Subset 0 of Dataset 0]
                                 image_dir: "/mnt/v/ImagesForSDTrining/Lora training/Test/Image/2_Testt"
                                 image_count: 48
                                 num_repeats: 2
                                 shuffle_caption: True
                                 keep_tokens: 0
                                 caption_dropout_rate: 0.0
                                 caption_dropout_every_n_epochs: 0
                                 caption_tag_dropout_rate: 0.0
                                 caption_prefix: None
                                 caption_suffix: None
                                 color_aug: False
                                 flip_aug: True
                                 face_crop_aug_range: None
                                 random_crop: False
                                 token_warmup_min: 1,
                                 token_warmup_step: 0,
                                 alpha_mask: False
                                 resize_interpolation: None
                                 custom_attributes: {}
                                 is_reg: False
                                 class_tokens: Test
                                 caption_extension: .txt


                    INFO     [Prepare dataset 0]                                                                                                    config_util.py:592
                    INFO     loading image sizes.                                                                                                    train_util.py:987
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 48/48 [00:00<00:00, 241.65it/s]
                    INFO     make buckets                                                                                                           train_util.py:1010
                    WARNING  min_bucket_reso and max_bucket_reso are ignored if bucket_no_upscale is set, because bucket reso is defined by image   train_util.py:1027
                             size automatically /
                             bucket_no_upscaleが指定された場合は、bucketの解像度は画像サイズから自動計算されるため、min_bucket_resoとmax_bucket_res
                             oは無視されます
                    INFO     number of images (including repeats) / 各bucketの画像枚数（繰り返し回数を含む）                                        train_util.py:1056
                    INFO     bucket 0: resolution (512, 512), count: 96                                                                             train_util.py:1061
                    INFO     mean ar error (without repeats): 0.0                                                                                   train_util.py:1069
                    WARNING  clip_skip will be unexpected / SDXL学習ではclip_skipは動作しません                                                 sdxl_train_util.py:349
                    INFO     preparing accelerator                                                                                                train_network.py:580
                    INFO     building U-Net                                                                                                     sdxl_model_util.py:198
2025-05-29 23:30:43 INFO     loading U-Net from checkpoint                                                                                      sdxl_model_util.py:202
accelerator device: cuda:1
[rank1]:[W529 23:30:43.921166898 ProcessGroupNCCL.cpp:4715] [PG ID 0 PG GUID 0 Rank 1]  using GPU 1 as device used by this process is currently unknown. This can potentially cause a hang if this rank to GPU mapping is incorrect. You can pecify device_id in init_process_group() to force use of a particular device.
                    INFO     U-Net: <All keys matched successfully>                                                                             sdxl_model_util.py:208
                    INFO     building text encoders                                                                                             sdxl_model_util.py:211
                    INFO     loading text encoders from checkpoint                                                                              sdxl_model_util.py:264
2025-05-29 23:30:44 INFO     text encoder 1: <All keys matched successfully>                                                                    sdxl_model_util.py:278
2025-05-29 23:30:49 INFO     text encoder 2: <All keys matched successfully>                                                                    sdxl_model_util.py:282
                    INFO     building VAE                                                                                                       sdxl_model_util.py:285
                    INFO     loading VAE from checkpoint                                                                                        sdxl_model_util.py:290
                    INFO     VAE: <All keys matched successfully>                                                                               sdxl_model_util.py:293
[rank0]:[W529 23:30:49.591696521 ProcessGroupNCCL.cpp:4715] [PG ID 0 PG GUID 0 Rank 0]  using GPU 0 as device used by this process is currently unknown. This can potentially cause a hang if this rank to GPU mapping is incorrect. You can pecify device_id in init_process_group() to force use of a particular device.
HarbingerMark4:1028:1028 [0] NCCL INFO Bootstrap: Using eth0:172.18.219.97<0>
HarbingerMark4:1028:1028 [0] NCCL INFO cudaDriverVersion 12090
HarbingerMark4:1029:1029 [1] NCCL INFO cudaDriverVersion 12090
HarbingerMark4:1029:1029 [1] NCCL INFO Bootstrap: Using eth0:172.18.219.97<0>
HarbingerMark4:1028:1028 [0] NCCL INFO NCCL version 2.26.2+cuda12.2
HarbingerMark4:1029:1029 [1] NCCL INFO NCCL version 2.26.2+cuda12.2
HarbingerMark4:1029:1029 [1] NCCL INFO Comm config Blocking set to 1
HarbingerMark4:1028:1028 [0] NCCL INFO Comm config Blocking set to 1
HarbingerMark4:1028:1063 [0] NCCL INFO NET/Plugin: Could not find: libnccl-net.so. Using internal net plugin.
HarbingerMark4:1029:1064 [1] NCCL INFO NET/Plugin: Could not find: libnccl-net.so. Using internal net plugin.
HarbingerMark4:1028:1063 [0] NCCL INFO Failed to open libibverbs.so[.1]
HarbingerMark4:1028:1063 [0] NCCL INFO NET/Socket : Using [0]eth0:172.18.219.97<0>
HarbingerMark4:1029:1064 [1] NCCL INFO Failed to open libibverbs.so[.1]
HarbingerMark4:1029:1064 [1] NCCL INFO NET/Socket : Using [0]eth0:172.18.219.97<0>
HarbingerMark4:1028:1063 [0] NCCL INFO PROFILER/Plugin: Could not find: libnccl-profiler.so.
HarbingerMark4:1028:1063 [0] NCCL INFO Using network Socket
HarbingerMark4:1029:1064 [1] NCCL INFO PROFILER/Plugin: Could not find: libnccl-profiler.so.
HarbingerMark4:1029:1064 [1] NCCL INFO Using network Socket
HarbingerMark4:1028:1063 [0] NCCL INFO ncclCommInitRankConfig comm 0x5bb88f01dec0 rank 0 nranks 2 cudaDev 0 nvmlDev 1 busId 3000 commId 0x521785f307753e29 - Init START
HarbingerMark4:1029:1064 [1] NCCL INFO ncclCommInitRankConfig comm 0x6378b9182a40 rank 1 nranks 2 cudaDev 1 nvmlDev 0 busId 1000 commId 0x521785f307753e29 - Init START
HarbingerMark4:1028:1063 [0] NCCL INFO RAS client listening socket at 127.0.0.1<28028>
HarbingerMark4:1029:1064 [1] NCCL INFO RAS client listening socket at 127.0.0.1<28028>
HarbingerMark4:1029:1064 [1] NCCL INFO Bootstrap timings total 0.001110 (create 0.000027, send 0.000102, recv 0.000171, ring 0.000021, delay 0.000000)
HarbingerMark4:1028:1063 [0] NCCL INFO Bootstrap timings total 0.001898 (create 0.000031, send 0.000100, recv 0.000873, ring 0.000137, delay 0.000000)
HarbingerMark4:1029:1064 [1] NCCL INFO NCCL_P2P_DISABLE set by environment to 1
HarbingerMark4:1028:1063 [0] NCCL INFO NCCL_P2P_DISABLE set by environment to 1
HarbingerMark4:1028:1063 [0] NCCL INFO comm 0x5bb88f01dec0 rank 0 nRanks 2 nNodes 1 localRanks 2 localRank 0 MNNVL 0
HarbingerMark4:1029:1064 [1] NCCL INFO comm 0x6378b9182a40 rank 1 nRanks 2 nNodes 1 localRanks 2 localRank 1 MNNVL 0
HarbingerMark4:1028:1063 [0] NCCL INFO Channel 00/02 : 0 1
HarbingerMark4:1029:1064 [1] NCCL INFO Trees [0] -1/-1/-1->1->0 [1] -1/-1/-1->1->0
HarbingerMark4:1029:1064 [1] NCCL INFO NCCL_BUFFSIZE set by environment to 524288.
HarbingerMark4:1028:1063 [0] NCCL INFO Channel 01/02 : 0 1
HarbingerMark4:1029:1064 [1] NCCL INFO P2P Chunksize set to 65536
HarbingerMark4:1028:1063 [0] NCCL INFO Trees [0] 1/-1/-1->0->-1 [1] 1/-1/-1->0->-1
HarbingerMark4:1028:1063 [0] NCCL INFO NCCL_BUFFSIZE set by environment to 524288.
HarbingerMark4:1028:1063 [0] NCCL INFO P2P Chunksize set to 65536
HarbingerMark4:1028:1063 [0] NCCL INFO Check P2P Type intraNodeP2pSupport 0 directMode 0
HarbingerMark4:1029:1067 [1] NCCL INFO [Proxy Service] Device 1 CPU core 6
HarbingerMark4:1028:1068 [0] NCCL INFO [Proxy Service] Device 0 CPU core 0
HarbingerMark4:1029:1069 [1] NCCL INFO [Proxy Service UDS] Device 1 CPU core 10
HarbingerMark4:1028:1070 [0] NCCL INFO [Proxy Service UDS] Device 0 CPU core 9
HarbingerMark4:1029:1064 [1] NCCL INFO threadThresholds 8/8/64 | 16/8/64 | 512 | 512
HarbingerMark4:1029:1064 [1] NCCL INFO 2 coll channels, 2 collnet channels, 0 nvls channels, 2 p2p channels, 2 p2p channels per peer
HarbingerMark4:1028:1063 [0] NCCL INFO threadThresholds 8/8/64 | 16/8/64 | 512 | 512
HarbingerMark4:1028:1063 [0] NCCL INFO 2 coll channels, 2 collnet channels, 0 nvls channels, 2 p2p channels, 2 p2p channels per peer
HarbingerMark4:1028:1063 [0] NCCL INFO CC Off, workFifoBytes 1048576
HarbingerMark4:1029:1064 [1] NCCL INFO TUNER/Plugin: Could not find: libnccl-tuner.so. Using internal tuner plugin.
HarbingerMark4:1029:1064 [1] NCCL INFO ncclCommInitRankConfig comm 0x6378b9182a40 rank 1 nranks 2 cudaDev 1 nvmlDev 0 busId 1000 commId 0x521785f307753e29 - Init COMPLETE
HarbingerMark4:1029:1064 [1] NCCL INFO Init timings - ncclCommInitRankConfig: rank 1 nranks 2 total 0.36 (kernels 0.29, alloc 0.03, bootstrap 0.00, allgathers 0.01, topo 0.01, graphs 0.00, connections 0.01, rest 0.01)
HarbingerMark4:1028:1063 [0] NCCL INFO TUNER/Plugin: Could not find: libnccl-tuner.so. Using internal tuner plugin.
HarbingerMark4:1028:1063 [0] NCCL INFO ncclCommInitRankConfig comm 0x5bb88f01dec0 rank 0 nranks 2 cudaDev 0 nvmlDev 1 busId 3000 commId 0x521785f307753e29 - Init COMPLETE
HarbingerMark4:1028:1063 [0] NCCL INFO Init timings - ncclCommInitRankConfig: rank 0 nranks 2 total 0.36 (kernels 0.28, alloc 0.03, bootstrap 0.00, allgathers 0.00, topo 0.02, graphs 0.00, connections 0.01, rest 0.01)

[2025-05-29 23:30:50] HarbingerMark4:1029:1067 [1] include/alloc.h:65 NCCL WARN Cuda failure 2 'out of memory'
HarbingerMark4:1029:1067 [1] NCCL INFO transport/shm.cc:534 -> 1
HarbingerMark4:1029:1067 [1] NCCL INFO transport/shm.cc:491 -> 1
HarbingerMark4:1029:1072 [1] NCCL INFO transport/shm.cc:153 -> 1
HarbingerMark4:1029:1072 [1] NCCL INFO transport.cc:35 -> 1
HarbingerMark4:1029:1072 [1] NCCL INFO transport.cc:147 -> 1
HarbingerMark4:1029:1072 [1] NCCL INFO transport/generic.cc:19 -> 1
HarbingerMark4:1029:1072 [1] NCCL INFO group.cc:148 -> 1
HarbingerMark4:1029:1072 [1] NCCL INFO group.cc:75 -> 1 [Async thread]
HarbingerMark4:1029:1029 [1] NCCL INFO group.cc:460 -> 1
HarbingerMark4:1029:1029 [1] NCCL INFO group.cc:581 -> 1
HarbingerMark4:1029:1029 [1] NCCL INFO enqueue.cc:2299 -> 1
HarbingerMark4:1028:1071 [0] NCCL INFO Channel 00 : 0[1] -> 1[0] via SHM/direct/direct
HarbingerMark4:1028:1071 [0] NCCL INFO Channel 01 : 0[1] -> 1[0] via SHM/direct/direct
[rank1]: Traceback (most recent call last):
[rank1]:   File "/mnt/c/tools/AI/kohya_ss/sd-scripts/sdxl_train_network.py", line 229, in <module>
[rank1]:     trainer.train(args)
[rank1]:   File "/mnt/c/tools/AI/kohya_ss/sd-scripts/train_network.py", line 589, in train
[rank1]:     model_version, text_encoder, vae, unet = self.load_target_model(args, weight_dtype, accelerator)
[rank1]:                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank1]:   File "/mnt/c/tools/AI/kohya_ss/sd-scripts/sdxl_train_network.py", line 51, in load_target_model
[rank1]:     ) = sdxl_train_util.load_target_model(args, accelerator, sdxl_model_util.MODEL_VERSION_SDXL_BASE_V1_0, weight_dtype)
[rank1]:         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank1]:   File "/mnt/c/tools/AI/kohya_ss/sd-scripts/library/sdxl_train_util.py", line 60, in load_target_model
[rank1]:     accelerator.wait_for_everyone()
[rank1]:   File "/mnt/c/tools/AI/kohya_ss/.venv/lib/python3.11/site-packages/accelerate/accelerator.py", line 2890, in wait_for_everyone
[rank1]:     wait_for_everyone()
[rank1]:   File "/mnt/c/tools/AI/kohya_ss/.venv/lib/python3.11/site-packages/accelerate/utils/other.py", line 241, in wait_for_everyone
[rank1]:     PartialState().wait_for_everyone()
[rank1]:   File "/mnt/c/tools/AI/kohya_ss/.venv/lib/python3.11/site-packages/accelerate/state.py", line 401, in wait_for_everyone
[rank1]:     torch.distributed.barrier()
[rank1]:   File "/mnt/c/tools/AI/kohya_ss/.venv/lib/python3.11/site-packages/torch/distributed/c10d_logger.py", line 81, in wrapper
[rank1]:     return func(*args, **kwargs)
[rank1]:            ^^^^^^^^^^^^^^^^^^^^^
[rank1]:   File "/mnt/c/tools/AI/kohya_ss/.venv/lib/python3.11/site-packages/torch/distributed/distributed_c10d.py", line 4622, in barrier
[rank1]:     work = group.barrier(opts=opts)
[rank1]:            ^^^^^^^^^^^^^^^^^^^^^^^^
[rank1]: torch.distributed.DistBackendError: NCCL error in: /pytorch/torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:3353, unhandled cuda error (run with NCCL_DEBUG=INFO for details), NCCL version 2.26.2
[rank1]: ncclUnhandledCudaError: Call to CUDA function failed.
[rank1]: Last error:
[rank1]: Cuda failure 2 'out of memory'
HarbingerMark4:1029:1074 [1] NCCL INFO misc/socket.cc:64 -> 3
HarbingerMark4:1029:1074 [1] NCCL INFO misc/socket.cc:80 -> 3
HarbingerMark4:1029:1074 [1] NCCL INFO misc/socket.cc:829 -> 3
HarbingerMark4:1029:1067 [1] NCCL INFO misc/socket.cc:881 -> 3
HarbingerMark4:1029:1074 [1] NCCL INFO comm 0x6378b9182a40 rank 1 nranks 2 cudaDev 1 busId 1000 - Abort COMPLETE
W0529 23:30:52.538000 1006 .venv/lib/python3.11/site-packages/torch/distributed/elastic/multiprocessing/api.py:900] Sending process 1028 closing signal SIGTERM
E0529 23:30:53.264000 1006 .venv/lib/python3.11/site-packages/torch/distributed/elastic/multiprocessing/api.py:874] failed (exitcode: 1) local_rank: 1 (pid: 1029) of binary: /mnt/c/tools/AI/kohya_ss/.venv/bin/python
Traceback (most recent call last):
  File "/mnt/c/tools/AI/kohya_ss/.venv/bin/accelerate", line 10, in <module>
    sys.exit(main())
             ^^^^^^
  File "/mnt/c/tools/AI/kohya_ss/.venv/lib/python3.11/site-packages/accelerate/commands/accelerate_cli.py", line 50, in main
    args.func(args)
  File "/mnt/c/tools/AI/kohya_ss/.venv/lib/python3.11/site-packages/accelerate/commands/launch.py", line 1189, in launch_command
    multi_gpu_launcher(args)
  File "/mnt/c/tools/AI/kohya_ss/.venv/lib/python3.11/site-packages/accelerate/commands/launch.py", line 815, in multi_gpu_launcher
    distrib_run.run(args)
  File "/mnt/c/tools/AI/kohya_ss/.venv/lib/python3.11/site-packages/torch/distributed/run.py", line 883, in run
    elastic_launch(
  File "/mnt/c/tools/AI/kohya_ss/.venv/lib/python3.11/site-packages/torch/distributed/launcher/api.py", line 139, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/tools/AI/kohya_ss/.venv/lib/python3.11/site-packages/torch/distributed/launcher/api.py", line 270, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:
============================================================
/mnt/c/tools/AI/kohya_ss/sd-scripts/sdxl_train_network.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2025-05-29_23:30:52
  host      : HarbingerMark4.localdomain
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 1029)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
23:30:54-169296 INFO     Training has ended.
```

**Comment by bmaltais** [comment]
Wish I could help... but I have never trained on multi-gpu. But from what I gathered... it is very difficult to do with kohya_ss

**Comment by NeoLoger** [comment]
Ok, I think I figured some of it out.

By disabling NCCL_SHM it allows me to start the training however I'm still getting OOM due to the one of my GPUs has less VRAM
```
[rank1]: torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 40.00 MiB. GPU 1 has a total capacity of 8.00 GiB of which 0 bytes is free. Process 2319 has 17179869184.00 GiB memory in use. Including non-PyTorch memory, this process has 17179869184.00 GiB memory in use. Of the allocated memory 6.95 GiB is allocated by PyTorch, and 338.75 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management 
```


I load the environment in my WSL and add an export variable then load the gui-uv.sh 
```
export NCCL_SHM_DISABLE=1
``` 

Not sure how to progress from here, if I figure it out I'll post here.
But if anyone have any suggestions or solutions I'll be more than happy to hear them.

**Comment by m-doughty** [comment]
Just adding, for my A6000s on Linux it was:

```
export NCCL_P2P_DISABLE=1
```

**Comment by zuoyanzhang** [comment]
@m-doughty it also works for me.
