### ISSUE TITLE
无法训练模型

### ISSUE THREAD

**Issue by meijun1997** [bmaltais/kohya_ss#381]
CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching /usr/local/cuda/lib64...
F:\stable\kohya\kohya_ss\venv\lib\site-packages\bitsandbytes\cuda_setup\paths.py:27: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {WindowsPath('/usr/local/cuda/lib64')}
  warn(
WARNING: No libcudart.so found! Install CUDA or the cudatoolkit package (anaconda)!
CUDA SETUP: Loading binary F:\stable\kohya\kohya_ss\venv\lib\site-packages\bitsandbytes\libbitsandbytes_cpu.so...
Traceback (most recent call last):
  File "F:\stable\kohya\kohya_ss\train_network.py", line 659, in <module>
    train(args)
  File "F:\stable\kohya\kohya_ss\train_network.py", line 171, in train
    optimizer_name, optimizer_args, optimizer = train_util.get_optimizer(args, trainable_params)
  File "F:\stable\kohya\kohya_ss\library\train_util.py", line 1719, in get_optimizer
    import bitsandbytes as bnb
  File "F:\stable\kohya\kohya_ss\venv\lib\site-packages\bitsandbytes\__init__.py", line 6, in <module>
    from .autograd._functions import (
  File "F:\stable\kohya\kohya_ss\venv\lib\site-packages\bitsandbytes\autograd\_functions.py", line 5, in <module>
    import bitsandbytes.functional as F
  File "F:\stable\kohya\kohya_ss\venv\lib\site-packages\bitsandbytes\functional.py", line 13, in <module>
    from .cextension import COMPILED_WITH_CUDA, lib
  File "F:\stable\kohya\kohya_ss\venv\lib\site-packages\bitsandbytes\cextension.py", line 41, in <module>
    lib = CUDALibrary_Singleton.get_instance().lib
  File "F:\stable\kohya\kohya_ss\venv\lib\site-packages\bitsandbytes\cextension.py", line 37, in get_instance
    cls._instance.initialize()
  File "F:\stable\kohya\kohya_ss\venv\lib\site-packages\bitsandbytes\cextension.py", line 31, in initialize
    self.lib = ct.cdll.LoadLibrary(binary_path)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\ctypes\__init__.py", line 452, in LoadLibrary    return self._dlltype(name)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\ctypes\__init__.py", line 364, in __init__
    if '/' in name or '\\' in name:
TypeError: argument of type 'WindowsPath' is not iterable
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "F:\stable\kohya\kohya_ss\venv\Scripts\accelerate.exe\__main__.py", line 7, in <module>
  File "F:\stable\kohya\kohya_ss\venv\lib\site-packages\accelerate\commands\accelerate_cli.py", line 45, in main
    args.func(args)
  File "F:\stable\kohya\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 1104, in launch_command
    simple_launcher(args)
  File "F:\stable\kohya\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 567, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['F:\\stable\\kohya\\kohya_ss\\venv\\Scripts\\python.exe', 'train_network.py', '--pretrained_model_name_or_path=runwayml/stable-diffusion-v1-5', '--train_data_dir=F:/stable/train/catmodel/image', '--resolution=512,512', '--output_dir=F:/stable/train/catmodel/model', '--logging_dir=F:/stable/train/catmodel/log', '--network_alpha=128', '--save_model_as=safetensors', '--network_module=networks.lora', '--text_encoder_lr=5e-5', '--unet_lr=0.0001', '--network_dim=128', '--output_name=Addams', '--lr_scheduler_num_cycles=1', '--learning_rate=0.0001', '--lr_scheduler=constant', '--train_batch_size=1', '--max_train_steps=1500', '--save_every_n_epochs=1', '--mixed_precision=fp16', '--save_precision=fp16', '--seed=1234', '--caption_extension=.txt', '--cache_latents', '--optimizer_type=AdamW8bit', '--max_data_loader_n_workers=1', '--clip_skip=2', '--bucket_reso_steps=64', '--mem_eff_attn', '--gradient_checkpointing', '--xformers', '--bucket_no_upscale']' returned non-zero exit status 1.

**Comment by yifenglv46** [comment]
一摸一样的情况，估计是新版本的问题

**Comment by FinaBro69** [comment]
各位我找到好消息了，他們使用的顯卡30系或40系lora訓練是沒問題的，他們更不知道10系或16系還有人在用，所以作者呢把kohya_ss設定為30系或40系的設定，所以我們沒有辦法訓練lora。

來首先點擊Dreambooth LoRA點擊Training parameters
然後你會看到AdamW8bit設定選擇AdamW
還有你會看到Gradient checkpointing和Memory efficient attention跟它打√就對了。

希望這個設定對你們有幫助。

**Comment by Big-ANGELO** [comment]
> 各位我找到好消息了，他們使用的顯卡30系或40系lora訓練是沒問題的，他們更不知道10系或16系還有人在用，所以作者呢把kohya_ss設定為30系或40系的設定，所以我們沒有辦法訓練lora。
> 
> 來首先點擊Dreambooth LoRA點擊Training parameters 然後你會看到AdamW8bit設定選擇AdamW 還有你會看到Gradient checkpointing和Memory efficient attention跟它打√就對了。
> 
> 希望這個設定對你們有幫助。

It doesn't work~BRO~

**Comment by Chasexj** [comment]
@FinaBro69 worked for me

**Comment by lamboJw** [comment]
> 各位我找到好消息了，他們使用的顯卡30系或40系lora訓練是沒問題的，他們更不知道10系或16系還有人在用，所以作者呢把kohya_ss設定為30系或40系的設定，所以我們沒有辦法訓練lora。
> 
> 來首先點擊Dreambooth LoRA點擊Training parameters 然後你會看到AdamW8bit設定選擇AdamW 還有你會看到Gradient checkpointing和Memory efficient attention跟它打√就對了。
> 
> 希望這個設定對你們有幫助。

解决了我的问题，终于开始训练了
