### ISSUE TITLE
CUDA issue

### ISSUE THREAD

**Issue by Chasexj** [bmaltais/kohya_ss#465]
Follow up on #461 , the python version is fixed but the problem persists:
System: RHEL 8 with conda environment configured using ubuntu_setup.sh

CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching /usr/local/cuda/lib64...                                                                                                                                    CUDA SETUP: CUDA runtime path found: /usr/local/cuda/lib64/libcudart.so                                                                                                                                                                      CUDA SETUP: Highest compute capability among GPUs detected: 7.5                                                                                                                                                                              CUDA SETUP: Detected CUDA version 121                                                                                                                                                                                                        CUDA SETUP: TODO: compile library for specific version: libbitsandbytes_cuda121.so                                                                                                                                                           CUDA SETUP: Defaulting to libbitsandbytes.so...                                                                                                                                                                                              CUDA SETUP: CUDA detection failed. Either CUDA driver not installed, CUDA not installed, or you have multiple conflicting CUDA libraries!                                                                                                    CUDA SETUP: If you compiled from source, try again with `make CUDA_VERSION=DETECTED_CUDA_VERSION` for example, `make CUDA_VERSION=113`.                                                                                                      Traceback (most recent call last):                                                                                                                                                                                                             File "/scratch/cjiang/fine_tune/kohya/kohya_ss/train_network.py", line 699, in <module>                                                                                                                                                        train(args)                                                                                                                                                                                                                                File "/scratch/cjiang/fine_tune/kohya/kohya_ss/train_network.py", line 183, in train                                                                                                                                                           optimizer_name, optimizer_args, optimizer = train_util.get_optimizer(args, trainable_params)                                                                                                                                               File "/scratch/cjiang/fine_tune/kohya/kohya_ss/library/train_util.py", line 2208, in get_optimizer                                                                                                                                             import bitsandbytes as bnb                                                                                                                                                                                                                 File "/scratch/cjiang/fine_tune/kohya/kohya_ss/venv/lib/python3.10/site-packages/bitsandbytes/__init__.py", line 6, in <module>                                                                                                                from .autograd._functions import (                                                                                                                                                                                                         File "/scratch/cjiang/fine_tune/kohya/kohya_ss/venv/lib/python3.10/site-packages/bitsandbytes/autograd/_functions.py", line 5, in <module>                                                                                                     import bitsandbytes.functional as F                                                                                                                                                                                                        File "/scratch/cjiang/fine_tune/kohya/kohya_ss/venv/lib/python3.10/site-packages/bitsandbytes/functional.py", line 13, in <module>                                                                                                             from .cextension import COMPILED_WITH_CUDA, lib                                                                                                                                                                                            File "/scratch/cjiang/fine_tune/kohya/kohya_ss/venv/lib/python3.10/site-packages/bitsandbytes/cextension.py", line 41, in <module>                                                                                                             lib = CUDALibrary_Singleton.get_instance().lib                                                                                                                                                                                             File "/scratch/cjiang/fine_tune/kohya/kohya_ss/venv/lib/python3.10/site-packages/bitsandbytes/cextension.py", line 37, in get_instance                                                                                                         cls._instance.initialize()                                                                                                                                                                                                                 File "/scratch/cjiang/fine_tune/kohya/kohya_ss/venv/lib/python3.10/site-packages/bitsandbytes/cextension.py", line 27, in initialize                                                                                                           raise Exception('CUDA SETUP: Setup Failed!')                                                                                                                                                                                             Exception: CUDA SETUP: Setup Failed!                                                                                                                                                                                                         Traceback (most recent call last):                                                                                                                                                                                                             File "/scratch/cjiang/fine_tune/kohya/kohya_ss/venv/bin/accelerate", line 8, in <module>                                                                                                                                                       sys.exit(main())                                                                                                                                                                                                                           File "/scratch/cjiang/fine_tune/kohya/kohya_ss/venv/lib/python3.10/site-packages/accelerate/commands/accelerate_cli.py", line 45, in main                                                                                                      args.func(args)                                                                                                                                                                                                                            File "/scratch/cjiang/fine_tune/kohya/kohya_ss/venv/lib/python3.10/site-packages/accelerate/commands/launch.py", line 1104, in launch_command                                                                                                  simple_launcher(args)                                                                                                                                                                                                                      File "/scratch/cjiang/fine_tune/kohya/kohya_ss/venv/lib/python3.10/site-packages/accelerate/commands/launch.py", line 567, in simple_launcher                                                                                                  raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)                                                                                                                                                              subprocess.CalledProcessError: Command '['/scratch/cjiang/fine_tune/kohya/kohya_ss/venv/bin/python3', 'train_network.py', '--pretrained_model_name_or_path=runwayml/stable-diffusion-v1-5', '--train_data_dir=/scratch/cjiang/fine_tune/kohya/kohya_ss/model_training/network_1024_lora/image', '--resolution=512,512', '--output_dir=/scratch/cjiang/fine_tune/kohya/kohya_ss/model_training/network_1024_lora/model', '--logging_dir=/scratch/cjiang/fine_tune/kohya/kohya_ss/model_training/network_1024_lora/log', '--network_alpha=128', '--save_model_as=safetensors', '--network_module=networks.lora', '--text_encoder_lr=5e-5', '--unet_lr=0.0001', '--network_dim=128', '--output_name=Addams', '--lr_scheduler_num_cycles=1', '--learning_rate=0.0001', '--lr_scheduler=constant', '--train_batch_size=2', '--max_train_steps=4200', '--save_every_n_epochs=1', '--mixed_precision=fp16', '--save_precision=fp16', '--seed=1234', '--caption_extension=.txt', '--cache_latents', '--optimizer_type=AdamW8bit', '--max_data_loader_n_workers=1', '--clip_skip=2', '--bucket_reso_steps=64', '--mem_eff_attn', '--xformers', '--bucket_no_upscale']' returned non-zero exit status 1.

**Comment by costs** [comment]
/root/kohya_ss/venv/lib/python3.10/site-packages/bitsandbytes/cuda_setup/paths.py:27: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {PosixPath('/root/kohya_ss/venv/lib/python3.10/site-packages/cv2/../../lib64')}
  warn(
CUDA SETUP: CUDA runtime path found: /usr/local/cuda-12.0/lib64/libcudart.so
CUDA SETUP: Highest compute capability among GPUs detected: 8.9
CUDA SETUP: Detected CUDA version 120
CUDA SETUP: TODO: compile library for specific version: libbitsandbytes_cuda120_nocublaslt.so
CUDA SETUP: Defaulting to libbitsandbytes.so...
CUDA SETUP: CUDA detection failed. Either CUDA driver not installed, CUDA not installed, or you have multiple conflicting CUDA libraries!
CUDA SETUP: If you compiled from source, try again with `make CUDA_VERSION=DETECTED_CUDA_VERSION` for example, `make CUDA_VERSION=113`.
Traceback (most recent call last):
  File "/root/kohya_ss/train_network.py", line 724, in <module>
    train(args)
  File "/root/kohya_ss/train_network.py", line 200, in train
    optimizer_name, optimizer_args, optimizer = train_util.get_optimizer(args, trainable_params)
  File "/root/kohya_ss/library/train_util.py", line 2312, in get_optimizer
    import bitsandbytes as bnb
  File "/root/kohya_ss/venv/lib/python3.10/site-packages/bitsandbytes/__init__.py", line 6, in <module>
    from .autograd._functions import (
  File "/root/kohya_ss/venv/lib/python3.10/site-packages/bitsandbytes/autograd/_functions.py", line 5, in <module>
    import bitsandbytes.functional as F
  File "/root/kohya_ss/venv/lib/python3.10/site-packages/bitsandbytes/functional.py", line 13, in <module>
    from .cextension import COMPILED_WITH_CUDA, lib
  File "/root/kohya_ss/venv/lib/python3.10/site-packages/bitsandbytes/cextension.py", line 41, in <module>
    lib = CUDALibrary_Singleton.get_instance().lib
  File "/root/kohya_ss/venv/lib/python3.10/site-packages/bitsandbytes/cextension.py", line 37, in get_instance
    cls._instance.initialize()
  File "/root/kohya_ss/venv/lib/python3.10/site-packages/bitsandbytes/cextension.py", line 27, in initialize
    raise Exception('CUDA SETUP: Setup Failed!')
Exception: CUDA SETUP: Setup Failed!
Traceback (most recent call last):
  File "/root/kohya_ss/venv/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/root/kohya_ss/venv/lib/python3.10/site-packages/accelerate/commands/accelerate_cli.py", line 45, in main
    args.func(args)
  File "/root/kohya_ss/venv/lib/python3.10/site-packages/accelerate/commands/launch.py", line 1104, in launch_command
    simple_launcher(args)
  File "/root/kohya_ss/venv/lib/python3.10/site-packages/accelerate/commands/launch.py", line 567, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/root/kohya_ss/venv/bin/python', 'train_network.py', '--pretrained_model_name_or_path=runwayml/stable-diffusion-v1-5', '--train_data_dir=/root/kohya_ss/Train_Models/QingJu_Lora/img', '--resolution=768,768', '--output_dir=/root/kohya_ss/Train_Models/QingJu_Lora/model', '--logging_dir=/root/kohya_ss/Train_Models/QingJu_Lora/log', '--network_alpha=128', '--save_model_as=safetensors', '--network_module=networks.lora', '--text_encoder_lr=5e-5', '--unet_lr=0.0001', '--network_dim=128', '--output_name=QingJu', '--lr_scheduler_num_cycles=1', '--learning_rate=0.0001', '--lr_scheduler=constant', '--train_batch_size=2', '--max_train_steps=2500', '--save_every_n_epochs=1', '--mixed_precision=bf16', '--save_precision=bf16', '--seed=1234', '--caption_extension=.txt', '--cache_latents', '--optimizer_type=AdamW8bit', '--max_data_loader_n_workers=1', '--clip_skip=2', '--bucket_reso_steps=64', '--xformers', '--bucket_no_upscale']' returned non-zero exit status 1.

**Comment by ArtificialCleverness** [comment]
I solved this problem by removing `bitsandbytes` version, try
`pip uninstall bitsandbytes ./setup.sh`
#684 
I also created a PR by removing the version constraint
