### ISSUE TITLE
Does it work on Intel GPUs?

### ISSUE THREAD

**Issue by Jaeha47** [bmaltais/kohya_ss#615]
It just stuck at 
`"  0%|                                                                                           | 0/15 [00:00<?, ?it/s] "`
Is it because of my Intel Arc? Or did i do something wrong? 

*edit ok now it gave the error
```
 raise ValueError(err.format(mode="fp16", requirement="a GPU"))
ValueError: fp16 mixed precision requires a GPU
```

So guess it doesnt with with Intel GPUs

/edit
After setting Mixed Precision to no and Save Precision to float it in training parameter settings the first step worked but it then gives me a bounch of errors during the optimization.

```
E:\Arc Diffusion\Kohya\kohya_ss\venv\lib\site-packages\torch\utils\checkpoint.py:25: UserWarning: None of the inputs have requires_grad=True. Gradients will be None
  warnings.warn("None of the inputs have requires_grad=True. Gradients will be None")
E:\Arc Diffusion\Kohya\kohya_ss\venv\lib\site-packages\torch\amp\autocast_mode.py:198: UserWarning: User provided device_type of 'cuda', but CUDA is not available. Disabling
  warnings.warn('User provided device_type of \'cuda\', but CUDA is not available. Disabling')
Error CUDA driver version is insufficient for CUDA runtime version at line 167 in file D:\ai\tool\bitsandbytes\csrc\ops.cu
Traceback (most recent call last):
  File "C:\Users\denni\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\denni\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "E:\Arc Diffusion\Kohya\kohya_ss\venv\Scripts\accelerate.exe\__main__.py", line 7, in <module>
  File "E:\Arc Diffusion\Kohya\kohya_ss\venv\lib\site-packages\accelerate\commands\accelerate_cli.py", line 45, in main
    args.func(args)
  File "E:\Arc Diffusion\Kohya\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 1104, in launch_command
    simple_launcher(args)
  File "E:\Arc Diffusion\Kohya\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 567, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['E:\\Arc Diffusion\\Kohya\\kohya_ss\\venv\\Scripts\\python.exe', 'train_network.py', '--pretrained_model_name_or_path=runwayml/stable-diffusion-v1-5', '--train_data_dir=C:/Users/PC/Desktop/Stamp/CharLORA/image', '--resolution=512,512', '--output_dir=C:/Users/PC/Desktop/Stamp/CharLORA/model', '--logging_dir=C:/Users/PC/Desktop/Stamp/CharLORA/log', '--network_alpha=128', '--save_model_as=safetensors', '--network_module=networks.lora', '--text_encoder_lr=5e-5', '--unet_lr=0.0001', '--network_dim=128', '--output_name=Feste', '--lr_scheduler_num_cycles=1', '--learning_rate=0.0001', '--lr_scheduler=constant', '--train_batch_size=1', '--max_train_steps=1500', '--save_every_n_epochs=1', '--mixed_precision=no', '--save_precision=float', '--seed=1234', '--caption_extension=.txt', '--cache_latents', '--optimizer_type=AdamW8bit', '--max_data_loader_n_workers=1', '--clip_skip=2', '--bucket_reso_steps=64', '--mem_eff_attn', '--gradient_checkpointing', '--xformers', '--bucket_no_upscale']' returned non-zer
```

**Comment by bmaltais** [comment]
The solution is only supported under NVidia and (maybe) MacOS gpu... but I am not 100% sure if it work properly on MacOS Mx CPU/GPU

**Comment by nonetrix** [comment]
Really would like to see Intel Arc support since they have way more VRAM than the competition for cheaper despite the performance

**Comment by Disty0** [comment]
Intel ARC is working now:
https://www.technopat.net/sosyal/konu/installing-kohya-ss-with-intel-arc-gpus.2869152/

**Comment by ep150de** [comment]
I'm still running into issues with getting kohya training to run on intel arc A770 gpu after following the --use-ipex flag for setup and running the gui.

error traceback:
Traceback (most recent call last):
  File "C:\Users\Demo\kohya_ss\sdxl_train_network.py", line 189, in <module>
    trainer.train(args)
  File "C:\Users\Demo\kohya_ss\train_network.py", line 242, in train
    vae.set_use_memory_efficient_attention_xformers(args.xformers)
  File "C:\Users\Demo\kohya_ss\venv\lib\site-packages\diffusers\models\modeling_utils.py", line 263, in set_use_memory_efficient_attention_xformers
    fn_recursive_set_mem_eff(module)
  File "C:\Users\Demo\kohya_ss\venv\lib\site-packages\diffusers\models\modeling_utils.py", line 259, in fn_recursive_set_mem_eff
    fn_recursive_set_mem_eff(child)
  File "C:\Users\Demo\kohya_ss\venv\lib\site-packages\diffusers\models\modeling_utils.py", line 259, in fn_recursive_set_mem_eff
    fn_recursive_set_mem_eff(child)
  File "C:\Users\Demo\kohya_ss\venv\lib\site-packages\diffusers\models\modeling_utils.py", line 259, in fn_recursive_set_mem_eff
    fn_recursive_set_mem_eff(child)
  File "C:\Users\Demo\kohya_ss\venv\lib\site-packages\diffusers\models\modeling_utils.py", line 256, in fn_recursive_set_mem_eff
    module.set_use_memory_efficient_attention_xformers(valid, attention_op)
  File "C:\Users\Demo\kohya_ss\venv\lib\site-packages\diffusers\models\attention_processor.py", line 255, in set_use_memory_efficient_attention_xformers
    raise ValueError(
ValueError: torch.cuda.is_available() should be True but is False. xformers' memory efficient attention is only available for GPU
Traceback (most recent call last):
  File "C:\Users\Demo\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Demo\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\Demo\kohya_ss\venv\Scripts\accelerate.exe\__main__.py", line 7, in <module>
  File "C:\Users\Demo\kohya_ss\venv\lib\site-packages\accelerate\commands\accelerate_cli.py", line 47, in main
    args.func(args)
  File "C:\Users\Demo\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 986, in launch_command
    simple_launcher(args)
  File "C:\Users\Demo\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 628, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['C:\\Users\\Demo\\kohya_ss\\venv\\Scripts\\python.exe', './sdxl_train_network.py', '--enable_bucket', '--min_bucket_reso=256', '--max_bucket_reso=2048', '--pretrained_model_name_or_path=stabilityai/stable-diffusion-xl-base-1.0', '--train_data_dir=C:/Users/Demo/Desktop/pat/round2 training\\img', '--resolution=1024,1024', '--output_dir=C:/Users/Demo/Desktop/pat/round2 training\\model', '--logging_dir=C:/Users/Demo/Desktop/pat/round2 training\\log', '--network_alpha=1', '--save_model_as=safetensors', '--network_module=networks.lora', '--text_encoder_lr=0.0004', '--unet_lr=0.0004', '--network_dim=256', '--output_name=patgv7_arc', '--lr_scheduler_num_cycles=4', '--no_half_vae', '--learning_rate=0.0004', '--lr_scheduler=constant', '--train_batch_size=2', '--max_train_steps=1680', '--save_every_n_epochs=1', '--mixed_precision=bf16', '--save_precision=bf16', '--cache_latents', '--cache_latents_to_disk', '--optimizer_type=Adafactor', '--optimizer_args', 'scale_parameter=False', 'relative_step=False', 'warmup_init=False', '--max_grad_norm=1', '--max_data_loader_n_workers=0', '--bucket_reso_steps=64', '--save_state', '--gradient_checkpointing', '--xformers', '--bucket_no_upscale', '--noise_offset=0.0']' returned non-zero exit status 1.

**Comment by Disty0** [comment]
Guide i sent tells you to use SDPA. Follow the guide.

**Comment by kainatquaderee** [comment]
it doesnt works now. is there any workarround?

```
./setup.sh --use-ipex
Skipping git operations.
Switching to virtual Python environment using python3.11.
Detected active conda environment: ./conda_env
Using existing conda environment at: ./conda_env
[04/07/26 01:50:14] INFO     Python version is 3.11.15 (main, Mar 11 2026, 17:20:07) [GCC 14.3.0]                                                                                                                  setup_common.py:28
                    INFO     Submodule initialized and updated.                                                                                                                                                    setup_common.py:54
                    INFO     Installing python dependencies. This could take a few minutes as it downloads files.                                                                                                   setup_linux.py:14
                    INFO     If this operation ever runs too long, you can rerun this script in verbose mode to check.                                                                                              setup_linux.py:15
                    INFO     Kohya_ss GUI version: v25.2.1                                                                                                                                                        setup_common.py:445
                                                                                                                                                                                                                                     
                    INFO     Installing/Validating requirements from requirements_linux_ipex.txt...                                                                                                               setup_common.py:174
                    INFO     Looking in indexes: https://pypi.org/simple, https://pytorch-extension.intel.com/release-whl/stable/xpu/us/                                                                          setup_common.py:202
                    INFO     Obtaining file://./sd-scripts (from -r                                                                                setup_common.py:202
                             ./requirements.txt (line 38))                                                                                                            
                    INFO     Installing build dependencies: started                                                                                                                                               setup_common.py:202
[04/07/26 01:50:16] INFO     Installing build dependencies: finished with status 'done'                                                                                                                           setup_common.py:202
                    INFO     Checking if build backend supports build_editable: started                                                                                                                           setup_common.py:202
                    INFO     Checking if build backend supports build_editable: finished with status 'done'                                                                                                       setup_common.py:202
                    INFO     Getting requirements to build editable: started                                                                                                                                      setup_common.py:202
                    INFO     Getting requirements to build editable: finished with status 'done'                                                                                                                  setup_common.py:202
                    INFO     Preparing editable metadata (pyproject.toml): started                                                                                                                                setup_common.py:202
[04/07/26 01:50:17] INFO     Preparing editable metadata (pyproject.toml): finished with status 'done'                                                                                                            setup_common.py:202
[04/07/26 01:50:18] INFO     Collecting torch==2.3.1+cxx11.abi (from -r requirements_linux_ipex.txt (line 4))                                                                                                     setup_common.py:202
                    INFO     Using cached https://download.pytorch-extension.intel.com/ipex_stable/xpu/./torch-2.3.1%2Bcxx11.abi-cp311-cp311-linux_x86_64.whl (195.3 MB)                                          setup_common.py:202
[04/07/26 01:50:19] INFO     Collecting torchvision==0.18.1+cxx11.abi (from -r requirements_linux_ipex.txt (line 5))                                                                                              setup_common.py:202
                    INFO     Using cached https://download.pytorch-extension.intel.com/ipex_stable/xpu/./torchvision-0.18.1%2Bcxx11.abi-cp311-cp311-linux_x86_64.whl (987 kB)                                     setup_common.py:202
[04/07/26 01:50:20] INFO     Collecting intel-extension-for-pytorch==2.3.110+xpu (from -r requirements_linux_ipex.txt (line 6))                                                                                   setup_common.py:202
[04/07/26 01:50:21] ERROR    Failed to install requirements from requirements_linux_ipex.txt. Pip command: 'pip install -r requirements_linux_ipex.txt'. Exit code: 1                                             setup_common.py:207
                    ERROR    Pip stderr: ERROR: HTTP error 403 while getting                                                                                                                                      setup_common.py:211
                             https://download.pytorch-extension.intel.com/ipex_stable/xpu/./intel_extension_for_pytorch-2.3.110%2Bxpu-cp311-cp311-linux_x86_64.whl (from                                                             
                             https://pytorch-extension.intel.com/release-whl/stable/xpu/us/intel-extension-for-pytorch/)                                                                                                             
                             ERROR: Could not install requirement intel-extension-for-pytorch==2.3.110+xpu from                                                                                                                      
                             https://download.pytorch-extension.intel.com/ipex_stable/xpu/./intel_extension_for_pytorch-2.3.110%2Bxpu-cp311-cp311-linux_x86_64.whl (from -r requirements_linux_ipex.txt (line 6))                    
                             because of HTTP error 403 Client Error: Forbidden for url:                                                                                                                                              
                             https://download.pytorch-extension.intel.com/ipex_stable/xpu/intel_extension_for_pytorch-2.3.110%2Bxpu-cp311-cp311-linux_x86_64.whl for URL                                                             
                             https://download.pytorch-extension.intel.com/ipex_stable/xpu/./intel_extension_for_pytorch-2.3.110%2Bxpu-cp311-cp311-linux_x86_64.whl (from                                                             
                             https://pytorch-extension.intel.com/release-whl/stable/xpu/us/intel-extension-for-pytorch/)                                                                                                             
                    ERROR    Please check the requirements file path, your internet connection, and ensure pip is functioning correctly.                                                                          setup_common.py:212
                    INFO     Configuring accelerate...                                                                                                                                                            setup_common.py:235
                    WARNING  Could not automatically configure accelerate. Please manually configure accelerate with the option in the menu or with: accelerate config.                                           setup_common.py:308
Setup finished! Run ./gui.sh to start.
Please note if you'd like to expose your public server you need to run ./gui.sh --share

```
