### ISSUE TITLE
Cannot find libcudart.so

### ISSUE THREAD

**Issue by mtdkmgw** [bmaltais/kohya_ss#64]
When I was trying to train Dreambooth LoRA and Dreambooth, an error occured. I have tried reinstall CUDA but it doesn't work.

> ===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please submit your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
For effortless bug reporting copy-paste your error into this form: https://docs.google.com/forms/d/e/1FAIpQLScPB8emS3Thkp66nvqwmjTEgxp8Y9ufuWTzFyr9kJ5AoI47dQ/viewform?usp=sf_link
================================================================================
CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching /usr/local/cuda/lib64...
C:\Users\moti9\AppData\Local\Programs\Python\Python310\lib\site-packages\bitsandbytes\cuda_setup\paths.py:27: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {WindowsPath('/usr/local/cuda/lib64')}
  warn(
WARNING: No libcudart.so found! Install CUDA or the cudatoolkit package (anaconda)!
CUDA SETUP: Loading binary C:\Users\moti9\AppData\Local\Programs\Python\Python310\lib\site-packages\bitsandbytes\libbitsandbytes_cpu.so...
Traceback (most recent call last):
  File "E:\kohya\kohya_ss\train_network.py", line 427, in <module>
    train(args)
  File "E:\kohya\kohya_ss\train_network.py", line 114, in train
    import bitsandbytes as bnb
  File "C:\Users\moti9\AppData\Local\Programs\Python\Python310\lib\site-packages\bitsandbytes\__init__.py", line 6, in <module>
    from .autograd._functions import (
  File "C:\Users\moti9\AppData\Local\Programs\Python\Python310\lib\site-packages\bitsandbytes\autograd\_functions.py", line 5, in <module>
    import bitsandbytes.functional as F
  File "C:\Users\moti9\AppData\Local\Programs\Python\Python310\lib\site-packages\bitsandbytes\functional.py", line 13, in <module>
    from .cextension import COMPILED_WITH_CUDA, lib
  File "C:\Users\moti9\AppData\Local\Programs\Python\Python310\lib\site-packages\bitsandbytes\cextension.py", line 41, in <module>
    lib = CUDALibrary_Singleton.get_instance().lib
  File "C:\Users\moti9\AppData\Local\Programs\Python\Python310\lib\site-packages\bitsandbytes\cextension.py", line 37, in get_instance
    cls._instance.initialize()
  File "C:\Users\moti9\AppData\Local\Programs\Python\Python310\lib\site-packages\bitsandbytes\cextension.py", line 31, in initialize
    self.lib = ct.cdll.LoadLibrary(binary_path)
  File "C:\Users\moti9\AppData\Local\Programs\Python\Python310\lib\ctypes\__init__.py", line 452, in LoadLibrary
    return self._dlltype(name)
  File "C:\Users\moti9\AppData\Local\Programs\Python\Python310\lib\ctypes\__init__.py", line 364, in __init__
    if '/' in name or '\\' in name:
TypeError: argument of type 'WindowsPath' is not iterable
Traceback (most recent call last):
  File "C:\Users\moti9\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\moti9\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\moti9\AppData\Local\Programs\Python\Python310\Scripts\accelerate.exe\__main__.py", line 7, in <module>
  File "C:\Users\moti9\AppData\Local\Programs\Python\Python310\lib\site-packages\accelerate\commands\accelerate_cli.py", line 45, in main
    args.func(args)
  File "C:\Users\moti9\AppData\Local\Programs\Python\Python310\lib\site-packages\accelerate\commands\launch.py", line 1104, in launch_command
    simple_launcher(args)
  File "C:\Users\moti9\AppData\Local\Programs\Python\Python310\lib\site-packages\accelerate\commands\launch.py", line 567, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['C:\\Users\\moti9\\AppData\\Local\\Programs\\Python\\Python310\\python.exe', 'train_network.py', '--enable_bucket', '--pretrained_model_name_or_path=E:/dreambooth/stable-diffusion-webui/models/Stable-diffusion/anything-v4.0.ckpt', '--train_data_dir=E:\\dataset\\aaa', '--resolution=512,512', '--output_dir=E:\\dataset\\aaa', '--logging_dir=', '--network_module=networks.lora', '--text_encoder_lr=1.5e-5', '--unet_lr=1.5e-4', '--network_dim=128', '--output_name=layla', '--learning_rate=1.5e-5', '--lr_scheduler=constant_with_warmup', '--lr_warmup_steps=163', '--train_batch_size=1', '--max_train_steps=3255', '--save_every_n_epochs=5', '--mixed_precision=fp16', '--save_precision=fp16', '--seed=1234', '--cache_latents', '--clip_skip=2', '--shuffle_caption', '--xformers', '--use_8bit_adam']' returned non-zero exit status 1.

**Comment by bmaltais** [comment]
Make sure Nvidia CUDA is properly installed on Windows: https://developer.download.nvidia.com/compute/cuda/12.0.0/local_installers/cuda_12.0.0_527.41_windows.exe

This should help fix this issue.

**Comment by mtdkmgw** [comment]
Thank you for your reply. After reinstalling CUDA, the same error occured again. But when I unselected using 8bit adam, the problem solved. It seems that the 8bit adam causes the issue.

**Comment by bmaltais** [comment]
This is most certainly related to a failed module installation. If you run `pip freeze` in a powershell terminal without the venv activated, do you get any packages listed? If so, they are probably causing an issue with the installation in the venv. Best is to not install local python modules outside the venv as they take precedence over the venv ones.
