### ISSUE TITLE
CUDA out of memory

### ISSUE THREAD

**Issue by hedaoming** [bmaltais/kohya_ss#745]
Hello. I encountered a CUDA out of memory error while training with DreamBooth Lora.I would appreciate any help or suggestions to resolve these issues. Thank you!

System：ubuntu
GPU：NVIDIA GeForce RTX 2080 Ti 11GB，During training, all 8 GPUs are utilized
Try: I have tried using AdamW and AdamW8bit optimizers, and also enabled "Gradient checkpointing" and "Memory efficient attention"

1. Here are some log detail

```
Use DreamBooth method.

[Dataset 0]
loading image sizes.
100%|██████████| 30/30 [00:00<00:00, 6144.30it/s]
make buckets
min_bucket_reso and max_bucket_reso are ignored if bucket_no_upscale is set, because bucket reso is defined by image size automatically / bucket_no_upscaleが指定された場合は、bucketの解像度は画像サイズから自動計算されるため、min_bucket_resoとmax_bucket_resoは無視されます
number of images (including repeats) / 各bucketの画像枚数（繰り返し回数を含む）
bucket 0: resolution (512, 512), count: 1500
mean ar error (without repeats): 0.0
prepare images.
found directory /data1/lora/talkShow/img/50_talkShow2 contains 30 image files
1500 train images with repeating.
0 reg images.
no regularization images / 正則化画像が見つかりませんでした
[Dataset 0]
  batch_size: 1
  resolution: (512, 512)
  enable_bucket: True
  min_bucket_reso: 256
  max_bucket_reso: 1024
  bucket_reso_steps: 64
  bucket_no_upscale: True

  [Subset 0 of Dataset 0]
    image_dir: "/data1/lora/talkShow/img/50_talkShow2"
    image_count: 30
    num_repeats: 50
    shuffle_caption: False
    keep_tokens: 0
    caption_dropout_rate: 0.0
    caption_dropout_every_n_epoches: 0
    caption_tag_dropout_rate: 0.0
    color_aug: False
    flip_aug: False
    face_crop_aug_range: None
    random_crop: False
    token_warmup_min: 1,
    token_warmup_step: 0,
    is_reg: False
    class_tokens: talkShow2
    caption_extension: .txt


[Dataset 0]
loading image sizes.
  0%|          | 0/30 [00:00<?, ?it/s]prepare accelerator
/data1/kohya_ss/venv/lib/python3.10/site-packages/accelerate/accelerator.py:249: FutureWarning: `logging_dir` is deprecated and will be removed in version 0.18.0 of 🤗 Accelerate. Use `project_dir` instead.
  warnings.warn(
100%|██████████| 30/30 [00:00<00:00, 5017.91it/s]
make buckets
min_bucket_reso and max_bucket_reso are ignored if bucket_no_upscale is set, because bucket reso is defined by image size automatically / bucket_no_upscaleが指定された場合は、bucketの解像度は画像サイズから自動計算されるため、min_bucket_resoとmax_bucket_resoは無視されます
number of images (including repeats) / 各bucketの画像枚数（繰り返し回数を含む）
bucket 0: resolution (512, 512), count: 1500
mean ar error (without repeats): 0.0
prepare accelerator
/data1/kohya_ss/venv/lib/python3.10/site-packages/accelerate/accelerator.py:249: FutureWarning: `logging_dir` is deprecated and will be removed in version 0.18.0 of 🤗 Accelerate. Use `project_dir` instead.
  warnings.warn(
Using accelerator 0.15.0 or above.
load Diffusers pretrained models
Fetching 15 files: 100%|██████████| 15/15 [00:00<00:00, 64461.64it/s]
You have disabled the safety checker for <class 'diffusers.pipelines.stable_diffusion.pipeline_stable_diffusion.StableDiffusionPipeline'> by passing `safety_checker=None`. Ensure that you abide to the conditions of the Stable Diffusion license and do not expose unfiltered results in services or applications open to the public. Both the diffusers team and Hugging Face strongly recommend to keep the safety filter enabled in all public facing circumstances, disabling it only for use-cases that involve analyzing network behavior or auditing its results. For more information, please have a look at https://github.com/huggingface/diffusers/pull/254 .
Replace CrossAttention.forward to use FlashAttention (not xformers)Replace CrossAttention.forward to use FlashAttention (not xformers)Replace CrossAttention.forward to use FlashAttention (not xformers)Replace CrossAttention.forward to use FlashAttention (not xformers)Replace CrossAttention.forward to use FlashAttention (not xformers)
Replace CrossAttention.forward to use FlashAttention (not xformers)Replace CrossAttention.forward to use FlashAttention (not xformers)


[Dataset 0]
caching latents.
100%|██████████| 30/30 [00:03<00:00,  9.30it/s]
import network module:import network module:import network module:import network module:import network module:import network module: import network module:     networks.lora networks.loranetworks.loranetworks.loranetworks.loranetworks.lora
networks.lora
create LoRA network. base dim (rank): 128, alpha: 128.0create LoRA network. base dim (rank): 128, alpha: 128.0
create LoRA network. base dim (rank): 128, alpha: 128.0
create LoRA for Text Encoder: 72 modules.
create LoRA for U-Net: 192 modules.
enable LoRA for text encoder
enable LoRA for U-Net
prepare optimizer, data loader etc.
use AdamW optimizer | {}
create LoRA for U-Net: 192 modules.
enable LoRA for text encoder
prepare optimizer, data loader etc.
enable LoRA for U-Net
use AdamW optimizer | {}
prepare optimizer, data loader etc.use AdamW optimizer | {}

use AdamW optimizer | {}
Traceback (most recent call last):
  File "/data1/kohya_ss/train_network.py", line 773, in <module>
    train(args)
  File "/data1/kohya_ss/train_network.py", line 250, in train
    unet, text_encoder, network, optimizer, train_dataloader, lr_scheduler = accelerator.prepare(
  File "/data1/kohya_ss/venv/lib/python3.10/site-packages/accelerate/accelerator.py", line 1122, in prepare
    result = tuple(
  File "/data1/kohya_ss/venv/lib/python3.10/site-packages/accelerate/accelerator.py", line 1123, in <genexpr>
    self._prepare_one(obj, first_pass=True, device_placement=d) for obj, d in zip(args, device_placement)
  File "/data1/kohya_ss/venv/lib/python3.10/site-packages/accelerate/accelerator.py", line 977, in _prepare_one
    return self.prepare_model(obj, device_placement=device_placement)
  File "/data1/kohya_ss/venv/lib/python3.10/site-packages/accelerate/accelerator.py", line 1202, in prepare_model
    model = torch.nn.parallel.DistributedDataParallel(
  File "/data1/kohya_ss/venv/lib/python3.10/site-packages/torch/nn/parallel/distributed.py", line 658, in __init__
    self._ddp_init_helper(
  File "/data1/kohya_ss/venv/lib/python3.10/site-packages/torch/nn/parallel/distributed.py", line 724, in _ddp_init_helper
    self.reducer = dist.Reducer(
RuntimeError: CUDA out of memory. Tried to allocate 3.20 GiB (GPU 0; 10.76 GiB total capacity; 3.22 GiB already allocated; 3.18 GiB free; 3.28 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 45737 closing signal SIGTERM
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 45738 closing signal SIGTERM
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 45739 closing signal SIGTERM
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 45740 closing signal SIGTERM
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 45741 closing signal SIGTERM
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 45742 closing signal SIGTERM
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 45736) of binary: /data1/kohya_ss/venv/bin/python
Traceback (most recent call last):
  File "/data1/kohya_ss/venv/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/data1/kohya_ss/venv/lib/python3.10/site-packages/accelerate/commands/accelerate_cli.py", line 45, in main
    args.func(args)
  File "/data1/kohya_ss/venv/lib/python3.10/site-packages/accelerate/commands/launch.py", line 914, in launch_command
    multi_gpu_launcher(args)
  File "/data1/kohya_ss/venv/lib/python3.10/site-packages/accelerate/commands/launch.py", line 603, in multi_gpu_launcher
    distrib_run.run(args)
  File "/data1/kohya_ss/venv/lib/python3.10/site-packages/torch/distributed/run.py", line 752, in run
    elastic_launch(
  File "/data1/kohya_ss/venv/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/data1/kohya_ss/venv/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 245, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
train_network.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-05-09_14:36:57
  host      : ubuntu
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 45736)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================



```

2. My config
```
{
  "pretrained_model_name_or_path": "runwayml/stable-diffusion-v1-5",
  "v2": false,
  "v_parameterization": false,
  "logging_dir": "/data1/lora/talkShow/log",
  "train_data_dir": "/data1/lora/talkShow/img",
  "reg_data_dir": "",
  "output_dir": "/data/services/ml_projects/stable-diffusion-webui-master/embeddings",
  "max_resolution": "512,512",
  "learning_rate": 0.0001,
  "lr_scheduler": "cosine",
  "lr_warmup": 10,
  "train_batch_size": 1,
  "epoch": 1,
  "save_every_n_epochs": 1,
  "mixed_precision": "fp16",
  "save_precision": "fp16",
  "seed": "1234",
  "num_cpu_threads_per_process": 2,
  "cache_latents": true,
  "cache_latents_to_disk": false,
  "caption_extension": ".txt",
  "enable_bucket": true,
  "gradient_checkpointing": false,
  "full_fp16": false,
  "no_token_padding": false,
  "stop_text_encoder_training": 0,
  "xformers": true,
  "save_model_as": "safetensors",
  "shuffle_caption": false,
  "save_state": false,
  "resume": "",
  "prior_loss_weight": 1.0,
  "text_encoder_lr": 5e-05,
  "unet_lr": 0.0001,
  "network_dim": 128,
  "lora_network_weights": "",
  "color_aug": false,
  "flip_aug": false,
  "clip_skip": 2,
  "gradient_accumulation_steps": 1.0,
  "mem_eff_attn": false,
  "output_name": "talkShow_v1.0",
  "model_list": "runwayml/stable-diffusion-v1-5",
  "max_token_length": "75",
  "max_train_epochs": "",
  "max_data_loader_n_workers": "1",
  "network_alpha": 128,
  "training_comment": "",
  "keep_tokens": "0",
  "lr_scheduler_num_cycles": "",
  "lr_scheduler_power": "",
  "persistent_data_loader_workers": false,
  "bucket_no_upscale": true,
  "random_crop": false,
  "bucket_reso_steps": 64.0,
  "caption_dropout_every_n_epochs": 0.0,
  "caption_dropout_rate": 0,
  "optimizer": "AdamW",
  "optimizer_args": "",
  "noise_offset": 0,
  "multires_noise_iterations": 0,
  "multires_noise_discount": 0,
  "LoRA_type": "Standard",
  "conv_dim": 1,
  "conv_alpha": 1,
  "sample_every_n_steps": 0,
  "sample_every_n_epochs": 0,
  "sample_sampler": "euler_a",
  "sample_prompts": "",
  "additional_parameters": "",
  "vae_batch_size": 0,
  "min_snr_gamma": 0,
  "down_lr_weight": "",
  "mid_lr_weight": "",
  "up_lr_weight": "",
  "block_lr_zero_threshold": "",
  "block_dims": "",
  "block_alphas": "",
  "conv_dims": "",
  "conv_alphas": "",
  "weighted_captions": false,
  "unit": 1,
  "save_every_n_steps": 0,
  "save_last_n_steps": 0,
  "save_last_n_steps_state": 0,
  "use_wandb": "",
  "wandb_api_key": false
}
```

**Comment by hedaoming** [comment]
I solved the problem by reconfiguring the GPU using accelerate config. I changed the GPU configuration to run with a single GPU instead of multiple GPUs. When running with multiple GPUs, there was an out of memory error.

```
2023-05-10 14:39:18.589320: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-05-10 14:39:18.773335: E tensorflow/stream_executor/cuda/cuda_blas.cc:2981] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2023-05-10 14:39:19.330622: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /data1/cuda-11.8/lib64:
2023-05-10 14:39:19.330706: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /data1/cuda-11.8/lib64:
2023-05-10 14:39:19.330716: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
-------------------------------------------------------------------------------------------------------------------In which compute environment are you running?
This machine                                                                                                       
-------------------------------------------------------------------------------------------------------------------Which type of machine are you using?                                                                               
No distributed training                                                                                            
Do you want to run your training on CPU only (even if a GPU / Apple Silicon device is available)? [yes/NO]:NO      
Do you wish to optimize your script with torch dynamo?[yes/NO]:NO                                                  
Do you want to use DeepSpeed? [yes/NO]: NO                                                                         
What GPU(s) (by id) should be used for training on this machine as a comma-seperated list? [all]:00000000:1A:00.0  
-------------------------------------------------------------------------------------------------------------------Do you wish to use FP16 or BF16 (mixed precision)?
fp16                                                                                                               
accelerate configuration saved at /data/services/huggingface_cache/.cache/accelerate/default_config.yaml
```

**Comment by saulvic555** [comment]
cheers mate. Had to do a clean install of koyha because of an upgrade error, and was at a loss at how I had gone from using hundreds of images down to less than 50. Copied what you did and its back to normal!
