### ISSUE TITLE
Kohya_SS anomaly since update

### ISSUE THREAD

**Issue by XT-404** [bmaltais/kohya_ss#875]
Hello Mrs, Mr, I allow myself to ask you following a huge anomaly.

since the update that took place 2 to 3 days ago on Kohya I have been the victim of abnormal bugs 1 I can no longer mount the Batch if I go up to 2 or 3, all crashes
if I reinstall Kohya it's carnage
before i use during install if i wanted experienced or not ect
now I have to make the choice 1 and 1 permanently at the beginning of the installation
Ditto for the end where we must choose FP16 or BF16 or if I have no
nothing works
when I say nothing works the latent caching stays stuck at 0
and don't move
there is a list of totally delusional bugs since this last update which is a mess I have never seen

here is the type of error that I get if I raise the Batch to 2 when I could do it without problem before this update from hell.
namely my graphics card and a 3060 12GB which works perfectly (1 week)
it is since this update that everything is completely derailed
************************************************************************************************************************************
steps:   0%|                                                             | 1/1150 [00:04<1:33:36,  4.89s/it, loss=0.43]Traceback (most recent call last):
  File "D:\kohya_ss\train_network.py", line 783, in <module>
    train(args)
  File "D:\kohya_ss\train_network.py", line 610, in train
    noise_pred = unet(noisy_latents, timesteps, encoder_hidden_states).sample
  File "D:\kohya_ss\venv\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\kohya_ss\venv\lib\site-packages\accelerate\utils\operations.py", line 495, in __call__
    return convert_to_fp32(self.model_forward(*args, **kwargs))
  File "D:\kohya_ss\venv\lib\site-packages\torch\amp\autocast_mode.py", line 12, in decorate_autocast
    return func(*args, **kwargs)
  File "D:\kohya_ss\venv\lib\site-packages\diffusers\models\unet_2d_condition.py", line 407, in forward
    sample = upsample_block(
  File "D:\kohya_ss\venv\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\kohya_ss\venv\lib\site-packages\diffusers\models\unet_2d_blocks.py", line 1203, in forward
    hidden_states = attn(hidden_states, encoder_hidden_states=encoder_hidden_states).sample
  File "D:\kohya_ss\venv\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\kohya_ss\venv\lib\site-packages\diffusers\models\attention.py", line 216, in forward
    hidden_states = block(hidden_states, context=encoder_hidden_states, timestep=timestep)
  File "D:\kohya_ss\venv\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\kohya_ss\venv\lib\site-packages\diffusers\models\attention.py", line 484, in forward
    hidden_states = self.attn1(norm_hidden_states) + hidden_states
  File "D:\kohya_ss\venv\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\kohya_ss\venv\lib\site-packages\diffusers\models\attention.py", line 589, in forward
    hidden_states = self._attention(query, key, value)
  File "D:\kohya_ss\venv\lib\site-packages\diffusers\models\attention.py", line 604, in _attention
    attention_scores = torch.baddbmm(
RuntimeError: CUDA out of memory. Tried to allocate 392.00 MiB (GPU 0; 12.00 GiB total capacity; 10.85 GiB already allocated; 0 bytes free; 11.11 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
steps:   0%|                                                             | 1/1150 [00:06<2:06:45,  6.62s/it, loss=0.43]
Traceback (most recent call last):
  File "C:\Users\Kohya_SS\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Kohya_SS\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "D:\kohya_ss\venv\Scripts\accelerate.exe\__main__.py", line 7, in <module>
  File "D:\kohya_ss\venv\lib\site-packages\accelerate\commands\accelerate_cli.py", line 45, in main
    args.func(args)
  File "D:\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 923, in launch_command
    simple_launcher(args)
  File "D:\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 579, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['D:\\kohya_ss\\venv\\Scripts\\python.exe', 'train_network.py', '--enable_bucket', '--pretrained_model_name_or_path=D:/automatic/models/Stable-diffusion/Oni_A.S.U.R.A.S_MONSTER_StormV1.0.0fp16.safetensors', '--train_data_dir=C:/Users/Kohya_SS/Downloads/testtraining666/img', '--resolution=512,512', '--output_dir=C:/Users/Kohya_SS/Downloads/testtraining666/model', '--logging_dir=C:/Users/Kohya_SS/Downloads/testtraining666/log', '--network_alpha=128', '--save_model_as=safetensors', '--network_module=networks.lora', '--text_encoder_lr=4e-05', '--unet_lr=0.0001', '--network_dim=128', '--output_name=azefgcd', '--lr_scheduler_num_cycles=10', '--learning_rate=0.0001', '--lr_scheduler=constant', '--train_batch_size=2', '--max_train_steps=1150', '--save_every_n_epochs=1', '--mixed_precision=fp16', '--save_precision=fp16', '--cache_latents', '--optimizer_type=AdamW', '--max_data_loader_n_workers=1', '--bucket_reso_steps=64', '--bucket_no_upscale']' returned non-zero exit status 1.
**************************************************************************************************************************
Thanks for your feedback
I have already uninstalled and reinstalled Kohya 20 times.
try modifying the installation parameters
to repair pytorch errors or other nothing helps
I am H24 blocked at Batch 1

**Comment by rjorekit** [comment]
same. this latest update broke everything

**Comment by Djanghost** [comment]
Same...

**Comment by IndolentKheper** [comment]
I think I fixed this by installing the CUDNN 8.6 files. Now training with batch 2, 5460 steps, gonna take about 2.5 hours though which seems... iunno, not fast? Also using a 3060, 12gb VRAM. The CUDA memory error I was getting before installing CUDNN 8.6 made no sense though, said it couldn't allocate around 24MiB in spite of having 2.4-3.4 GiB free.

**Comment by bmaltais** [comment]
It is quite possible the latest code upgrade from kohya's repo might be causing this... Try deleting the bench folder and install from a previous release that used to work until future code updates from Kohya bring things back to what it used to be.

**Comment by neoraoz** [comment]
> It is quite possible the latest code upgrade from kohya's repo might be causing this... Try deleting the bench folder and install from a previous release that used to work until future code updates from Kohya bring things back to what it used to be.

Sorry for my ignorance.
Would you be so kind to le me know how I can get the previous release. I'm kinda new for this github.
Many thanks in advance.
