### ISSUE TITLE
Error no kernel image is available 

### ISSUE THREAD

**Issue by BobbtheBuilder** [bmaltais/kohya_ss#90]
after installing kohya i get the following error when i start training.

Error no kernel image is available for execution on the device at line 167 in file D:\ai\tool\bitsandbytes\csrc\ops.cu
Traceback (most recent call last):
  File "C:\Users\Walter\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Walter\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "E:\AIStuff\kohya_ss\venv\Scripts\accelerate.exe\__main__.py", line 7, in <module>
  File "E:\AIStuff\kohya_ss\venv\lib\site-packages\accelerate\commands\accelerate_cli.py", line 45, in main
    args.func(args)
  File "E:\AIStuff\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 1104, in launch_command
    simple_launcher(args)
  File "E:\AIStuff\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 567, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['E:\\AIStuff\\kohya_ss\\venv\\Scripts\\python.exe', 'train_network.py', '--enable_bucket', '--pretrained_model_name_or_path=E:/AIStuff/stable-diffusion-webui/models/Stable-diffusion/v1-5-pruned-emaonly.ckpt', '--train_data_dir=E:/AIStuff/train/JuanGimenez', '--resolution=512,512', '--output_dir=E:/AIStuff/train/model', '--logging_dir=E:/AIStuff/train/log', '--network_alpha=8', '--save_model_as=safetensors', '--network_module=networks.lora', '--text_encoder_lr=5e-5', '--unet_lr=1e-3', '--network_dim=8', '--output_name=last', '--learning_rate=1e-5', '--lr_scheduler=constant', '--train_batch_size=2', '--max_train_steps=4500', '--save_every_n_epochs=1', '--mixed_precision=fp16', '--save_precision=fp16', '--seed=1234', '--cache_latents', '--xformers', '--use_8bit_adam']' returned non-zero exit status 1.

i do not have your script installed on my d drive. and i deleted everything from scratch multiple times. 

my specs are amd ryzen 1700 with 48gb gpus are amd radeon 6900 and a tesla p40/24gb for compute. 

i configured everything with no as the default prompt suggests. any help would be appreciated.

**Comment by BobbtheBuilder** [comment]
after some more investigation i got it to work by disabling 8bit adam.

**Comment by bmaltais** [comment]
I am surprised it even work on a non NVidia GPU. This solution is really meant to be used on nvdia cards.

**Comment by BobbtheBuilder** [comment]
the p40 is a nvidia gpu. its a pascal based 24gb datacenter card. im not using this on my amd gpu. i have a SD version that works on AMD but its slow and lacks many features from auto1111 so it all runs on my p40. 

https://www.techpowerup.com/gpu-specs/tesla-p40.c2878

**Comment by haqthat** [comment]
> Pascal based cards have no fp16 so we can't use a lot of stuff. Automatic1111 used this trick so we all could at least use his code - [kohya-ss/sd-scripts#44 (comment)](https://github.com/kohya-ss/sd-scripts/issues/44#issuecomment-1375690372) Get that file, and do what it says and it should work. I only have 6gb so I can't DB but for TI I can on my 1060 though not before I did the file change and the new .dll.

Yes confirmed this works!
[https://github.com/james-things/bitsandbytes-prebuilt-all_arch](https://github.com/james-things/bitsandbytes-prebuilt-all_arch)

> This repository contains builds of the bitsandbytes library compiled with the "all" option for GPU architecture support. They are useful if you are running into issues running bitsandbytes on older Nvidia GPUs. In theory, support exists for Kepler, Maxwell, Pascal, Volta, and newer GPUs. This was built and tested on Pascal however, so no guarantees.
