### ISSUE TITLE
Error no kernel image is available for execution on the device

### ISSUE THREAD

**Issue by developer90210brr** [bmaltais/kohya_ss#99]
F:\koya\kohya_ss\venv\lib\site-packages\torch\utils\checkpoint.py:25: UserWarning: None of the inputs have requires_grad=True. Gradients will be None
  warnings.warn("None of the inputs have requires_grad=True. Gradients will be None")
Error no kernel image is available for execution on the device at line 167 in file D:\ai\tool\bitsandbytes\csrc\ops.cu
Traceback (most recent call last):
  File "C:\Users\cassell\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\cassell\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "F:\koya\kohya_ss\venv\Scripts\accelerate.exe\__main__.py", line 7, in <module>
  File "F:\koya\kohya_ss\venv\lib\site-packages\accelerate\commands\accelerate_cli.py", line 45, in main
    args.func(args)
  File "F:\koya\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 1104, in launch_command
    simple_launcher(args)
  File "F:\koya\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 567, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['F:\\koya\\kohya_ss\\venv\\Scripts\\python.exe', 'train_network.py', '--pretrained_model_name_or_path=F:\\stable22\\stable-diffusion-webui\\models\\Stable-diffusion\\uberRealisticPornMerge_urpmv12.safetensors', '--train_data_dir=F:/koya/training data/sssniperwolf2/image', '--resolution=512,512', '--output_dir=F:/koya/training data/sssniperwolf2/model', '--logging_dir=F:/koya/training data/sssniperwolf2/log', '--network_alpha=128', '--save_model_as=safetensors', '--network_module=networks.lora', '--text_encoder_lr=5e-5', '--unet_lr=0.0001', '--network_dim=128', '--output_name=sssniperwolf', '--learning_rate=0.0001', '--lr_scheduler=constant', '--train_batch_size=1', '--max_train_steps=1508', '--save_every_n_epochs=1', '--mixed_precision=fp16', '--save_precision=fp16', '--seed=1234', '--caption_extension=.txt', '--cache_latents', '--max_data_loader_n_workers=1', '--clip_skip=2', '--mem_eff_attn', '--gradient_checkpointing', '--xformers', '--use_8bit_adam']' returned non-zero exit status 1.

ive tried lots of things not sure of this issues i run on a 1070 so my thought was a issues with how old it is

**Comment by BobbtheBuilder** [comment]
i had the same problem. try disabling 8bit adam. i have a feeling pascal cant do 8bit adam. but im not a coder.

**Comment by developer90210brr** [comment]
ill give that a try but ive never had a issue with 8bit adam before

**Comment by developer90210brr** [comment]
> i had the same problem. try disabling 8bit adam. i have a feeling pascal cant do 8bit adam. but im not a coder.

ur a legend it worked great wish i had a paperspace version of this so i can use the quadro rtx5000 but  at least i can train now

**Comment by haqthat** [comment]
> Pascal based cards have no fp16 so we can't use a lot of stuff. Automatic1111 used this trick so we all could at least use his code - [kohya-ss/sd-scripts#44 (comment)](https://github.com/kohya-ss/sd-scripts/issues/44#issuecomment-1375690372) Get that file, and do what it says and it should work. I only have 6gb so I can't DB but for TI I can on my 1060 though not before I did the file change and the new .dll.

Yes confirmed this works!
[https://github.com/james-things/bitsandbytes-prebuilt-all_arch](https://github.com/james-things/bitsandbytes-prebuilt-all_arch)

> This repository contains builds of the bitsandbytes library compiled with the "all" option for GPU architecture support. They are useful if you are running into issues running bitsandbytes on older Nvidia GPUs. In theory, support exists for Kepler, Maxwell, Pascal, Volta, and newer GPUs. This was built and tested on Pascal however, so no guarantees.
